{{- if and .Values.enhancedTrafficManagement.enabled .Values.enhancedTrafficManagement.ambient.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "sandbox.cni.labels" . | nindent 4 }}
  name: {{ include "sandbox.cni.name" . }}
  namespace: {{ include "sandbox.namespace" . }}
{{- end }}
