{{- if .Values.enhancedTrafficManagement.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ include "sandbox.controller.name" . }}
  name: {{ include "sandbox.controller.name" . }}
  namespace: {{ include "sandbox.namespace" . }}
{{- end }}
