// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pilot/pkg/serviceregistry/kube/controller/agentio/extensions/agentioconfig.proto

package extensions

import (
	duration "github.com/golang/protobuf/ptypes/duration"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1alpha3 "istio.io/api/networking/v1alpha3"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WorkloadConfigScope determines the scope of a WorkloadConfig resource.
type WorkloadConfigScope int32

const (
	// WORKLOAD_CONFIG_SCOPE_GLOBAL applies to all workloads in the mesh.
	WorkloadConfigScope_WORKLOAD_CONFIG_SCOPE_GLOBAL WorkloadConfigScope = 0
	// WORKLOAD_CONFIG_SCOPE_NAMESPACE applies only to workloads in the
	// same namespace as the resource.
	WorkloadConfigScope_WORKLOAD_CONFIG_SCOPE_NAMESPACE WorkloadConfigScope = 1
)

// Enum value maps for WorkloadConfigScope.
var (
	WorkloadConfigScope_name = map[int32]string{
		0: "WORKLOAD_CONFIG_SCOPE_GLOBAL",
		1: "WORKLOAD_CONFIG_SCOPE_NAMESPACE",
	}
	WorkloadConfigScope_value = map[string]int32{
		"WORKLOAD_CONFIG_SCOPE_GLOBAL":    0,
		"WORKLOAD_CONFIG_SCOPE_NAMESPACE": 1,
	}
)

func (x WorkloadConfigScope) Enum() *WorkloadConfigScope {
	p := new(WorkloadConfigScope)
	*p = x
	return p
}

func (x WorkloadConfigScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkloadConfigScope) Descriptor() protoreflect.EnumDescriptor {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_enumTypes[0].Descriptor()
}

func (WorkloadConfigScope) Type() protoreflect.EnumType {
	return &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_enumTypes[0]
}

func (x WorkloadConfigScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkloadConfigScope.Descriptor instead.
func (WorkloadConfigScope) EnumDescriptor() ([]byte, []int) {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_rawDescGZIP(), []int{0}
}

// HeaderSendMode mirrors Envoy's ProcessingMode.HeaderSendMode.
type HeaderSendMode int32

const (
	// Use the default behavior (request headers are sent, response headers are not).
	HeaderSendMode_DEFAULT HeaderSendMode = 0
	// Send the header/trailer to the ext_proc server.
	HeaderSendMode_SEND HeaderSendMode = 1
	// Do not send the header/trailer to the ext_proc server.
	HeaderSendMode_SKIP HeaderSendMode = 2
)

// Enum value maps for HeaderSendMode.
var (
	HeaderSendMode_name = map[int32]string{
		0: "DEFAULT",
		1: "SEND",
		2: "SKIP",
	}
	HeaderSendMode_value = map[string]int32{
		"DEFAULT": 0,
		"SEND":    1,
		"SKIP":    2,
	}
)

func (x HeaderSendMode) Enum() *HeaderSendMode {
	p := new(HeaderSendMode)
	*p = x
	return p
}

func (x HeaderSendMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HeaderSendMode) Descriptor() protoreflect.EnumDescriptor {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_enumTypes[1].Descriptor()
}

func (HeaderSendMode) Type() protoreflect.EnumType {
	return &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_enumTypes[1]
}

func (x HeaderSendMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HeaderSendMode.Descriptor instead.
func (HeaderSendMode) EnumDescriptor() ([]byte, []int) {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_rawDescGZIP(), []int{1}
}

// EgressPolicyAction defines the action for matching egress traffic.
type EgressPolicyAction int32

const (
	// Passthrough allows traffic to flow directly to the destination.
	EgressPolicyAction_PASSTHROUGH EgressPolicyAction = 0
	// Deny blocks the traffic.
	EgressPolicyAction_DENY EgressPolicyAction = 1
	// Gateway forwards traffic through the specified egress gateway.
	EgressPolicyAction_GATEWAY EgressPolicyAction = 2
)

// Enum value maps for EgressPolicyAction.
var (
	EgressPolicyAction_name = map[int32]string{
		0: "PASSTHROUGH",
		1: "DENY",
		2: "GATEWAY",
	}
	EgressPolicyAction_value = map[string]int32{
		"PASSTHROUGH": 0,
		"DENY":        1,
		"GATEWAY":     2,
	}
)

func (x EgressPolicyAction) Enum() *EgressPolicyAction {
	p := new(EgressPolicyAction)
	*p = x
	return p
}

func (x EgressPolicyAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EgressPolicyAction) Descriptor() protoreflect.EnumDescriptor {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_enumTypes[2].Descriptor()
}

func (EgressPolicyAction) Type() protoreflect.EnumType {
	return &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_enumTypes[2]
}

func (x EgressPolicyAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EgressPolicyAction.Descriptor instead.
func (EgressPolicyAction) EnumDescriptor() ([]byte, []int) {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_rawDescGZIP(), []int{2}
}

// AgentioConfig is the complete configuration for the agentio controller.
type AgentioConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// External processing provider for sandbox traffic inspection and policy enforcement.
	SandboxExtProc *ExtProcProvider `protobuf:"bytes,1,opt,name=sandbox_ext_proc,json=sandboxExtProc,proto3" json:"sandbox_ext_proc,omitempty"`
	// Ordered list of egress policies. Traffic is evaluated against policies
	// in order; the first matching policy's action is applied.
	EgressPolicies []*EgressPolicy `protobuf:"bytes,2,rep,name=egress_policies,json=egressPolicies,proto3" json:"egress_policies,omitempty"`
	// Filter sandbox labels to reduce xds push size.
	SandboxIgnoredLabels []string `protobuf:"bytes,3,rep,name=sandbox_ignored_labels,json=sandboxIgnoredLabels,proto3" json:"sandbox_ignored_labels,omitempty"`
	// Per-gateway settings; tls_termination lives inside each gateway here so
	// SDS can authorize on-demand cert pulls per gateway.
	EgressGateways []*EgressGateway `protobuf:"bytes,4,rep,name=egress_gateways,json=egressGateways,proto3" json:"egress_gateways,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentioConfig) Reset() {
	*x = AgentioConfig{}
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentioConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentioConfig) ProtoMessage() {}

func (x *AgentioConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentioConfig.ProtoReflect.Descriptor instead.
func (*AgentioConfig) Descriptor() ([]byte, []int) {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_rawDescGZIP(), []int{0}
}

func (x *AgentioConfig) GetSandboxExtProc() *ExtProcProvider {
	if x != nil {
		return x.SandboxExtProc
	}
	return nil
}

func (x *AgentioConfig) GetEgressPolicies() []*EgressPolicy {
	if x != nil {
		return x.EgressPolicies
	}
	return nil
}

func (x *AgentioConfig) GetSandboxIgnoredLabels() []string {
	if x != nil {
		return x.SandboxIgnoredLabels
	}
	return nil
}

func (x *AgentioConfig) GetEgressGateways() []*EgressGateway {
	if x != nil {
		return x.EgressGateways
	}
	return nil
}

// EgressGateway describes a sandbox egress gateway deployment.
// name/namespace match the proxy via ExtractProxyMeta(proxy.ID): namespace
// must match exactly and pod name must be prefixed with `name+"-"` (the
// standard Deployment→ReplicaSet→Pod naming).
type EgressGateway struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deployment name. Doubles as the ServiceAccount name for SDS Authorize
	// (SA == Deployment name == EgressGateway.name convention) and as the pod
	// name prefix for FindEgressGatewayForProxy.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Namespace where the gateway Deployment lives. Compared with the proxy's
	// namespace using strict equality.
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Per-gateway TLS termination policy. nil means this gateway forwards all
	// TLS traffic without termination (waypoint listener falls back to the
	// no-SNI-match protocolMatcher).
	TlsTermination *TlsTerminationConfig `protobuf:"bytes,3,opt,name=tls_termination,json=tlsTermination,proto3" json:"tls_termination,omitempty"`
	// Per-gateway ext_proc override. When set, this gateway uses its own
	// ext_proc endpoint instead of the global AgentioConfig.sandbox_ext_proc.
	// nil means fall back to the global configuration.
	ExtProc *ExtProcProvider `protobuf:"bytes,4,opt,name=ext_proc,json=extProc,proto3" json:"ext_proc,omitempty"`
	// Per-gateway connection pool and timeout settings. Controls HCM
	// StreamIdleTimeout, TCPProxy idle/max-connection-duration, and
	// per-host HTTP route timeouts. nil means use hardcoded defaults
	// (StreamIdleTimeout=30min, TCPProxy IdleTimeout=1h).
	ConnectionPool *ConnectionPoolSettings `protobuf:"bytes,5,opt,name=connection_pool,json=connectionPool,proto3" json:"connection_pool,omitempty"`
	// Per-gateway connect rate limit. Controls the rate at which new
	// H2 CONNECT streams are accepted on the connect_terminate HCM.
	// nil means no rate limiting.
	ConnectRateLimit *LocalRateLimitSettings `protobuf:"bytes,6,opt,name=connect_rate_limit,json=connectRateLimit,proto3" json:"connect_rate_limit,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EgressGateway) Reset() {
	*x = EgressGateway{}
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressGateway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressGateway) ProtoMessage() {}

func (x *EgressGateway) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressGateway.ProtoReflect.Descriptor instead.
func (*EgressGateway) Descriptor() ([]byte, []int) {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_rawDescGZIP(), []int{1}
}

func (x *EgressGateway) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EgressGateway) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *EgressGateway) GetTlsTermination() *TlsTerminationConfig {
	if x != nil {
		return x.TlsTermination
	}
	return nil
}

func (x *EgressGateway) GetExtProc() *ExtProcProvider {
	if x != nil {
		return x.ExtProc
	}
	return nil
}

func (x *EgressGateway) GetConnectionPool() *ConnectionPoolSettings {
	if x != nil {
		return x.ConnectionPool
	}
	return nil
}

func (x *EgressGateway) GetConnectRateLimit() *LocalRateLimitSettings {
	if x != nil {
		return x.ConnectRateLimit
	}
	return nil
}

// TlsTerminationConfig defines which SNI domains should undergo TLS termination
// and which should bypass it in the sandbox waypoint.
type TlsTerminationConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Domains that should undergo TLS termination using on-demand certificates.
	// Supports wildcards (e.g. *.example.com). When a TLS ClientHello's SNI
	// matches one of these domains, traffic is routed to the TLS termination
	// filter chain.
	IncludeHosts []string `protobuf:"bytes,1,rep,name=include_hosts,json=includeHosts,proto3" json:"include_hosts,omitempty"`
	// Domains that should bypass TLS termination. Traffic matching these
	// domains is forwarded as-is via the TCP filter chain without certificate
	// termination. Supports wildcards (e.g. *.internal.com).
	ExcludeHosts  []string `protobuf:"bytes,2,rep,name=exclude_hosts,json=excludeHosts,proto3" json:"exclude_hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TlsTerminationConfig) Reset() {
	*x = TlsTerminationConfig{}
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TlsTerminationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TlsTerminationConfig) ProtoMessage() {}

func (x *TlsTerminationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TlsTerminationConfig.ProtoReflect.Descriptor instead.
func (*TlsTerminationConfig) Descriptor() ([]byte, []int) {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_rawDescGZIP(), []int{2}
}

func (x *TlsTerminationConfig) GetIncludeHosts() []string {
	if x != nil {
		return x.IncludeHosts
	}
	return nil
}

func (x *TlsTerminationConfig) GetExcludeHosts() []string {
	if x != nil {
		return x.ExcludeHosts
	}
	return nil
}

// EgressPolicies is an internal wrapper for marshaling repeated EgressPolicy.
type EgressPolicies struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EgressPolicies []*EgressPolicy        `protobuf:"bytes,1,rep,name=egress_policies,json=egressPolicies,proto3" json:"egress_policies,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EgressPolicies) Reset() {
	*x = EgressPolicies{}
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressPolicies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressPolicies) ProtoMessage() {}

func (x *EgressPolicies) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressPolicies.ProtoReflect.Descriptor instead.
func (*EgressPolicies) Descriptor() ([]byte, []int) {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_rawDescGZIP(), []int{3}
}

func (x *EgressPolicies) GetEgressPolicies() []*EgressPolicy {
	if x != nil {
		return x.EgressPolicies
	}
	return nil
}

// WorkloadConfig is an independent xDS resource pushed to ztunnel.
type WorkloadConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Scope          WorkloadConfigScope    `protobuf:"varint,1,opt,name=scope,proto3,enum=kruise.networking.extensions.v1.WorkloadConfigScope" json:"scope,omitempty"`
	EgressPolicies []*EgressPolicy        `protobuf:"bytes,2,rep,name=egress_policies,json=egressPolicies,proto3" json:"egress_policies,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorkloadConfig) Reset() {
	*x = WorkloadConfig{}
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadConfig) ProtoMessage() {}

func (x *WorkloadConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadConfig.ProtoReflect.Descriptor instead.
func (*WorkloadConfig) Descriptor() ([]byte, []int) {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_rawDescGZIP(), []int{4}
}

func (x *WorkloadConfig) GetScope() WorkloadConfigScope {
	if x != nil {
		return x.Scope
	}
	return WorkloadConfigScope_WORKLOAD_CONFIG_SCOPE_GLOBAL
}

func (x *WorkloadConfig) GetEgressPolicies() []*EgressPolicy {
	if x != nil {
		return x.EgressPolicies
	}
	return nil
}

// ExtProcProvider configures the external processing endpoint.
type ExtProcProvider struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service hostname or address for the ext_proc endpoint.
	Service string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// Service port for the ext_proc endpoint.
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// Request processing mode options.
	Request *ProcessingModeOptions `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	// Response processing mode options.
	Response *ProcessingModeOptions `protobuf:"bytes,4,opt,name=response,proto3" json:"response,omitempty"`
	// If true, the filter will be allowed to continue processing even if the ext_proc
	// server is unavailable or returns an error. Defaults to false.
	FailureModeAllow bool `protobuf:"varint,5,opt,name=failure_mode_allow,json=failureModeAllow,proto3" json:"failure_mode_allow,omitempty"`
	// Cluster-level settings for the ext_proc upstream cluster.
	ClusterSettings *ClusterSettings `protobuf:"bytes,6,opt,name=cluster_settings,json=clusterSettings,proto3" json:"cluster_settings,omitempty"`
	// Timeout for each message sent to the ext_proc server. If the server does not
	// respond within this duration, the request is considered failed.
	// Format: golang duration string (e.g. "200ms", "1s"). Defaults to 200ms if not set.
	MessageTimeout string `protobuf:"bytes,7,opt,name=message_timeout,json=messageTimeout,proto3" json:"message_timeout,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExtProcProvider) Reset() {
	*x = ExtProcProvider{}
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtProcProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtProcProvider) ProtoMessage() {}

func (x *ExtProcProvider) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtProcProvider.ProtoReflect.Descriptor instead.
func (*ExtProcProvider) Descriptor() ([]byte, []int) {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_rawDescGZIP(), []int{5}
}

func (x *ExtProcProvider) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ExtProcProvider) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ExtProcProvider) GetRequest() *ProcessingModeOptions {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ExtProcProvider) GetResponse() *ProcessingModeOptions {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ExtProcProvider) GetFailureModeAllow() bool {
	if x != nil {
		return x.FailureModeAllow
	}
	return false
}

func (x *ExtProcProvider) GetClusterSettings() *ClusterSettings {
	if x != nil {
		return x.ClusterSettings
	}
	return nil
}

func (x *ExtProcProvider) GetMessageTimeout() string {
	if x != nil {
		return x.MessageTimeout
	}
	return ""
}

// ClusterSettings configures upstream cluster behavior.
type ClusterSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTP protocol settings for the upstream cluster.
	Http          *HttpSettings `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterSettings) Reset() {
	*x = ClusterSettings{}
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterSettings) ProtoMessage() {}

func (x *ClusterSettings) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterSettings.ProtoReflect.Descriptor instead.
func (*ClusterSettings) Descriptor() ([]byte, []int) {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_rawDescGZIP(), []int{6}
}

func (x *ClusterSettings) GetHttp() *HttpSettings {
	if x != nil {
		return x.Http
	}
	return nil
}

// HttpSettings configures HTTP/2 protocol options for the upstream cluster.
type HttpSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of concurrent streams per HTTP/2 connection.
	// Defaults to 100 if not set.
	MaxConcurrentStreams uint32 `protobuf:"varint,1,opt,name=max_concurrent_streams,json=maxConcurrentStreams,proto3" json:"max_concurrent_streams,omitempty"`
	// Maximum number of requests per connection before it is closed.
	// 0 means unlimited (default behavior).
	MaxRequestsPerConnection uint32 `protobuf:"varint,2,opt,name=max_requests_per_connection,json=maxRequestsPerConnection,proto3" json:"max_requests_per_connection,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *HttpSettings) Reset() {
	*x = HttpSettings{}
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpSettings) ProtoMessage() {}

func (x *HttpSettings) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpSettings.ProtoReflect.Descriptor instead.
func (*HttpSettings) Descriptor() ([]byte, []int) {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_rawDescGZIP(), []int{7}
}

func (x *HttpSettings) GetMaxConcurrentStreams() uint32 {
	if x != nil {
		return x.MaxConcurrentStreams
	}
	return 0
}

func (x *HttpSettings) GetMaxRequestsPerConnection() uint32 {
	if x != nil {
		return x.MaxRequestsPerConnection
	}
	return 0
}

type ProcessingModeOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Header send mode: DEFAULT, SEND, or SKIP.
	HeaderMode HeaderSendMode `protobuf:"varint,1,opt,name=header_mode,json=headerMode,proto3,enum=kruise.networking.extensions.v1.HeaderSendMode" json:"header_mode,omitempty"`
	// Attributes to include in ext_proc headers.
	Attributes    []string `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessingModeOptions) Reset() {
	*x = ProcessingModeOptions{}
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingModeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingModeOptions) ProtoMessage() {}

func (x *ProcessingModeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingModeOptions.ProtoReflect.Descriptor instead.
func (*ProcessingModeOptions) Descriptor() ([]byte, []int) {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_rawDescGZIP(), []int{8}
}

func (x *ProcessingModeOptions) GetHeaderMode() HeaderSendMode {
	if x != nil {
		return x.HeaderMode
	}
	return HeaderSendMode_DEFAULT
}

func (x *ProcessingModeOptions) GetAttributes() []string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// EgressPolicy defines a rule for handling egress traffic.
// Traffic is evaluated in order; the first matching policy applies.
type EgressPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Namespaces restricts this policy to traffic originating from these namespaces.
	// If empty, the policy applies to all namespaces.
	Namespaces []string `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	// MatchCidrs specifies the destination CIDR ranges to match.
	// If empty, matches any destination.
	MatchCidrs []string `protobuf:"bytes,2,rep,name=match_cidrs,json=matchCidrs,proto3" json:"match_cidrs,omitempty"`
	// MatchPorts specifies the destination ports to match. Each entry is a
	// single port number as a decimal string (e.g. "443", "8080"). If empty,
	// matches any destination port. A traffic flow matches the policy only
	// when both match_cidrs and match_ports match (empty means wildcard on
	// that dimension).
	MatchPorts []string `protobuf:"bytes,5,rep,name=match_ports,json=matchPorts,proto3" json:"match_ports,omitempty"`
	// Policy defines the action to take for matching traffic.
	Policy EgressPolicyAction `protobuf:"varint,3,opt,name=policy,proto3,enum=kruise.networking.extensions.v1.EgressPolicyAction" json:"policy,omitempty"`
	// Gateway is the egress gateway address to forward traffic to (when policy is GATEWAY).
	Gateway *GatewayAddress `protobuf:"bytes,4,opt,name=gateway,proto3" json:"gateway,omitempty"`
	// MatchHosts specifies destination hostnames to match. The control plane
	// resolves these to IP addresses and merges the results into match_cidrs
	// before sending to the data plane. DNS results are refreshed based on TTL.
	MatchHosts    []string `protobuf:"bytes,6,rep,name=match_hosts,json=matchHosts,proto3" json:"match_hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressPolicy) Reset() {
	*x = EgressPolicy{}
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressPolicy) ProtoMessage() {}

func (x *EgressPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressPolicy.ProtoReflect.Descriptor instead.
func (*EgressPolicy) Descriptor() ([]byte, []int) {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_rawDescGZIP(), []int{9}
}

func (x *EgressPolicy) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *EgressPolicy) GetMatchCidrs() []string {
	if x != nil {
		return x.MatchCidrs
	}
	return nil
}

func (x *EgressPolicy) GetMatchPorts() []string {
	if x != nil {
		return x.MatchPorts
	}
	return nil
}

func (x *EgressPolicy) GetPolicy() EgressPolicyAction {
	if x != nil {
		return x.Policy
	}
	return EgressPolicyAction_PASSTHROUGH
}

func (x *EgressPolicy) GetGateway() *GatewayAddress {
	if x != nil {
		return x.Gateway
	}
	return nil
}

func (x *EgressPolicy) GetMatchHosts() []string {
	if x != nil {
		return x.MatchHosts
	}
	return nil
}

// GatewayAddress represents the address of a gateway.
type GatewayAddress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service name of the gateway (e.g. egress-gateway.istio-system.svc.cluster.local).
	Service string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// Port is the port to reach the gateway at.
	Port          uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayAddress) Reset() {
	*x = GatewayAddress{}
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayAddress) ProtoMessage() {}

func (x *GatewayAddress) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayAddress.ProtoReflect.Descriptor instead.
func (*GatewayAddress) Descriptor() ([]byte, []int) {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_rawDescGZIP(), []int{10}
}

func (x *GatewayAddress) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GatewayAddress) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// ConnectionPoolSettings controls timeout and connection management for
// the sandbox egress path. Mirrors the Istio DestinationRule
// ConnectionPoolSettings structure with tcp/http sub-messages.
type ConnectionPoolSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TCP-level connection pool settings.
	Tcp *TcpSettings `protobuf:"bytes,1,opt,name=tcp,proto3" json:"tcp,omitempty"`
	// HTTP-level connection pool and route settings.
	Http          *ConnectionPoolHttpSettings `protobuf:"bytes,2,opt,name=http,proto3" json:"http,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionPoolSettings) Reset() {
	*x = ConnectionPoolSettings{}
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionPoolSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionPoolSettings) ProtoMessage() {}

func (x *ConnectionPoolSettings) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionPoolSettings.ProtoReflect.Descriptor instead.
func (*ConnectionPoolSettings) Descriptor() ([]byte, []int) {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_rawDescGZIP(), []int{11}
}

func (x *ConnectionPoolSettings) GetTcp() *TcpSettings {
	if x != nil {
		return x.Tcp
	}
	return nil
}

func (x *ConnectionPoolSettings) GetHttp() *ConnectionPoolHttpSettings {
	if x != nil {
		return x.Http
	}
	return nil
}

// TcpSettings configures TCP connection timeouts and limits for the
// sandbox egress TCPProxy filters and passthrough path.
type TcpSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum time a TCP connection can be idle before Envoy closes it.
	// Applies to TCPProxy filters on tls-terminate and forward-tcp chains.
	// Default 1h.
	IdleTimeout *duration.Duration `protobuf:"bytes,1,opt,name=idle_timeout,json=idleTimeout,proto3" json:"idle_timeout,omitempty"`
	// Absolute maximum lifetime of a downstream TCP connection regardless
	// of activity. Default unset (no limit).
	MaxConnectionDuration *duration.Duration `protobuf:"bytes,2,opt,name=max_connection_duration,json=maxConnectionDuration,proto3" json:"max_connection_duration,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TcpSettings) Reset() {
	*x = TcpSettings{}
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TcpSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpSettings) ProtoMessage() {}

func (x *TcpSettings) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpSettings.ProtoReflect.Descriptor instead.
func (*TcpSettings) Descriptor() ([]byte, []int) {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_rawDescGZIP(), []int{12}
}

func (x *TcpSettings) GetIdleTimeout() *duration.Duration {
	if x != nil {
		return x.IdleTimeout
	}
	return nil
}

func (x *TcpSettings) GetMaxConnectionDuration() *duration.Duration {
	if x != nil {
		return x.MaxConnectionDuration
	}
	return nil
}

// ConnectionPoolHttpSettings configures HTTP connection manager and
// route-level settings for the sandbox egress HCM.
type ConnectionPoolHttpSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum time a stream (including upgraded WebSocket/SSE) can be idle
	// before Envoy closes it. Applies to the HCM StreamIdleTimeout.
	// Default 30min.
	StreamIdleTimeout *duration.Duration `protobuf:"bytes,1,opt,name=stream_idle_timeout,json=streamIdleTimeout,proto3" json:"stream_idle_timeout,omitempty"`
	// Default route settings applied to the fallback wildcard ("*")
	// VirtualHost. If nil, route timeout is 0 (disabled).
	DefaultRoute *HttpRouteSettings `protobuf:"bytes,2,opt,name=default_route,json=defaultRoute,proto3" json:"default_route,omitempty"`
	// Per-host route overrides. Each entry generates a dedicated VirtualHost
	// with the specified hosts as domains. Evaluated by Envoy's domain
	// matching (exact > suffix > prefix > wildcard).
	RouteOverrides []*HttpRouteOverride `protobuf:"bytes,3,rep,name=route_overrides,json=routeOverrides,proto3" json:"route_overrides,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConnectionPoolHttpSettings) Reset() {
	*x = ConnectionPoolHttpSettings{}
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionPoolHttpSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionPoolHttpSettings) ProtoMessage() {}

func (x *ConnectionPoolHttpSettings) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionPoolHttpSettings.ProtoReflect.Descriptor instead.
func (*ConnectionPoolHttpSettings) Descriptor() ([]byte, []int) {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_rawDescGZIP(), []int{13}
}

func (x *ConnectionPoolHttpSettings) GetStreamIdleTimeout() *duration.Duration {
	if x != nil {
		return x.StreamIdleTimeout
	}
	return nil
}

func (x *ConnectionPoolHttpSettings) GetDefaultRoute() *HttpRouteSettings {
	if x != nil {
		return x.DefaultRoute
	}
	return nil
}

func (x *ConnectionPoolHttpSettings) GetRouteOverrides() []*HttpRouteOverride {
	if x != nil {
		return x.RouteOverrides
	}
	return nil
}

// HttpRouteOverride binds HTTP route settings to a set of destination hosts.
type HttpRouteOverride struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Destination host patterns. Supports exact ("api.example.com") and
	// wildcard ("*.example.com") matching via Envoy VirtualHost domains.
	Hosts []string `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	// Route settings to apply for these hosts.
	Settings      *HttpRouteSettings `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRouteOverride) Reset() {
	*x = HttpRouteOverride{}
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRouteOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRouteOverride) ProtoMessage() {}

func (x *HttpRouteOverride) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRouteOverride.ProtoReflect.Descriptor instead.
func (*HttpRouteOverride) Descriptor() ([]byte, []int) {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_rawDescGZIP(), []int{14}
}

func (x *HttpRouteOverride) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *HttpRouteOverride) GetSettings() *HttpRouteSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

// HttpRouteSettings configures Envoy route-level timeout and retry behavior.
// Fields mirror istio.networking.v1alpha3.HTTPRoute (timeout + retries).
type HttpRouteSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total request timeout. 0 means disabled (Envoy default).
	Timeout *duration.Duration `protobuf:"bytes,1,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// Retry policy for HTTP requests. Uses the Istio HTTPRetry definition.
	Retries       *v1alpha3.HTTPRetry `protobuf:"bytes,2,opt,name=retries,proto3" json:"retries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRouteSettings) Reset() {
	*x = HttpRouteSettings{}
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRouteSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRouteSettings) ProtoMessage() {}

func (x *HttpRouteSettings) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRouteSettings.ProtoReflect.Descriptor instead.
func (*HttpRouteSettings) Descriptor() ([]byte, []int) {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_rawDescGZIP(), []int{15}
}

func (x *HttpRouteSettings) GetTimeout() *duration.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *HttpRouteSettings) GetRetries() *v1alpha3.HTTPRetry {
	if x != nil {
		return x.Retries
	}
	return nil
}

// LocalRateLimitSettings configures Envoy's local rate limit HTTP filter
// on the connect_terminate HCM. Each new H2 CONNECT stream (= one client
// TCP connection) consumes one token from the bucket.
type LocalRateLimitSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Global token bucket applied to all streams on this gateway.
	// Acts as the default when no descriptor matches. If unset, only
	// descriptor-level rate limits apply.
	TokenBucket *TokenBucket `protobuf:"bytes,1,opt,name=token_bucket,json=tokenBucket,proto3" json:"token_bucket,omitempty"`
	// Per-descriptor rate limit overrides. The first descriptor whose
	// entries fully match the request uses its own token bucket.
	Descriptors []*RateLimitDescriptor `protobuf:"bytes,2,rep,name=descriptors,proto3" json:"descriptors,omitempty"`
	// When true, each downstream H2 connection (ztunnel → waypoint) gets
	// its own token bucket. Default false (shared across all connections).
	// Cannot be used together with wildcard descriptor values.
	PerDownstreamConnection bool `protobuf:"varint,3,opt,name=per_downstream_connection,json=perDownstreamConnection,proto3" json:"per_downstream_connection,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *LocalRateLimitSettings) Reset() {
	*x = LocalRateLimitSettings{}
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalRateLimitSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalRateLimitSettings) ProtoMessage() {}

func (x *LocalRateLimitSettings) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalRateLimitSettings.ProtoReflect.Descriptor instead.
func (*LocalRateLimitSettings) Descriptor() ([]byte, []int) {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_rawDescGZIP(), []int{16}
}

func (x *LocalRateLimitSettings) GetTokenBucket() *TokenBucket {
	if x != nil {
		return x.TokenBucket
	}
	return nil
}

func (x *LocalRateLimitSettings) GetDescriptors() []*RateLimitDescriptor {
	if x != nil {
		return x.Descriptors
	}
	return nil
}

func (x *LocalRateLimitSettings) GetPerDownstreamConnection() bool {
	if x != nil {
		return x.PerDownstreamConnection
	}
	return false
}

// TokenBucket configures a token bucket rate limiter.
type TokenBucket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum tokens the bucket can hold. Also the initial token count.
	MaxTokens uint32 `protobuf:"varint,1,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	// Tokens added per fill_interval. Defaults to 1 if not set.
	TokensPerFill uint32 `protobuf:"varint,2,opt,name=tokens_per_fill,json=tokensPerFill,proto3" json:"tokens_per_fill,omitempty"`
	// Interval at which tokens_per_fill tokens are added to the bucket.
	// Must be >= 50ms.
	FillInterval  *duration.Duration `protobuf:"bytes,3,opt,name=fill_interval,json=fillInterval,proto3" json:"fill_interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenBucket) Reset() {
	*x = TokenBucket{}
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenBucket) ProtoMessage() {}

func (x *TokenBucket) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenBucket.ProtoReflect.Descriptor instead.
func (*TokenBucket) Descriptor() ([]byte, []int) {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_rawDescGZIP(), []int{17}
}

func (x *TokenBucket) GetMaxTokens() uint32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *TokenBucket) GetTokensPerFill() uint32 {
	if x != nil {
		return x.TokensPerFill
	}
	return 0
}

func (x *TokenBucket) GetFillInterval() *duration.Duration {
	if x != nil {
		return x.FillInterval
	}
	return nil
}

// RateLimitDescriptor defines a set of descriptor entries and an
// associated token bucket. When all entries match, this descriptor's
// bucket is used instead of (or in addition to) the global bucket.
type RateLimitDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Entries that must all match for this descriptor to apply.
	Entries []*RateLimitEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	// Token bucket for streams matching this descriptor.
	TokenBucket   *TokenBucket `protobuf:"bytes,2,opt,name=token_bucket,json=tokenBucket,proto3" json:"token_bucket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimitDescriptor) Reset() {
	*x = RateLimitDescriptor{}
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitDescriptor) ProtoMessage() {}

func (x *RateLimitDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitDescriptor.ProtoReflect.Descriptor instead.
func (*RateLimitDescriptor) Descriptor() ([]byte, []int) {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_rawDescGZIP(), []int{18}
}

func (x *RateLimitDescriptor) GetEntries() []*RateLimitEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *RateLimitDescriptor) GetTokenBucket() *TokenBucket {
	if x != nil {
		return x.TokenBucket
	}
	return nil
}

// RateLimitEntry is a single key/value pair in a rate limit descriptor.
type RateLimitEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Descriptor key used in the Envoy descriptor matching.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Descriptor value to match. An empty string acts as a wildcard,
	// creating a dynamic per-unique-value token bucket (e.g. per-IP).
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// CEL expression that produces the descriptor value at runtime.
	// Uses the envoy.rate_limit_descriptors.expr extension. The
	// expression has access to filter_state, e.g.:
	//
	//	filter_state["downstream_peer"].name
	//	filter_state["downstream_peer"].namespace
	//	filter_state["io.istio.peer_principal"]
	Cel           string `protobuf:"bytes,3,opt,name=cel,proto3" json:"cel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimitEntry) Reset() {
	*x = RateLimitEntry{}
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitEntry) ProtoMessage() {}

func (x *RateLimitEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitEntry.ProtoReflect.Descriptor instead.
func (*RateLimitEntry) Descriptor() ([]byte, []int) {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_rawDescGZIP(), []int{19}
}

func (x *RateLimitEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RateLimitEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *RateLimitEntry) GetCel() string {
	if x != nil {
		return x.Cel
	}
	return ""
}

var File_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto protoreflect.FileDescriptor

const file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_rawDesc = "" +
	"\n" +
	"Ppilot/pkg/serviceregistry/kube/controller/agentio/extensions/agentioconfig.proto\x12\x1fkruise.networking.extensions.v1\x1a\x1egoogle/protobuf/duration.proto\x1a)networking/v1alpha3/virtual_service.proto\"\xd2\x02\n" +
	"\rAgentioConfig\x12Z\n" +
	"\x10sandbox_ext_proc\x18\x01 \x01(\v20.kruise.networking.extensions.v1.ExtProcProviderR\x0esandboxExtProc\x12V\n" +
	"\x0fegress_policies\x18\x02 \x03(\v2-.kruise.networking.extensions.v1.EgressPolicyR\x0eegressPolicies\x124\n" +
	"\x16sandbox_ignored_labels\x18\x03 \x03(\tR\x14sandboxIgnoredLabels\x12W\n" +
	"\x0fegress_gateways\x18\x04 \x03(\v2..kruise.networking.extensions.v1.EgressGatewayR\x0eegressGateways\"\xb7\x03\n" +
	"\rEgressGateway\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12^\n" +
	"\x0ftls_termination\x18\x03 \x01(\v25.kruise.networking.extensions.v1.TlsTerminationConfigR\x0etlsTermination\x12K\n" +
	"\bext_proc\x18\x04 \x01(\v20.kruise.networking.extensions.v1.ExtProcProviderR\aextProc\x12`\n" +
	"\x0fconnection_pool\x18\x05 \x01(\v27.kruise.networking.extensions.v1.ConnectionPoolSettingsR\x0econnectionPool\x12e\n" +
	"\x12connect_rate_limit\x18\x06 \x01(\v27.kruise.networking.extensions.v1.LocalRateLimitSettingsR\x10connectRateLimit\"`\n" +
	"\x14TlsTerminationConfig\x12#\n" +
	"\rinclude_hosts\x18\x01 \x03(\tR\fincludeHosts\x12#\n" +
	"\rexclude_hosts\x18\x02 \x03(\tR\fexcludeHosts\"h\n" +
	"\x0eEgressPolicies\x12V\n" +
	"\x0fegress_policies\x18\x01 \x03(\v2-.kruise.networking.extensions.v1.EgressPolicyR\x0eegressPolicies\"\xb4\x01\n" +
	"\x0eWorkloadConfig\x12J\n" +
	"\x05scope\x18\x01 \x01(\x0e24.kruise.networking.extensions.v1.WorkloadConfigScopeR\x05scope\x12V\n" +
	"\x0fegress_policies\x18\x02 \x03(\v2-.kruise.networking.extensions.v1.EgressPolicyR\x0eegressPolicies\"\x99\x03\n" +
	"\x0fExtProcProvider\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12P\n" +
	"\arequest\x18\x03 \x01(\v26.kruise.networking.extensions.v1.ProcessingModeOptionsR\arequest\x12R\n" +
	"\bresponse\x18\x04 \x01(\v26.kruise.networking.extensions.v1.ProcessingModeOptionsR\bresponse\x12,\n" +
	"\x12failure_mode_allow\x18\x05 \x01(\bR\x10failureModeAllow\x12[\n" +
	"\x10cluster_settings\x18\x06 \x01(\v20.kruise.networking.extensions.v1.ClusterSettingsR\x0fclusterSettings\x12'\n" +
	"\x0fmessage_timeout\x18\a \x01(\tR\x0emessageTimeout\"T\n" +
	"\x0fClusterSettings\x12A\n" +
	"\x04http\x18\x01 \x01(\v2-.kruise.networking.extensions.v1.HttpSettingsR\x04http\"\x83\x01\n" +
	"\fHttpSettings\x124\n" +
	"\x16max_concurrent_streams\x18\x01 \x01(\rR\x14maxConcurrentStreams\x12=\n" +
	"\x1bmax_requests_per_connection\x18\x02 \x01(\rR\x18maxRequestsPerConnection\"\x89\x01\n" +
	"\x15ProcessingModeOptions\x12P\n" +
	"\vheader_mode\x18\x01 \x01(\x0e2/.kruise.networking.extensions.v1.HeaderSendModeR\n" +
	"headerMode\x12\x1e\n" +
	"\n" +
	"attributes\x18\x02 \x03(\tR\n" +
	"attributes\"\xa9\x02\n" +
	"\fEgressPolicy\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\tR\n" +
	"namespaces\x12\x1f\n" +
	"\vmatch_cidrs\x18\x02 \x03(\tR\n" +
	"matchCidrs\x12\x1f\n" +
	"\vmatch_ports\x18\x05 \x03(\tR\n" +
	"matchPorts\x12K\n" +
	"\x06policy\x18\x03 \x01(\x0e23.kruise.networking.extensions.v1.EgressPolicyActionR\x06policy\x12I\n" +
	"\agateway\x18\x04 \x01(\v2/.kruise.networking.extensions.v1.GatewayAddressR\agateway\x12\x1f\n" +
	"\vmatch_hosts\x18\x06 \x03(\tR\n" +
	"matchHosts\">\n" +
	"\x0eGatewayAddress\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"\xa9\x01\n" +
	"\x16ConnectionPoolSettings\x12>\n" +
	"\x03tcp\x18\x01 \x01(\v2,.kruise.networking.extensions.v1.TcpSettingsR\x03tcp\x12O\n" +
	"\x04http\x18\x02 \x01(\v2;.kruise.networking.extensions.v1.ConnectionPoolHttpSettingsR\x04http\"\x9e\x01\n" +
	"\vTcpSettings\x12<\n" +
	"\fidle_timeout\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\vidleTimeout\x12Q\n" +
	"\x17max_connection_duration\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x15maxConnectionDuration\"\x9d\x02\n" +
	"\x1aConnectionPoolHttpSettings\x12I\n" +
	"\x13stream_idle_timeout\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x11streamIdleTimeout\x12W\n" +
	"\rdefault_route\x18\x02 \x01(\v22.kruise.networking.extensions.v1.HttpRouteSettingsR\fdefaultRoute\x12[\n" +
	"\x0froute_overrides\x18\x03 \x03(\v22.kruise.networking.extensions.v1.HttpRouteOverrideR\x0erouteOverrides\"y\n" +
	"\x11HttpRouteOverride\x12\x14\n" +
	"\x05hosts\x18\x01 \x03(\tR\x05hosts\x12N\n" +
	"\bsettings\x18\x02 \x01(\v22.kruise.networking.extensions.v1.HttpRouteSettingsR\bsettings\"\x88\x01\n" +
	"\x11HttpRouteSettings\x123\n" +
	"\atimeout\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12>\n" +
	"\aretries\x18\x02 \x01(\v2$.istio.networking.v1alpha3.HTTPRetryR\aretries\"\xfd\x01\n" +
	"\x16LocalRateLimitSettings\x12O\n" +
	"\ftoken_bucket\x18\x01 \x01(\v2,.kruise.networking.extensions.v1.TokenBucketR\vtokenBucket\x12V\n" +
	"\vdescriptors\x18\x02 \x03(\v24.kruise.networking.extensions.v1.RateLimitDescriptorR\vdescriptors\x12:\n" +
	"\x19per_downstream_connection\x18\x03 \x01(\bR\x17perDownstreamConnection\"\x94\x01\n" +
	"\vTokenBucket\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x01 \x01(\rR\tmaxTokens\x12&\n" +
	"\x0ftokens_per_fill\x18\x02 \x01(\rR\rtokensPerFill\x12>\n" +
	"\rfill_interval\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\ffillInterval\"\xb1\x01\n" +
	"\x13RateLimitDescriptor\x12I\n" +
	"\aentries\x18\x01 \x03(\v2/.kruise.networking.extensions.v1.RateLimitEntryR\aentries\x12O\n" +
	"\ftoken_bucket\x18\x02 \x01(\v2,.kruise.networking.extensions.v1.TokenBucketR\vtokenBucket\"J\n" +
	"\x0eRateLimitEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x10\n" +
	"\x03cel\x18\x03 \x01(\tR\x03cel*\\\n" +
	"\x13WorkloadConfigScope\x12 \n" +
	"\x1cWORKLOAD_CONFIG_SCOPE_GLOBAL\x10\x00\x12#\n" +
	"\x1fWORKLOAD_CONFIG_SCOPE_NAMESPACE\x10\x01*1\n" +
	"\x0eHeaderSendMode\x12\v\n" +
	"\aDEFAULT\x10\x00\x12\b\n" +
	"\x04SEND\x10\x01\x12\b\n" +
	"\x04SKIP\x10\x02*<\n" +
	"\x12EgressPolicyAction\x12\x0f\n" +
	"\vPASSTHROUGH\x10\x00\x12\b\n" +
	"\x04DENY\x10\x01\x12\v\n" +
	"\aGATEWAY\x10\x02B>Z<pilot/pkg/serviceregistry/kube/controller/agentio/extensionsb\x06proto3"

var (
	file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_rawDescOnce sync.Once
	file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_rawDescData []byte
)

func file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_rawDescGZIP() []byte {
	file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_rawDescOnce.Do(func() {
		file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_rawDesc), len(file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_rawDesc)))
	})
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_rawDescData
}

var file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_goTypes = []any{
	(WorkloadConfigScope)(0),           // 0: kruise.networking.extensions.v1.WorkloadConfigScope
	(HeaderSendMode)(0),                // 1: kruise.networking.extensions.v1.HeaderSendMode
	(EgressPolicyAction)(0),            // 2: kruise.networking.extensions.v1.EgressPolicyAction
	(*AgentioConfig)(nil),              // 3: kruise.networking.extensions.v1.AgentioConfig
	(*EgressGateway)(nil),              // 4: kruise.networking.extensions.v1.EgressGateway
	(*TlsTerminationConfig)(nil),       // 5: kruise.networking.extensions.v1.TlsTerminationConfig
	(*EgressPolicies)(nil),             // 6: kruise.networking.extensions.v1.EgressPolicies
	(*WorkloadConfig)(nil),             // 7: kruise.networking.extensions.v1.WorkloadConfig
	(*ExtProcProvider)(nil),            // 8: kruise.networking.extensions.v1.ExtProcProvider
	(*ClusterSettings)(nil),            // 9: kruise.networking.extensions.v1.ClusterSettings
	(*HttpSettings)(nil),               // 10: kruise.networking.extensions.v1.HttpSettings
	(*ProcessingModeOptions)(nil),      // 11: kruise.networking.extensions.v1.ProcessingModeOptions
	(*EgressPolicy)(nil),               // 12: kruise.networking.extensions.v1.EgressPolicy
	(*GatewayAddress)(nil),             // 13: kruise.networking.extensions.v1.GatewayAddress
	(*ConnectionPoolSettings)(nil),     // 14: kruise.networking.extensions.v1.ConnectionPoolSettings
	(*TcpSettings)(nil),                // 15: kruise.networking.extensions.v1.TcpSettings
	(*ConnectionPoolHttpSettings)(nil), // 16: kruise.networking.extensions.v1.ConnectionPoolHttpSettings
	(*HttpRouteOverride)(nil),          // 17: kruise.networking.extensions.v1.HttpRouteOverride
	(*HttpRouteSettings)(nil),          // 18: kruise.networking.extensions.v1.HttpRouteSettings
	(*LocalRateLimitSettings)(nil),     // 19: kruise.networking.extensions.v1.LocalRateLimitSettings
	(*TokenBucket)(nil),                // 20: kruise.networking.extensions.v1.TokenBucket
	(*RateLimitDescriptor)(nil),        // 21: kruise.networking.extensions.v1.RateLimitDescriptor
	(*RateLimitEntry)(nil),             // 22: kruise.networking.extensions.v1.RateLimitEntry
	(*duration.Duration)(nil),          // 23: google.protobuf.Duration
	(*v1alpha3.HTTPRetry)(nil),         // 24: istio.networking.v1alpha3.HTTPRetry
}
var file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_depIdxs = []int32{
	8,  // 0: kruise.networking.extensions.v1.AgentioConfig.sandbox_ext_proc:type_name -> kruise.networking.extensions.v1.ExtProcProvider
	12, // 1: kruise.networking.extensions.v1.AgentioConfig.egress_policies:type_name -> kruise.networking.extensions.v1.EgressPolicy
	4,  // 2: kruise.networking.extensions.v1.AgentioConfig.egress_gateways:type_name -> kruise.networking.extensions.v1.EgressGateway
	5,  // 3: kruise.networking.extensions.v1.EgressGateway.tls_termination:type_name -> kruise.networking.extensions.v1.TlsTerminationConfig
	8,  // 4: kruise.networking.extensions.v1.EgressGateway.ext_proc:type_name -> kruise.networking.extensions.v1.ExtProcProvider
	14, // 5: kruise.networking.extensions.v1.EgressGateway.connection_pool:type_name -> kruise.networking.extensions.v1.ConnectionPoolSettings
	19, // 6: kruise.networking.extensions.v1.EgressGateway.connect_rate_limit:type_name -> kruise.networking.extensions.v1.LocalRateLimitSettings
	12, // 7: kruise.networking.extensions.v1.EgressPolicies.egress_policies:type_name -> kruise.networking.extensions.v1.EgressPolicy
	0,  // 8: kruise.networking.extensions.v1.WorkloadConfig.scope:type_name -> kruise.networking.extensions.v1.WorkloadConfigScope
	12, // 9: kruise.networking.extensions.v1.WorkloadConfig.egress_policies:type_name -> kruise.networking.extensions.v1.EgressPolicy
	11, // 10: kruise.networking.extensions.v1.ExtProcProvider.request:type_name -> kruise.networking.extensions.v1.ProcessingModeOptions
	11, // 11: kruise.networking.extensions.v1.ExtProcProvider.response:type_name -> kruise.networking.extensions.v1.ProcessingModeOptions
	9,  // 12: kruise.networking.extensions.v1.ExtProcProvider.cluster_settings:type_name -> kruise.networking.extensions.v1.ClusterSettings
	10, // 13: kruise.networking.extensions.v1.ClusterSettings.http:type_name -> kruise.networking.extensions.v1.HttpSettings
	1,  // 14: kruise.networking.extensions.v1.ProcessingModeOptions.header_mode:type_name -> kruise.networking.extensions.v1.HeaderSendMode
	2,  // 15: kruise.networking.extensions.v1.EgressPolicy.policy:type_name -> kruise.networking.extensions.v1.EgressPolicyAction
	13, // 16: kruise.networking.extensions.v1.EgressPolicy.gateway:type_name -> kruise.networking.extensions.v1.GatewayAddress
	15, // 17: kruise.networking.extensions.v1.ConnectionPoolSettings.tcp:type_name -> kruise.networking.extensions.v1.TcpSettings
	16, // 18: kruise.networking.extensions.v1.ConnectionPoolSettings.http:type_name -> kruise.networking.extensions.v1.ConnectionPoolHttpSettings
	23, // 19: kruise.networking.extensions.v1.TcpSettings.idle_timeout:type_name -> google.protobuf.Duration
	23, // 20: kruise.networking.extensions.v1.TcpSettings.max_connection_duration:type_name -> google.protobuf.Duration
	23, // 21: kruise.networking.extensions.v1.ConnectionPoolHttpSettings.stream_idle_timeout:type_name -> google.protobuf.Duration
	18, // 22: kruise.networking.extensions.v1.ConnectionPoolHttpSettings.default_route:type_name -> kruise.networking.extensions.v1.HttpRouteSettings
	17, // 23: kruise.networking.extensions.v1.ConnectionPoolHttpSettings.route_overrides:type_name -> kruise.networking.extensions.v1.HttpRouteOverride
	18, // 24: kruise.networking.extensions.v1.HttpRouteOverride.settings:type_name -> kruise.networking.extensions.v1.HttpRouteSettings
	23, // 25: kruise.networking.extensions.v1.HttpRouteSettings.timeout:type_name -> google.protobuf.Duration
	24, // 26: kruise.networking.extensions.v1.HttpRouteSettings.retries:type_name -> istio.networking.v1alpha3.HTTPRetry
	20, // 27: kruise.networking.extensions.v1.LocalRateLimitSettings.token_bucket:type_name -> kruise.networking.extensions.v1.TokenBucket
	21, // 28: kruise.networking.extensions.v1.LocalRateLimitSettings.descriptors:type_name -> kruise.networking.extensions.v1.RateLimitDescriptor
	23, // 29: kruise.networking.extensions.v1.TokenBucket.fill_interval:type_name -> google.protobuf.Duration
	22, // 30: kruise.networking.extensions.v1.RateLimitDescriptor.entries:type_name -> kruise.networking.extensions.v1.RateLimitEntry
	20, // 31: kruise.networking.extensions.v1.RateLimitDescriptor.token_bucket:type_name -> kruise.networking.extensions.v1.TokenBucket
	32, // [32:32] is the sub-list for method output_type
	32, // [32:32] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() {
	file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_init()
}
func file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_init() {
	if File_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_rawDesc), len(file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_goTypes,
		DependencyIndexes: file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_depIdxs,
		EnumInfos:         file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_enumTypes,
		MessageInfos:      file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_msgTypes,
	}.Build()
	File_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto = out.File
	file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_goTypes = nil
	file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_agentioconfig_proto_depIdxs = nil
}
