//go:build vtprotobuf
// +build vtprotobuf

// Code generated by protoc-gen-go-vtproto. DO NOT EDIT.
// protoc-gen-go-vtproto version: v0.6.1-0.20250313105119-ba97887b0a25
// source: pilot/pkg/serviceregistry/kube/controller/agentio/extensions/agentioconfig.proto

package extensions

import (
	protohelpers "github.com/planetscale/vtprotobuf/protohelpers"
	durationpb "github.com/planetscale/vtprotobuf/types/known/durationpb"
	proto "google.golang.org/protobuf/proto"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1alpha3 "istio.io/api/networking/v1alpha3"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

func (this *AgentioConfig) EqualVT(that *AgentioConfig) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !this.SandboxExtProc.EqualVT(that.SandboxExtProc) {
		return false
	}
	if len(this.EgressPolicies) != len(that.EgressPolicies) {
		return false
	}
	for i, vx := range this.EgressPolicies {
		vy := that.EgressPolicies[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &EgressPolicy{}
			}
			if q == nil {
				q = &EgressPolicy{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	if len(this.SandboxIgnoredLabels) != len(that.SandboxIgnoredLabels) {
		return false
	}
	for i, vx := range this.SandboxIgnoredLabels {
		vy := that.SandboxIgnoredLabels[i]
		if vx != vy {
			return false
		}
	}
	if len(this.EgressGateways) != len(that.EgressGateways) {
		return false
	}
	for i, vx := range this.EgressGateways {
		vy := that.EgressGateways[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &EgressGateway{}
			}
			if q == nil {
				q = &EgressGateway{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *AgentioConfig) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*AgentioConfig)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *EgressGateway) EqualVT(that *EgressGateway) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Name != that.Name {
		return false
	}
	if this.Namespace != that.Namespace {
		return false
	}
	if !this.TlsTermination.EqualVT(that.TlsTermination) {
		return false
	}
	if !this.ExtProc.EqualVT(that.ExtProc) {
		return false
	}
	if !this.ConnectionPool.EqualVT(that.ConnectionPool) {
		return false
	}
	if !this.ConnectRateLimit.EqualVT(that.ConnectRateLimit) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *EgressGateway) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*EgressGateway)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *TlsTerminationConfig) EqualVT(that *TlsTerminationConfig) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if len(this.IncludeHosts) != len(that.IncludeHosts) {
		return false
	}
	for i, vx := range this.IncludeHosts {
		vy := that.IncludeHosts[i]
		if vx != vy {
			return false
		}
	}
	if len(this.ExcludeHosts) != len(that.ExcludeHosts) {
		return false
	}
	for i, vx := range this.ExcludeHosts {
		vy := that.ExcludeHosts[i]
		if vx != vy {
			return false
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *TlsTerminationConfig) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*TlsTerminationConfig)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *EgressPolicies) EqualVT(that *EgressPolicies) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if len(this.EgressPolicies) != len(that.EgressPolicies) {
		return false
	}
	for i, vx := range this.EgressPolicies {
		vy := that.EgressPolicies[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &EgressPolicy{}
			}
			if q == nil {
				q = &EgressPolicy{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *EgressPolicies) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*EgressPolicies)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *WorkloadConfig) EqualVT(that *WorkloadConfig) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Scope != that.Scope {
		return false
	}
	if len(this.EgressPolicies) != len(that.EgressPolicies) {
		return false
	}
	for i, vx := range this.EgressPolicies {
		vy := that.EgressPolicies[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &EgressPolicy{}
			}
			if q == nil {
				q = &EgressPolicy{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	if !this.ActorContext.EqualVT(that.ActorContext) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *WorkloadConfig) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*WorkloadConfig)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *ActorContext) EqualVT(that *ActorContext) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.ActorUid != that.ActorUid {
		return false
	}
	if this.ActorName != that.ActorName {
		return false
	}
	if this.Atespace != that.Atespace {
		return false
	}
	if this.Generation != that.Generation {
		return false
	}
	if len(this.Labels) != len(that.Labels) {
		return false
	}
	for i, vx := range this.Labels {
		vy, ok := that.Labels[i]
		if !ok {
			return false
		}
		if vx != vy {
			return false
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *ActorContext) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*ActorContext)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *ExtProcProvider) EqualVT(that *ExtProcProvider) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Service != that.Service {
		return false
	}
	if this.Port != that.Port {
		return false
	}
	if !this.Request.EqualVT(that.Request) {
		return false
	}
	if !this.Response.EqualVT(that.Response) {
		return false
	}
	if this.FailureModeAllow != that.FailureModeAllow {
		return false
	}
	if !this.ClusterSettings.EqualVT(that.ClusterSettings) {
		return false
	}
	if this.MessageTimeout != that.MessageTimeout {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *ExtProcProvider) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*ExtProcProvider)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *ClusterSettings) EqualVT(that *ClusterSettings) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !this.Http.EqualVT(that.Http) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *ClusterSettings) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*ClusterSettings)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *HttpSettings) EqualVT(that *HttpSettings) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.MaxConcurrentStreams != that.MaxConcurrentStreams {
		return false
	}
	if this.MaxRequestsPerConnection != that.MaxRequestsPerConnection {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *HttpSettings) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*HttpSettings)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *ProcessingModeOptions) EqualVT(that *ProcessingModeOptions) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.HeaderMode != that.HeaderMode {
		return false
	}
	if len(this.Attributes) != len(that.Attributes) {
		return false
	}
	for i, vx := range this.Attributes {
		vy := that.Attributes[i]
		if vx != vy {
			return false
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *ProcessingModeOptions) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*ProcessingModeOptions)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *EgressPolicy) EqualVT(that *EgressPolicy) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if len(this.Namespaces) != len(that.Namespaces) {
		return false
	}
	for i, vx := range this.Namespaces {
		vy := that.Namespaces[i]
		if vx != vy {
			return false
		}
	}
	if len(this.MatchCidrs) != len(that.MatchCidrs) {
		return false
	}
	for i, vx := range this.MatchCidrs {
		vy := that.MatchCidrs[i]
		if vx != vy {
			return false
		}
	}
	if this.Policy != that.Policy {
		return false
	}
	if !this.Gateway.EqualVT(that.Gateway) {
		return false
	}
	if len(this.MatchPorts) != len(that.MatchPorts) {
		return false
	}
	for i, vx := range this.MatchPorts {
		vy := that.MatchPorts[i]
		if vx != vy {
			return false
		}
	}
	if len(this.MatchHosts) != len(that.MatchHosts) {
		return false
	}
	for i, vx := range this.MatchHosts {
		vy := that.MatchHosts[i]
		if vx != vy {
			return false
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *EgressPolicy) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*EgressPolicy)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *GatewayAddress) EqualVT(that *GatewayAddress) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Service != that.Service {
		return false
	}
	if this.Port != that.Port {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *GatewayAddress) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*GatewayAddress)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *ConnectionPoolSettings) EqualVT(that *ConnectionPoolSettings) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !this.Tcp.EqualVT(that.Tcp) {
		return false
	}
	if !this.Http.EqualVT(that.Http) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *ConnectionPoolSettings) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*ConnectionPoolSettings)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *TcpSettings) EqualVT(that *TcpSettings) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !(*durationpb.Duration)(this.IdleTimeout).EqualVT((*durationpb.Duration)(that.IdleTimeout)) {
		return false
	}
	if !(*durationpb.Duration)(this.MaxConnectionDuration).EqualVT((*durationpb.Duration)(that.MaxConnectionDuration)) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *TcpSettings) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*TcpSettings)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *ConnectionPoolHttpSettings) EqualVT(that *ConnectionPoolHttpSettings) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !(*durationpb.Duration)(this.StreamIdleTimeout).EqualVT((*durationpb.Duration)(that.StreamIdleTimeout)) {
		return false
	}
	if !this.DefaultRoute.EqualVT(that.DefaultRoute) {
		return false
	}
	if len(this.RouteOverrides) != len(that.RouteOverrides) {
		return false
	}
	for i, vx := range this.RouteOverrides {
		vy := that.RouteOverrides[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &HttpRouteOverride{}
			}
			if q == nil {
				q = &HttpRouteOverride{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *ConnectionPoolHttpSettings) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*ConnectionPoolHttpSettings)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *HttpRouteOverride) EqualVT(that *HttpRouteOverride) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if len(this.Hosts) != len(that.Hosts) {
		return false
	}
	for i, vx := range this.Hosts {
		vy := that.Hosts[i]
		if vx != vy {
			return false
		}
	}
	if !this.Settings.EqualVT(that.Settings) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *HttpRouteOverride) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*HttpRouteOverride)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *HttpRouteSettings) EqualVT(that *HttpRouteSettings) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !(*durationpb.Duration)(this.Timeout).EqualVT((*durationpb.Duration)(that.Timeout)) {
		return false
	}
	if equal, ok := interface{}(this.Retries).(interface {
		EqualVT(*v1alpha3.HTTPRetry) bool
	}); ok {
		if !equal.EqualVT(that.Retries) {
			return false
		}
	} else if !proto.Equal(this.Retries, that.Retries) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *HttpRouteSettings) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*HttpRouteSettings)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *LocalRateLimitSettings) EqualVT(that *LocalRateLimitSettings) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !this.TokenBucket.EqualVT(that.TokenBucket) {
		return false
	}
	if len(this.Descriptors) != len(that.Descriptors) {
		return false
	}
	for i, vx := range this.Descriptors {
		vy := that.Descriptors[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &RateLimitDescriptor{}
			}
			if q == nil {
				q = &RateLimitDescriptor{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	if this.PerDownstreamConnection != that.PerDownstreamConnection {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *LocalRateLimitSettings) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*LocalRateLimitSettings)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *TokenBucket) EqualVT(that *TokenBucket) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.MaxTokens != that.MaxTokens {
		return false
	}
	if this.TokensPerFill != that.TokensPerFill {
		return false
	}
	if !(*durationpb.Duration)(this.FillInterval).EqualVT((*durationpb.Duration)(that.FillInterval)) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *TokenBucket) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*TokenBucket)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *RateLimitDescriptor) EqualVT(that *RateLimitDescriptor) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if len(this.Entries) != len(that.Entries) {
		return false
	}
	for i, vx := range this.Entries {
		vy := that.Entries[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &RateLimitEntry{}
			}
			if q == nil {
				q = &RateLimitEntry{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	if !this.TokenBucket.EqualVT(that.TokenBucket) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *RateLimitDescriptor) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*RateLimitDescriptor)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *RateLimitEntry) EqualVT(that *RateLimitEntry) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Key != that.Key {
		return false
	}
	if this.Value != that.Value {
		return false
	}
	if this.Cel != that.Cel {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *RateLimitEntry) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*RateLimitEntry)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (m *AgentioConfig) MarshalVTStrict() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVTStrict(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AgentioConfig) MarshalToVTStrict(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVTStrict(dAtA[:size])
}

func (m *AgentioConfig) MarshalToSizedBufferVTStrict(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if len(m.EgressGateways) > 0 {
		for iNdEx := len(m.EgressGateways) - 1; iNdEx >= 0; iNdEx-- {
			size, err := m.EgressGateways[iNdEx].MarshalToSizedBufferVTStrict(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.SandboxIgnoredLabels) > 0 {
		for iNdEx := len(m.SandboxIgnoredLabels) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.SandboxIgnoredLabels[iNdEx])
			copy(dAtA[i:], m.SandboxIgnoredLabels[iNdEx])
			i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.SandboxIgnoredLabels[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.EgressPolicies) > 0 {
		for iNdEx := len(m.EgressPolicies) - 1; iNdEx >= 0; iNdEx-- {
			size, err := m.EgressPolicies[iNdEx].MarshalToSizedBufferVTStrict(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x12
		}
	}
	if m.SandboxExtProc != nil {
		size, err := m.SandboxExtProc.MarshalToSizedBufferVTStrict(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EgressGateway) MarshalVTStrict() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVTStrict(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EgressGateway) MarshalToVTStrict(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVTStrict(dAtA[:size])
}

func (m *EgressGateway) MarshalToSizedBufferVTStrict(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.ConnectRateLimit != nil {
		size, err := m.ConnectRateLimit.MarshalToSizedBufferVTStrict(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x32
	}
	if m.ConnectionPool != nil {
		size, err := m.ConnectionPool.MarshalToSizedBufferVTStrict(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x2a
	}
	if m.ExtProc != nil {
		size, err := m.ExtProc.MarshalToSizedBufferVTStrict(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x22
	}
	if m.TlsTermination != nil {
		size, err := m.TlsTermination.MarshalToSizedBufferVTStrict(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Namespace) > 0 {
		i -= len(m.Namespace)
		copy(dAtA[i:], m.Namespace)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.Namespace)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TlsTerminationConfig) MarshalVTStrict() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVTStrict(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TlsTerminationConfig) MarshalToVTStrict(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVTStrict(dAtA[:size])
}

func (m *TlsTerminationConfig) MarshalToSizedBufferVTStrict(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if len(m.ExcludeHosts) > 0 {
		for iNdEx := len(m.ExcludeHosts) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ExcludeHosts[iNdEx])
			copy(dAtA[i:], m.ExcludeHosts[iNdEx])
			i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.ExcludeHosts[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.IncludeHosts) > 0 {
		for iNdEx := len(m.IncludeHosts) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.IncludeHosts[iNdEx])
			copy(dAtA[i:], m.IncludeHosts[iNdEx])
			i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.IncludeHosts[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *EgressPolicies) MarshalVTStrict() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVTStrict(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EgressPolicies) MarshalToVTStrict(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVTStrict(dAtA[:size])
}

func (m *EgressPolicies) MarshalToSizedBufferVTStrict(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if len(m.EgressPolicies) > 0 {
		for iNdEx := len(m.EgressPolicies) - 1; iNdEx >= 0; iNdEx-- {
			size, err := m.EgressPolicies[iNdEx].MarshalToSizedBufferVTStrict(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *WorkloadConfig) MarshalVTStrict() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVTStrict(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WorkloadConfig) MarshalToVTStrict(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVTStrict(dAtA[:size])
}

func (m *WorkloadConfig) MarshalToSizedBufferVTStrict(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.ActorContext != nil {
		size, err := m.ActorContext.MarshalToSizedBufferVTStrict(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.EgressPolicies) > 0 {
		for iNdEx := len(m.EgressPolicies) - 1; iNdEx >= 0; iNdEx-- {
			size, err := m.EgressPolicies[iNdEx].MarshalToSizedBufferVTStrict(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Scope != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.Scope))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ActorContext) MarshalVTStrict() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVTStrict(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ActorContext) MarshalToVTStrict(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVTStrict(dAtA[:size])
}

func (m *ActorContext) MarshalToSizedBufferVTStrict(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if len(m.Labels) > 0 {
		for k := range m.Labels {
			v := m.Labels[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = protohelpers.EncodeVarint(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = protohelpers.EncodeVarint(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = protohelpers.EncodeVarint(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.Generation != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.Generation))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Atespace) > 0 {
		i -= len(m.Atespace)
		copy(dAtA[i:], m.Atespace)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.Atespace)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ActorName) > 0 {
		i -= len(m.ActorName)
		copy(dAtA[i:], m.ActorName)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.ActorName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ActorUid) > 0 {
		i -= len(m.ActorUid)
		copy(dAtA[i:], m.ActorUid)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.ActorUid)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ExtProcProvider) MarshalVTStrict() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVTStrict(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ExtProcProvider) MarshalToVTStrict(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVTStrict(dAtA[:size])
}

func (m *ExtProcProvider) MarshalToSizedBufferVTStrict(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if len(m.MessageTimeout) > 0 {
		i -= len(m.MessageTimeout)
		copy(dAtA[i:], m.MessageTimeout)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.MessageTimeout)))
		i--
		dAtA[i] = 0x3a
	}
	if m.ClusterSettings != nil {
		size, err := m.ClusterSettings.MarshalToSizedBufferVTStrict(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x32
	}
	if m.FailureModeAllow {
		i--
		if m.FailureModeAllow {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.Response != nil {
		size, err := m.Response.MarshalToSizedBufferVTStrict(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x22
	}
	if m.Request != nil {
		size, err := m.Request.MarshalToSizedBufferVTStrict(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x1a
	}
	if m.Port != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.Port))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Service) > 0 {
		i -= len(m.Service)
		copy(dAtA[i:], m.Service)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.Service)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ClusterSettings) MarshalVTStrict() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVTStrict(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClusterSettings) MarshalToVTStrict(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVTStrict(dAtA[:size])
}

func (m *ClusterSettings) MarshalToSizedBufferVTStrict(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.Http != nil {
		size, err := m.Http.MarshalToSizedBufferVTStrict(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *HttpSettings) MarshalVTStrict() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVTStrict(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HttpSettings) MarshalToVTStrict(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVTStrict(dAtA[:size])
}

func (m *HttpSettings) MarshalToSizedBufferVTStrict(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.MaxRequestsPerConnection != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.MaxRequestsPerConnection))
		i--
		dAtA[i] = 0x10
	}
	if m.MaxConcurrentStreams != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.MaxConcurrentStreams))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ProcessingModeOptions) MarshalVTStrict() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVTStrict(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProcessingModeOptions) MarshalToVTStrict(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVTStrict(dAtA[:size])
}

func (m *ProcessingModeOptions) MarshalToSizedBufferVTStrict(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if len(m.Attributes) > 0 {
		for iNdEx := len(m.Attributes) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Attributes[iNdEx])
			copy(dAtA[i:], m.Attributes[iNdEx])
			i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.Attributes[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if m.HeaderMode != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.HeaderMode))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EgressPolicy) MarshalVTStrict() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVTStrict(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EgressPolicy) MarshalToVTStrict(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVTStrict(dAtA[:size])
}

func (m *EgressPolicy) MarshalToSizedBufferVTStrict(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if len(m.MatchHosts) > 0 {
		for iNdEx := len(m.MatchHosts) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.MatchHosts[iNdEx])
			copy(dAtA[i:], m.MatchHosts[iNdEx])
			i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.MatchHosts[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.MatchPorts) > 0 {
		for iNdEx := len(m.MatchPorts) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.MatchPorts[iNdEx])
			copy(dAtA[i:], m.MatchPorts[iNdEx])
			i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.MatchPorts[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.Gateway != nil {
		size, err := m.Gateway.MarshalToSizedBufferVTStrict(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x22
	}
	if m.Policy != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.Policy))
		i--
		dAtA[i] = 0x18
	}
	if len(m.MatchCidrs) > 0 {
		for iNdEx := len(m.MatchCidrs) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.MatchCidrs[iNdEx])
			copy(dAtA[i:], m.MatchCidrs[iNdEx])
			i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.MatchCidrs[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Namespaces) > 0 {
		for iNdEx := len(m.Namespaces) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Namespaces[iNdEx])
			copy(dAtA[i:], m.Namespaces[iNdEx])
			i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.Namespaces[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *GatewayAddress) MarshalVTStrict() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVTStrict(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GatewayAddress) MarshalToVTStrict(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVTStrict(dAtA[:size])
}

func (m *GatewayAddress) MarshalToSizedBufferVTStrict(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.Port != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.Port))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Service) > 0 {
		i -= len(m.Service)
		copy(dAtA[i:], m.Service)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.Service)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ConnectionPoolSettings) MarshalVTStrict() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVTStrict(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConnectionPoolSettings) MarshalToVTStrict(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVTStrict(dAtA[:size])
}

func (m *ConnectionPoolSettings) MarshalToSizedBufferVTStrict(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.Http != nil {
		size, err := m.Http.MarshalToSizedBufferVTStrict(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x12
	}
	if m.Tcp != nil {
		size, err := m.Tcp.MarshalToSizedBufferVTStrict(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TcpSettings) MarshalVTStrict() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVTStrict(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TcpSettings) MarshalToVTStrict(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVTStrict(dAtA[:size])
}

func (m *TcpSettings) MarshalToSizedBufferVTStrict(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.MaxConnectionDuration != nil {
		size, err := (*durationpb.Duration)(m.MaxConnectionDuration).MarshalToSizedBufferVTStrict(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x12
	}
	if m.IdleTimeout != nil {
		size, err := (*durationpb.Duration)(m.IdleTimeout).MarshalToSizedBufferVTStrict(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ConnectionPoolHttpSettings) MarshalVTStrict() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVTStrict(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConnectionPoolHttpSettings) MarshalToVTStrict(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVTStrict(dAtA[:size])
}

func (m *ConnectionPoolHttpSettings) MarshalToSizedBufferVTStrict(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if len(m.RouteOverrides) > 0 {
		for iNdEx := len(m.RouteOverrides) - 1; iNdEx >= 0; iNdEx-- {
			size, err := m.RouteOverrides[iNdEx].MarshalToSizedBufferVTStrict(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.DefaultRoute != nil {
		size, err := m.DefaultRoute.MarshalToSizedBufferVTStrict(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x12
	}
	if m.StreamIdleTimeout != nil {
		size, err := (*durationpb.Duration)(m.StreamIdleTimeout).MarshalToSizedBufferVTStrict(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *HttpRouteOverride) MarshalVTStrict() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVTStrict(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HttpRouteOverride) MarshalToVTStrict(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVTStrict(dAtA[:size])
}

func (m *HttpRouteOverride) MarshalToSizedBufferVTStrict(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.Settings != nil {
		size, err := m.Settings.MarshalToSizedBufferVTStrict(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Hosts) > 0 {
		for iNdEx := len(m.Hosts) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Hosts[iNdEx])
			copy(dAtA[i:], m.Hosts[iNdEx])
			i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.Hosts[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *HttpRouteSettings) MarshalVTStrict() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVTStrict(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HttpRouteSettings) MarshalToVTStrict(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVTStrict(dAtA[:size])
}

func (m *HttpRouteSettings) MarshalToSizedBufferVTStrict(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.Retries != nil {
		if vtmsg, ok := interface{}(m.Retries).(interface {
			MarshalToSizedBufferVTStrict([]byte) (int, error)
		}); ok {
			size, err := vtmsg.MarshalToSizedBufferVTStrict(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		} else {
			encoded, err := proto.Marshal(m.Retries)
			if err != nil {
				return 0, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = protohelpers.EncodeVarint(dAtA, i, uint64(len(encoded)))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Timeout != nil {
		size, err := (*durationpb.Duration)(m.Timeout).MarshalToSizedBufferVTStrict(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *LocalRateLimitSettings) MarshalVTStrict() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVTStrict(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LocalRateLimitSettings) MarshalToVTStrict(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVTStrict(dAtA[:size])
}

func (m *LocalRateLimitSettings) MarshalToSizedBufferVTStrict(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.PerDownstreamConnection {
		i--
		if m.PerDownstreamConnection {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.Descriptors) > 0 {
		for iNdEx := len(m.Descriptors) - 1; iNdEx >= 0; iNdEx-- {
			size, err := m.Descriptors[iNdEx].MarshalToSizedBufferVTStrict(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x12
		}
	}
	if m.TokenBucket != nil {
		size, err := m.TokenBucket.MarshalToSizedBufferVTStrict(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TokenBucket) MarshalVTStrict() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVTStrict(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TokenBucket) MarshalToVTStrict(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVTStrict(dAtA[:size])
}

func (m *TokenBucket) MarshalToSizedBufferVTStrict(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.FillInterval != nil {
		size, err := (*durationpb.Duration)(m.FillInterval).MarshalToSizedBufferVTStrict(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x1a
	}
	if m.TokensPerFill != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.TokensPerFill))
		i--
		dAtA[i] = 0x10
	}
	if m.MaxTokens != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.MaxTokens))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RateLimitDescriptor) MarshalVTStrict() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVTStrict(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RateLimitDescriptor) MarshalToVTStrict(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVTStrict(dAtA[:size])
}

func (m *RateLimitDescriptor) MarshalToSizedBufferVTStrict(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.TokenBucket != nil {
		size, err := m.TokenBucket.MarshalToSizedBufferVTStrict(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Entries) > 0 {
		for iNdEx := len(m.Entries) - 1; iNdEx >= 0; iNdEx-- {
			size, err := m.Entries[iNdEx].MarshalToSizedBufferVTStrict(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *RateLimitEntry) MarshalVTStrict() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVTStrict(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RateLimitEntry) MarshalToVTStrict(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVTStrict(dAtA[:size])
}

func (m *RateLimitEntry) MarshalToSizedBufferVTStrict(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if len(m.Cel) > 0 {
		i -= len(m.Cel)
		copy(dAtA[i:], m.Cel)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.Cel)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AgentioConfig) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SandboxExtProc != nil {
		l = m.SandboxExtProc.SizeVT()
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	if len(m.EgressPolicies) > 0 {
		for _, e := range m.EgressPolicies {
			l = e.SizeVT()
			n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
		}
	}
	if len(m.SandboxIgnoredLabels) > 0 {
		for _, s := range m.SandboxIgnoredLabels {
			l = len(s)
			n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
		}
	}
	if len(m.EgressGateways) > 0 {
		for _, e := range m.EgressGateways {
			l = e.SizeVT()
			n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
		}
	}
	n += len(m.unknownFields)
	return n
}

func (m *EgressGateway) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	l = len(m.Namespace)
	if l > 0 {
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	if m.TlsTermination != nil {
		l = m.TlsTermination.SizeVT()
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	if m.ExtProc != nil {
		l = m.ExtProc.SizeVT()
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	if m.ConnectionPool != nil {
		l = m.ConnectionPool.SizeVT()
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	if m.ConnectRateLimit != nil {
		l = m.ConnectRateLimit.SizeVT()
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	n += len(m.unknownFields)
	return n
}

func (m *TlsTerminationConfig) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.IncludeHosts) > 0 {
		for _, s := range m.IncludeHosts {
			l = len(s)
			n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
		}
	}
	if len(m.ExcludeHosts) > 0 {
		for _, s := range m.ExcludeHosts {
			l = len(s)
			n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
		}
	}
	n += len(m.unknownFields)
	return n
}

func (m *EgressPolicies) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.EgressPolicies) > 0 {
		for _, e := range m.EgressPolicies {
			l = e.SizeVT()
			n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
		}
	}
	n += len(m.unknownFields)
	return n
}

func (m *WorkloadConfig) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Scope != 0 {
		n += 1 + protohelpers.SizeOfVarint(uint64(m.Scope))
	}
	if len(m.EgressPolicies) > 0 {
		for _, e := range m.EgressPolicies {
			l = e.SizeVT()
			n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
		}
	}
	if m.ActorContext != nil {
		l = m.ActorContext.SizeVT()
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	n += len(m.unknownFields)
	return n
}

func (m *ActorContext) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ActorUid)
	if l > 0 {
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	l = len(m.ActorName)
	if l > 0 {
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	l = len(m.Atespace)
	if l > 0 {
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	if m.Generation != 0 {
		n += 1 + protohelpers.SizeOfVarint(uint64(m.Generation))
	}
	if len(m.Labels) > 0 {
		for k, v := range m.Labels {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + protohelpers.SizeOfVarint(uint64(len(k))) + 1 + len(v) + protohelpers.SizeOfVarint(uint64(len(v)))
			n += mapEntrySize + 1 + protohelpers.SizeOfVarint(uint64(mapEntrySize))
		}
	}
	n += len(m.unknownFields)
	return n
}

func (m *ExtProcProvider) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Service)
	if l > 0 {
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	if m.Port != 0 {
		n += 1 + protohelpers.SizeOfVarint(uint64(m.Port))
	}
	if m.Request != nil {
		l = m.Request.SizeVT()
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	if m.Response != nil {
		l = m.Response.SizeVT()
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	if m.FailureModeAllow {
		n += 2
	}
	if m.ClusterSettings != nil {
		l = m.ClusterSettings.SizeVT()
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	l = len(m.MessageTimeout)
	if l > 0 {
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	n += len(m.unknownFields)
	return n
}

func (m *ClusterSettings) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Http != nil {
		l = m.Http.SizeVT()
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	n += len(m.unknownFields)
	return n
}

func (m *HttpSettings) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxConcurrentStreams != 0 {
		n += 1 + protohelpers.SizeOfVarint(uint64(m.MaxConcurrentStreams))
	}
	if m.MaxRequestsPerConnection != 0 {
		n += 1 + protohelpers.SizeOfVarint(uint64(m.MaxRequestsPerConnection))
	}
	n += len(m.unknownFields)
	return n
}

func (m *ProcessingModeOptions) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.HeaderMode != 0 {
		n += 1 + protohelpers.SizeOfVarint(uint64(m.HeaderMode))
	}
	if len(m.Attributes) > 0 {
		for _, s := range m.Attributes {
			l = len(s)
			n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
		}
	}
	n += len(m.unknownFields)
	return n
}

func (m *EgressPolicy) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Namespaces) > 0 {
		for _, s := range m.Namespaces {
			l = len(s)
			n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
		}
	}
	if len(m.MatchCidrs) > 0 {
		for _, s := range m.MatchCidrs {
			l = len(s)
			n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
		}
	}
	if m.Policy != 0 {
		n += 1 + protohelpers.SizeOfVarint(uint64(m.Policy))
	}
	if m.Gateway != nil {
		l = m.Gateway.SizeVT()
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	if len(m.MatchPorts) > 0 {
		for _, s := range m.MatchPorts {
			l = len(s)
			n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
		}
	}
	if len(m.MatchHosts) > 0 {
		for _, s := range m.MatchHosts {
			l = len(s)
			n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
		}
	}
	n += len(m.unknownFields)
	return n
}

func (m *GatewayAddress) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Service)
	if l > 0 {
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	if m.Port != 0 {
		n += 1 + protohelpers.SizeOfVarint(uint64(m.Port))
	}
	n += len(m.unknownFields)
	return n
}

func (m *ConnectionPoolSettings) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Tcp != nil {
		l = m.Tcp.SizeVT()
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	if m.Http != nil {
		l = m.Http.SizeVT()
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	n += len(m.unknownFields)
	return n
}

func (m *TcpSettings) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IdleTimeout != nil {
		l = (*durationpb.Duration)(m.IdleTimeout).SizeVT()
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	if m.MaxConnectionDuration != nil {
		l = (*durationpb.Duration)(m.MaxConnectionDuration).SizeVT()
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	n += len(m.unknownFields)
	return n
}

func (m *ConnectionPoolHttpSettings) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.StreamIdleTimeout != nil {
		l = (*durationpb.Duration)(m.StreamIdleTimeout).SizeVT()
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	if m.DefaultRoute != nil {
		l = m.DefaultRoute.SizeVT()
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	if len(m.RouteOverrides) > 0 {
		for _, e := range m.RouteOverrides {
			l = e.SizeVT()
			n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
		}
	}
	n += len(m.unknownFields)
	return n
}

func (m *HttpRouteOverride) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Hosts) > 0 {
		for _, s := range m.Hosts {
			l = len(s)
			n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
		}
	}
	if m.Settings != nil {
		l = m.Settings.SizeVT()
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	n += len(m.unknownFields)
	return n
}

func (m *HttpRouteSettings) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Timeout != nil {
		l = (*durationpb.Duration)(m.Timeout).SizeVT()
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	if m.Retries != nil {
		if size, ok := interface{}(m.Retries).(interface {
			SizeVT() int
		}); ok {
			l = size.SizeVT()
		} else {
			l = proto.Size(m.Retries)
		}
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	n += len(m.unknownFields)
	return n
}

func (m *LocalRateLimitSettings) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TokenBucket != nil {
		l = m.TokenBucket.SizeVT()
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	if len(m.Descriptors) > 0 {
		for _, e := range m.Descriptors {
			l = e.SizeVT()
			n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
		}
	}
	if m.PerDownstreamConnection {
		n += 2
	}
	n += len(m.unknownFields)
	return n
}

func (m *TokenBucket) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxTokens != 0 {
		n += 1 + protohelpers.SizeOfVarint(uint64(m.MaxTokens))
	}
	if m.TokensPerFill != 0 {
		n += 1 + protohelpers.SizeOfVarint(uint64(m.TokensPerFill))
	}
	if m.FillInterval != nil {
		l = (*durationpb.Duration)(m.FillInterval).SizeVT()
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	n += len(m.unknownFields)
	return n
}

func (m *RateLimitDescriptor) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Entries) > 0 {
		for _, e := range m.Entries {
			l = e.SizeVT()
			n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
		}
	}
	if m.TokenBucket != nil {
		l = m.TokenBucket.SizeVT()
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	n += len(m.unknownFields)
	return n
}

func (m *RateLimitEntry) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	l = len(m.Cel)
	if l > 0 {
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	n += len(m.unknownFields)
	return n
}
