// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package extensions

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for TrafficPolicyExtension
func (this *TrafficPolicyExtension) MarshalJSON() ([]byte, error) {
	str, err := ExtensionsMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for TrafficPolicyExtension
func (this *TrafficPolicyExtension) UnmarshalJSON(b []byte) error {
	return ExtensionsUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Metadata
func (this *Metadata) MarshalJSON() ([]byte, error) {
	str, err := ExtensionsMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Metadata
func (this *Metadata) UnmarshalJSON(b []byte) error {
	return ExtensionsUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	ExtensionsMarshaler   = &jsonpb.Marshaler{}
	ExtensionsUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
