// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pilot/pkg/serviceregistry/kube/controller/agentio/extensions/extensions.proto

package extensions

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MeshInternalTrafficPolicy defines how mesh-internal (east-west) traffic is
// handled by agentio tunnel proxies.
type MeshInternalTrafficPolicy int32

const (
	MeshInternalTrafficPolicy_MESH_INTERNAL_PEER_AWARE  MeshInternalTrafficPolicy = 0
	MeshInternalTrafficPolicy_MESH_INTERNAL_PASSTHROUGH MeshInternalTrafficPolicy = 1
)

// Enum value maps for MeshInternalTrafficPolicy.
var (
	MeshInternalTrafficPolicy_name = map[int32]string{
		0: "MESH_INTERNAL_PEER_AWARE",
		1: "MESH_INTERNAL_PASSTHROUGH",
	}
	MeshInternalTrafficPolicy_value = map[string]int32{
		"MESH_INTERNAL_PEER_AWARE":  0,
		"MESH_INTERNAL_PASSTHROUGH": 1,
	}
)

func (x MeshInternalTrafficPolicy) Enum() *MeshInternalTrafficPolicy {
	p := new(MeshInternalTrafficPolicy)
	*p = x
	return p
}

func (x MeshInternalTrafficPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MeshInternalTrafficPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_enumTypes[0].Descriptor()
}

func (MeshInternalTrafficPolicy) Type() protoreflect.EnumType {
	return &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_enumTypes[0]
}

func (x MeshInternalTrafficPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MeshInternalTrafficPolicy.Descriptor instead.
func (MeshInternalTrafficPolicy) EnumDescriptor() ([]byte, []int) {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_rawDescGZIP(), []int{0}
}

// Traffic direction mode (server = inbound, client = outbound)
type TrafficPolicyMode int32

const (
	TrafficPolicyMode_SERVER TrafficPolicyMode = 0 // Inbound traffic (PREROUTING hook)
	TrafficPolicyMode_CLIENT TrafficPolicyMode = 1 // Outbound traffic (OUTPUT hook)
)

// Enum value maps for TrafficPolicyMode.
var (
	TrafficPolicyMode_name = map[int32]string{
		0: "SERVER",
		1: "CLIENT",
	}
	TrafficPolicyMode_value = map[string]int32{
		"SERVER": 0,
		"CLIENT": 1,
	}
)

func (x TrafficPolicyMode) Enum() *TrafficPolicyMode {
	p := new(TrafficPolicyMode)
	*p = x
	return p
}

func (x TrafficPolicyMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrafficPolicyMode) Descriptor() protoreflect.EnumDescriptor {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_enumTypes[1].Descriptor()
}

func (TrafficPolicyMode) Type() protoreflect.EnumType {
	return &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_enumTypes[1]
}

func (x TrafficPolicyMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrafficPolicyMode.Descriptor instead.
func (TrafficPolicyMode) EnumDescriptor() ([]byte, []int) {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_rawDescGZIP(), []int{1}
}

// TrafficPolicyExtension provides traffic policy priority and protocol information.
// Attached to Authorization policies via auth_extensions field.
type TrafficPolicyExtension struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Rule evaluation priority (lower value = higher priority = executed first).
	Priority int32 `protobuf:"varint,1,opt,name=priority,proto3" json:"priority,omitempty"`
	// Traffic direction mode:
	//
	//	SERVER (0) = inbound traffic
	//	CLIENT (1) = outbound traffic
	Mode          TrafficPolicyMode `protobuf:"varint,2,opt,name=mode,proto3,enum=kruise.networking.extensions.v1.TrafficPolicyMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficPolicyExtension) Reset() {
	*x = TrafficPolicyExtension{}
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficPolicyExtension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficPolicyExtension) ProtoMessage() {}

func (x *TrafficPolicyExtension) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficPolicyExtension.ProtoReflect.Descriptor instead.
func (*TrafficPolicyExtension) Descriptor() ([]byte, []int) {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_rawDescGZIP(), []int{0}
}

func (x *TrafficPolicyExtension) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *TrafficPolicyExtension) GetMode() TrafficPolicyMode {
	if x != nil {
		return x.Mode
	}
	return TrafficPolicyMode_SERVER
}

type WorkloadMetadata struct {
	state                     protoimpl.MessageState    `protogen:"open.v1"`
	Labels                    map[string]string         `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MeshInternalTrafficPolicy MeshInternalTrafficPolicy `protobuf:"varint,2,opt,name=mesh_internal_traffic_policy,json=meshInternalTrafficPolicy,proto3,enum=kruise.networking.extensions.v1.MeshInternalTrafficPolicy" json:"mesh_internal_traffic_policy,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *WorkloadMetadata) Reset() {
	*x = WorkloadMetadata{}
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadMetadata) ProtoMessage() {}

func (x *WorkloadMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadMetadata.ProtoReflect.Descriptor instead.
func (*WorkloadMetadata) Descriptor() ([]byte, []int) {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_rawDescGZIP(), []int{1}
}

func (x *WorkloadMetadata) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *WorkloadMetadata) GetMeshInternalTrafficPolicy() MeshInternalTrafficPolicy {
	if x != nil {
		return x.MeshInternalTrafficPolicy
	}
	return MeshInternalTrafficPolicy_MESH_INTERNAL_PEER_AWARE
}

var File_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto protoreflect.FileDescriptor

const file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_rawDesc = "" +
	"\n" +
	"Mpilot/pkg/serviceregistry/kube/controller/agentio/extensions/extensions.proto\x12\x1fkruise.networking.extensions.v1\"|\n" +
	"\x16TrafficPolicyExtension\x12\x1a\n" +
	"\bpriority\x18\x01 \x01(\x05R\bpriority\x12F\n" +
	"\x04mode\x18\x02 \x01(\x0e22.kruise.networking.extensions.v1.TrafficPolicyModeR\x04mode\"\xa1\x02\n" +
	"\x10WorkloadMetadata\x12U\n" +
	"\x06labels\x18\x01 \x03(\v2=.kruise.networking.extensions.v1.WorkloadMetadata.LabelsEntryR\x06labels\x12{\n" +
	"\x1cmesh_internal_traffic_policy\x18\x02 \x01(\x0e2:.kruise.networking.extensions.v1.MeshInternalTrafficPolicyR\x19meshInternalTrafficPolicy\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*X\n" +
	"\x19MeshInternalTrafficPolicy\x12\x1c\n" +
	"\x18MESH_INTERNAL_PEER_AWARE\x10\x00\x12\x1d\n" +
	"\x19MESH_INTERNAL_PASSTHROUGH\x10\x01*+\n" +
	"\x11TrafficPolicyMode\x12\n" +
	"\n" +
	"\x06SERVER\x10\x00\x12\n" +
	"\n" +
	"\x06CLIENT\x10\x01B>Z<pilot/pkg/serviceregistry/kube/controller/agentio/extensionsb\x06proto3"

var (
	file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_rawDescOnce sync.Once
	file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_rawDescData []byte
)

func file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_rawDescGZIP() []byte {
	file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_rawDescOnce.Do(func() {
		file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_rawDesc), len(file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_rawDesc)))
	})
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_rawDescData
}

var file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_goTypes = []any{
	(MeshInternalTrafficPolicy)(0), // 0: kruise.networking.extensions.v1.MeshInternalTrafficPolicy
	(TrafficPolicyMode)(0),         // 1: kruise.networking.extensions.v1.TrafficPolicyMode
	(*TrafficPolicyExtension)(nil), // 2: kruise.networking.extensions.v1.TrafficPolicyExtension
	(*WorkloadMetadata)(nil),       // 3: kruise.networking.extensions.v1.WorkloadMetadata
	nil,                            // 4: kruise.networking.extensions.v1.WorkloadMetadata.LabelsEntry
}
var file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_depIdxs = []int32{
	1, // 0: kruise.networking.extensions.v1.TrafficPolicyExtension.mode:type_name -> kruise.networking.extensions.v1.TrafficPolicyMode
	4, // 1: kruise.networking.extensions.v1.WorkloadMetadata.labels:type_name -> kruise.networking.extensions.v1.WorkloadMetadata.LabelsEntry
	0, // 2: kruise.networking.extensions.v1.WorkloadMetadata.mesh_internal_traffic_policy:type_name -> kruise.networking.extensions.v1.MeshInternalTrafficPolicy
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() {
	file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_init()
}
func file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_init() {
	if File_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_rawDesc), len(file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_goTypes,
		DependencyIndexes: file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_depIdxs,
		EnumInfos:         file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_enumTypes,
		MessageInfos:      file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_msgTypes,
	}.Build()
	File_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto = out.File
	file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_goTypes = nil
	file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_extensions_proto_depIdxs = nil
}
