// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package extensions

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for SandboxConfig
func (this *SandboxConfig) MarshalJSON() ([]byte, error) {
	str, err := SandboxconfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for SandboxConfig
func (this *SandboxConfig) UnmarshalJSON(b []byte) error {
	return SandboxconfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for EgressGateway
func (this *EgressGateway) MarshalJSON() ([]byte, error) {
	str, err := SandboxconfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for EgressGateway
func (this *EgressGateway) UnmarshalJSON(b []byte) error {
	return SandboxconfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for TlsTerminationConfig
func (this *TlsTerminationConfig) MarshalJSON() ([]byte, error) {
	str, err := SandboxconfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for TlsTerminationConfig
func (this *TlsTerminationConfig) UnmarshalJSON(b []byte) error {
	return SandboxconfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for EgressPolicies
func (this *EgressPolicies) MarshalJSON() ([]byte, error) {
	str, err := SandboxconfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for EgressPolicies
func (this *EgressPolicies) UnmarshalJSON(b []byte) error {
	return SandboxconfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for WorkloadConfig
func (this *WorkloadConfig) MarshalJSON() ([]byte, error) {
	str, err := SandboxconfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for WorkloadConfig
func (this *WorkloadConfig) UnmarshalJSON(b []byte) error {
	return SandboxconfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ExtProcProvider
func (this *ExtProcProvider) MarshalJSON() ([]byte, error) {
	str, err := SandboxconfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ExtProcProvider
func (this *ExtProcProvider) UnmarshalJSON(b []byte) error {
	return SandboxconfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ClusterSettings
func (this *ClusterSettings) MarshalJSON() ([]byte, error) {
	str, err := SandboxconfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ClusterSettings
func (this *ClusterSettings) UnmarshalJSON(b []byte) error {
	return SandboxconfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for HttpSettings
func (this *HttpSettings) MarshalJSON() ([]byte, error) {
	str, err := SandboxconfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for HttpSettings
func (this *HttpSettings) UnmarshalJSON(b []byte) error {
	return SandboxconfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ProcessingModeOptions
func (this *ProcessingModeOptions) MarshalJSON() ([]byte, error) {
	str, err := SandboxconfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ProcessingModeOptions
func (this *ProcessingModeOptions) UnmarshalJSON(b []byte) error {
	return SandboxconfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for EgressPolicy
func (this *EgressPolicy) MarshalJSON() ([]byte, error) {
	str, err := SandboxconfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for EgressPolicy
func (this *EgressPolicy) UnmarshalJSON(b []byte) error {
	return SandboxconfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for GatewayAddress
func (this *GatewayAddress) MarshalJSON() ([]byte, error) {
	str, err := SandboxconfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for GatewayAddress
func (this *GatewayAddress) UnmarshalJSON(b []byte) error {
	return SandboxconfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ConnectionPoolSettings
func (this *ConnectionPoolSettings) MarshalJSON() ([]byte, error) {
	str, err := SandboxconfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ConnectionPoolSettings
func (this *ConnectionPoolSettings) UnmarshalJSON(b []byte) error {
	return SandboxconfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for TcpSettings
func (this *TcpSettings) MarshalJSON() ([]byte, error) {
	str, err := SandboxconfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for TcpSettings
func (this *TcpSettings) UnmarshalJSON(b []byte) error {
	return SandboxconfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ConnectionPoolHttpSettings
func (this *ConnectionPoolHttpSettings) MarshalJSON() ([]byte, error) {
	str, err := SandboxconfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ConnectionPoolHttpSettings
func (this *ConnectionPoolHttpSettings) UnmarshalJSON(b []byte) error {
	return SandboxconfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for HttpRouteOverride
func (this *HttpRouteOverride) MarshalJSON() ([]byte, error) {
	str, err := SandboxconfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for HttpRouteOverride
func (this *HttpRouteOverride) UnmarshalJSON(b []byte) error {
	return SandboxconfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for HttpRouteSettings
func (this *HttpRouteSettings) MarshalJSON() ([]byte, error) {
	str, err := SandboxconfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for HttpRouteSettings
func (this *HttpRouteSettings) UnmarshalJSON(b []byte) error {
	return SandboxconfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for LocalRateLimitSettings
func (this *LocalRateLimitSettings) MarshalJSON() ([]byte, error) {
	str, err := SandboxconfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for LocalRateLimitSettings
func (this *LocalRateLimitSettings) UnmarshalJSON(b []byte) error {
	return SandboxconfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for TokenBucket
func (this *TokenBucket) MarshalJSON() ([]byte, error) {
	str, err := SandboxconfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for TokenBucket
func (this *TokenBucket) UnmarshalJSON(b []byte) error {
	return SandboxconfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for RateLimitDescriptor
func (this *RateLimitDescriptor) MarshalJSON() ([]byte, error) {
	str, err := SandboxconfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RateLimitDescriptor
func (this *RateLimitDescriptor) UnmarshalJSON(b []byte) error {
	return SandboxconfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for RateLimitEntry
func (this *RateLimitEntry) MarshalJSON() ([]byte, error) {
	str, err := SandboxconfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RateLimitEntry
func (this *RateLimitEntry) UnmarshalJSON(b []byte) error {
	return SandboxconfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	SandboxconfigMarshaler   = &jsonpb.Marshaler{}
	SandboxconfigUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
