// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package extensions

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for PolicyReference
func (this *PolicyReference) MarshalJSON() ([]byte, error) {
	str, err := SnipolicyMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for PolicyReference
func (this *PolicyReference) UnmarshalJSON(b []byte) error {
	return SnipolicyUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for SniTrafficPolicy
func (this *SniTrafficPolicy) MarshalJSON() ([]byte, error) {
	str, err := SnipolicyMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for SniTrafficPolicy
func (this *SniTrafficPolicy) UnmarshalJSON(b []byte) error {
	return SnipolicyUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for SniRule
func (this *SniRule) MarshalJSON() ([]byte, error) {
	str, err := SnipolicyMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for SniRule
func (this *SniRule) UnmarshalJSON(b []byte) error {
	return SnipolicyUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for SniMatch
func (this *SniMatch) MarshalJSON() ([]byte, error) {
	str, err := SnipolicyMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for SniMatch
func (this *SniMatch) UnmarshalJSON(b []byte) error {
	return SnipolicyUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	SnipolicyMarshaler   = &jsonpb.Marshaler{}
	SnipolicyUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
