// Copyright 2026 The Kruise Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pilot/pkg/serviceregistry/kube/controller/agentio/extensions/snipolicy.proto

package extensions

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SniAction int32

const (
	SniAction_SNI_ACTION_UNSPECIFIED     SniAction = 0
	SniAction_SNI_ACTION_TLS_TERMINATION SniAction = 1
	SniAction_SNI_ACTION_PASSTHROUGH     SniAction = 2
	SniAction_SNI_ACTION_DENY            SniAction = 3
)

// Enum value maps for SniAction.
var (
	SniAction_name = map[int32]string{
		0: "SNI_ACTION_UNSPECIFIED",
		1: "SNI_ACTION_TLS_TERMINATION",
		2: "SNI_ACTION_PASSTHROUGH",
		3: "SNI_ACTION_DENY",
	}
	SniAction_value = map[string]int32{
		"SNI_ACTION_UNSPECIFIED":     0,
		"SNI_ACTION_TLS_TERMINATION": 1,
		"SNI_ACTION_PASSTHROUGH":     2,
		"SNI_ACTION_DENY":            3,
	}
)

func (x SniAction) Enum() *SniAction {
	p := new(SniAction)
	*p = x
	return p
}

func (x SniAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SniAction) Descriptor() protoreflect.EnumDescriptor {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_enumTypes[0].Descriptor()
}

func (SniAction) Type() protoreflect.EnumType {
	return &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_enumTypes[0]
}

func (x SniAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SniAction.Descriptor instead.
func (SniAction) EnumDescriptor() ([]byte, []int) {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_rawDescGZIP(), []int{0}
}

type PolicyBinding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to TargetRef:
	//
	//	*PolicyBinding_Workload
	TargetRef isPolicyBinding_TargetRef `protobuf_oneof:"target_ref"`
	// Keyed by the full xDS TypeURL of the referenced policy resources.
	PolicyRefs    map[string]*PolicyReference `protobuf:"bytes,2,rep,name=policy_refs,json=policyRefs,proto3" json:"policy_refs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyBinding) Reset() {
	*x = PolicyBinding{}
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyBinding) ProtoMessage() {}

func (x *PolicyBinding) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyBinding.ProtoReflect.Descriptor instead.
func (*PolicyBinding) Descriptor() ([]byte, []int) {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_rawDescGZIP(), []int{0}
}

func (x *PolicyBinding) GetTargetRef() isPolicyBinding_TargetRef {
	if x != nil {
		return x.TargetRef
	}
	return nil
}

func (x *PolicyBinding) GetWorkload() *WorkloadReference {
	if x != nil {
		if x, ok := x.TargetRef.(*PolicyBinding_Workload); ok {
			return x.Workload
		}
	}
	return nil
}

func (x *PolicyBinding) GetPolicyRefs() map[string]*PolicyReference {
	if x != nil {
		return x.PolicyRefs
	}
	return nil
}

type isPolicyBinding_TargetRef interface {
	isPolicyBinding_TargetRef()
}

type PolicyBinding_Workload struct {
	Workload *WorkloadReference `protobuf:"bytes,1,opt,name=workload,proto3,oneof"`
}

func (*PolicyBinding_Workload) isPolicyBinding_TargetRef() {}

type WorkloadReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadReference) Reset() {
	*x = WorkloadReference{}
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadReference) ProtoMessage() {}

func (x *WorkloadReference) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadReference.ProtoReflect.Descriptor instead.
func (*WorkloadReference) Descriptor() ([]byte, []int) {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_rawDescGZIP(), []int{1}
}

func (x *WorkloadReference) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WorkloadReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PolicyReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ordered by descending resource priority, then ascending resource name.
	ResourceNames []string `protobuf:"bytes,1,rep,name=resource_names,json=resourceNames,proto3" json:"resource_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyReference) Reset() {
	*x = PolicyReference{}
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyReference) ProtoMessage() {}

func (x *PolicyReference) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyReference.ProtoReflect.Descriptor instead.
func (*PolicyReference) Descriptor() ([]byte, []int) {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_rawDescGZIP(), []int{2}
}

func (x *PolicyReference) GetResourceNames() []string {
	if x != nil {
		return x.ResourceNames
	}
	return nil
}

type SniTrafficPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Evaluated in the order produced by the control plane.
	Rules         []*SniRule `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SniTrafficPolicy) Reset() {
	*x = SniTrafficPolicy{}
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SniTrafficPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SniTrafficPolicy) ProtoMessage() {}

func (x *SniTrafficPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SniTrafficPolicy.ProtoReflect.Descriptor instead.
func (*SniTrafficPolicy) Descriptor() ([]byte, []int) {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_rawDescGZIP(), []int{3}
}

func (x *SniTrafficPolicy) GetRules() []*SniRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type SniRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         *SniMatch              `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
	Action        SniAction              `protobuf:"varint,2,opt,name=action,proto3,enum=kruise.networking.extensions.v1.SniAction" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SniRule) Reset() {
	*x = SniRule{}
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SniRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SniRule) ProtoMessage() {}

func (x *SniRule) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SniRule.ProtoReflect.Descriptor instead.
func (*SniRule) Descriptor() ([]byte, []int) {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_rawDescGZIP(), []int{4}
}

func (x *SniRule) GetMatch() *SniMatch {
	if x != nil {
		return x.Match
	}
	return nil
}

func (x *SniRule) GetAction() SniAction {
	if x != nil {
		return x.Action
	}
	return SniAction_SNI_ACTION_UNSPECIFIED
}

type SniMatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Values are ORed. Supported forms are exact names, a leading wildcard,
	// and "*" for any non-empty SNI.
	Sni           []string `protobuf:"bytes,1,rep,name=sni,proto3" json:"sni,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SniMatch) Reset() {
	*x = SniMatch{}
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SniMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SniMatch) ProtoMessage() {}

func (x *SniMatch) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SniMatch.ProtoReflect.Descriptor instead.
func (*SniMatch) Descriptor() ([]byte, []int) {
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_rawDescGZIP(), []int{5}
}

func (x *SniMatch) GetSni() []string {
	if x != nil {
		return x.Sni
	}
	return nil
}

var File_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto protoreflect.FileDescriptor

const file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_rawDesc = "" +
	"\n" +
	"Lpilot/pkg/serviceregistry/kube/controller/agentio/extensions/snipolicy.proto\x12\x1fkruise.networking.extensions.v1\"\xc1\x02\n" +
	"\rPolicyBinding\x12P\n" +
	"\bworkload\x18\x01 \x01(\v22.kruise.networking.extensions.v1.WorkloadReferenceH\x00R\bworkload\x12_\n" +
	"\vpolicy_refs\x18\x02 \x03(\v2>.kruise.networking.extensions.v1.PolicyBinding.PolicyRefsEntryR\n" +
	"policyRefs\x1ao\n" +
	"\x0fPolicyRefsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12F\n" +
	"\x05value\x18\x02 \x01(\v20.kruise.networking.extensions.v1.PolicyReferenceR\x05value:\x028\x01B\f\n" +
	"\n" +
	"target_ref\"E\n" +
	"\x11WorkloadReference\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"8\n" +
	"\x0fPolicyReference\x12%\n" +
	"\x0eresource_names\x18\x01 \x03(\tR\rresourceNames\"R\n" +
	"\x10SniTrafficPolicy\x12>\n" +
	"\x05rules\x18\x01 \x03(\v2(.kruise.networking.extensions.v1.SniRuleR\x05rules\"\x8e\x01\n" +
	"\aSniRule\x12?\n" +
	"\x05match\x18\x01 \x01(\v2).kruise.networking.extensions.v1.SniMatchR\x05match\x12B\n" +
	"\x06action\x18\x02 \x01(\x0e2*.kruise.networking.extensions.v1.SniActionR\x06action\"\x1c\n" +
	"\bSniMatch\x12\x10\n" +
	"\x03sni\x18\x01 \x03(\tR\x03sni*x\n" +
	"\tSniAction\x12\x1a\n" +
	"\x16SNI_ACTION_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSNI_ACTION_TLS_TERMINATION\x10\x01\x12\x1a\n" +
	"\x16SNI_ACTION_PASSTHROUGH\x10\x02\x12\x13\n" +
	"\x0fSNI_ACTION_DENY\x10\x03B>Z<pilot/pkg/serviceregistry/kube/controller/agentio/extensionsb\x06proto3"

var (
	file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_rawDescOnce sync.Once
	file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_rawDescData []byte
)

func file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_rawDescGZIP() []byte {
	file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_rawDescOnce.Do(func() {
		file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_rawDesc), len(file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_rawDesc)))
	})
	return file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_rawDescData
}

var file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_goTypes = []any{
	(SniAction)(0),            // 0: kruise.networking.extensions.v1.SniAction
	(*PolicyBinding)(nil),     // 1: kruise.networking.extensions.v1.PolicyBinding
	(*WorkloadReference)(nil), // 2: kruise.networking.extensions.v1.WorkloadReference
	(*PolicyReference)(nil),   // 3: kruise.networking.extensions.v1.PolicyReference
	(*SniTrafficPolicy)(nil),  // 4: kruise.networking.extensions.v1.SniTrafficPolicy
	(*SniRule)(nil),           // 5: kruise.networking.extensions.v1.SniRule
	(*SniMatch)(nil),          // 6: kruise.networking.extensions.v1.SniMatch
	nil,                       // 7: kruise.networking.extensions.v1.PolicyBinding.PolicyRefsEntry
}
var file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_depIdxs = []int32{
	2, // 0: kruise.networking.extensions.v1.PolicyBinding.workload:type_name -> kruise.networking.extensions.v1.WorkloadReference
	7, // 1: kruise.networking.extensions.v1.PolicyBinding.policy_refs:type_name -> kruise.networking.extensions.v1.PolicyBinding.PolicyRefsEntry
	5, // 2: kruise.networking.extensions.v1.SniTrafficPolicy.rules:type_name -> kruise.networking.extensions.v1.SniRule
	6, // 3: kruise.networking.extensions.v1.SniRule.match:type_name -> kruise.networking.extensions.v1.SniMatch
	0, // 4: kruise.networking.extensions.v1.SniRule.action:type_name -> kruise.networking.extensions.v1.SniAction
	3, // 5: kruise.networking.extensions.v1.PolicyBinding.PolicyRefsEntry.value:type_name -> kruise.networking.extensions.v1.PolicyReference
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_init() }
func file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_init() {
	if File_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto != nil {
		return
	}
	file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_msgTypes[0].OneofWrappers = []any{
		(*PolicyBinding_Workload)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_rawDesc), len(file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_goTypes,
		DependencyIndexes: file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_depIdxs,
		EnumInfos:         file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_enumTypes,
		MessageInfos:      file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_msgTypes,
	}.Build()
	File_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto = out.File
	file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_goTypes = nil
	file_pilot_pkg_serviceregistry_kube_controller_agentio_extensions_snipolicy_proto_depIdxs = nil
}
