version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    target-branch: master
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 1
    labels:
      - dependencies
    commit-message:
      prefix: deps
    groups:
      root-go-modules:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /test/e2e
    target-branch: master
    schedule:
      interval: weekly
      day: monday
      time: "03:15"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 1
    labels:
      - dependencies
    commit-message:
      prefix: deps
    groups:
      e2e-go-modules:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    target-branch: master
    schedule:
      interval: weekly
      day: monday
      time: "03:30"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 1
    labels:
      - dependencies
    commit-message:
      prefix: deps
    groups:
      github-actions:
        patterns:
          - "*"
