apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-patches
  namespace: agentio-system
  labels:
    manifests.agentio.kruise.io/type: gateway-patch
data:
  patches: |
    targetGateways:
      - demo/egress
    patches:
      - target: cluster
        operation: MERGE
        match:
          name: http_dynamic_forward_proxy
        value:
          connect_timeout: 3s
      - target: networkFilter
        operation: MERGE
        match:
          name: main_internal
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
        value:
          name: envoy.filters.network.http_connection_manager
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            stream_idle_timeout: 300s
