// Copyright 2026 The Kruise Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/extensions/v1/egresspolicy.proto

// These messages are wire types: EgressPolicies is packed with anypb into
// istio.workload.Workload.Extensions (pkg/compiler/wds.go), so its type URL
// embeds this proto package name. Moving or renaming anything reachable from
// EgressPolicies breaks every deployed data plane.

package extensionsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EgressPolicyAction defines the action for matching egress traffic.
type EgressPolicyAction int32

const (
	// Passthrough allows traffic to flow directly to the destination.
	EgressPolicyAction_PASSTHROUGH EgressPolicyAction = 0
	// Deny blocks the traffic.
	EgressPolicyAction_DENY EgressPolicyAction = 1
	// Gateway forwards traffic through the specified egress gateway.
	EgressPolicyAction_GATEWAY EgressPolicyAction = 2
)

// Enum value maps for EgressPolicyAction.
var (
	EgressPolicyAction_name = map[int32]string{
		0: "PASSTHROUGH",
		1: "DENY",
		2: "GATEWAY",
	}
	EgressPolicyAction_value = map[string]int32{
		"PASSTHROUGH": 0,
		"DENY":        1,
		"GATEWAY":     2,
	}
)

func (x EgressPolicyAction) Enum() *EgressPolicyAction {
	p := new(EgressPolicyAction)
	*p = x
	return p
}

func (x EgressPolicyAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EgressPolicyAction) Descriptor() protoreflect.EnumDescriptor {
	return file_api_extensions_v1_egresspolicy_proto_enumTypes[0].Descriptor()
}

func (EgressPolicyAction) Type() protoreflect.EnumType {
	return &file_api_extensions_v1_egresspolicy_proto_enumTypes[0]
}

func (x EgressPolicyAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EgressPolicyAction.Descriptor instead.
func (EgressPolicyAction) EnumDescriptor() ([]byte, []int) {
	return file_api_extensions_v1_egresspolicy_proto_rawDescGZIP(), []int{0}
}

// EgressPolicies is an internal wrapper for marshaling repeated EgressPolicy.
type EgressPolicies struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EgressPolicies []*EgressPolicy        `protobuf:"bytes,1,rep,name=egress_policies,json=egressPolicies,proto3" json:"egress_policies,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EgressPolicies) Reset() {
	*x = EgressPolicies{}
	mi := &file_api_extensions_v1_egresspolicy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressPolicies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressPolicies) ProtoMessage() {}

func (x *EgressPolicies) ProtoReflect() protoreflect.Message {
	mi := &file_api_extensions_v1_egresspolicy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressPolicies.ProtoReflect.Descriptor instead.
func (*EgressPolicies) Descriptor() ([]byte, []int) {
	return file_api_extensions_v1_egresspolicy_proto_rawDescGZIP(), []int{0}
}

func (x *EgressPolicies) GetEgressPolicies() []*EgressPolicy {
	if x != nil {
		return x.EgressPolicies
	}
	return nil
}

// EgressPolicy defines a rule for handling egress traffic.
// Traffic is evaluated in order; the first matching policy applies.
type EgressPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Namespaces restricts this policy to traffic originating from these namespaces.
	// If empty, the policy applies to all namespaces.
	Namespaces []string `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	// MatchCidrs specifies the destination CIDR ranges to match.
	// If empty, matches any destination.
	MatchCidrs []string `protobuf:"bytes,2,rep,name=match_cidrs,json=matchCidrs,proto3" json:"match_cidrs,omitempty"`
	// MatchPorts specifies the destination ports to match. Each entry is a
	// single port number as a decimal string (e.g. "443", "8080"). If empty,
	// matches any destination port. A traffic flow matches the policy only
	// when both match_cidrs and match_ports match (empty means wildcard on
	// that dimension).
	MatchPorts []string `protobuf:"bytes,5,rep,name=match_ports,json=matchPorts,proto3" json:"match_ports,omitempty"`
	// Policy defines the action to take for matching traffic.
	Policy EgressPolicyAction `protobuf:"varint,3,opt,name=policy,proto3,enum=kruise.networking.extensions.v1.EgressPolicyAction" json:"policy,omitempty"`
	// Gateway is the egress gateway address to forward traffic to (when policy is GATEWAY).
	Gateway *GatewayAddress `protobuf:"bytes,4,opt,name=gateway,proto3" json:"gateway,omitempty"`
	// MatchHosts specifies destination hostnames to match. The control plane
	// resolves these to IP addresses and merges the results into match_cidrs
	// before sending to the data plane. DNS results are refreshed based on TTL.
	MatchHosts    []string `protobuf:"bytes,6,rep,name=match_hosts,json=matchHosts,proto3" json:"match_hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressPolicy) Reset() {
	*x = EgressPolicy{}
	mi := &file_api_extensions_v1_egresspolicy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressPolicy) ProtoMessage() {}

func (x *EgressPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_api_extensions_v1_egresspolicy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressPolicy.ProtoReflect.Descriptor instead.
func (*EgressPolicy) Descriptor() ([]byte, []int) {
	return file_api_extensions_v1_egresspolicy_proto_rawDescGZIP(), []int{1}
}

func (x *EgressPolicy) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *EgressPolicy) GetMatchCidrs() []string {
	if x != nil {
		return x.MatchCidrs
	}
	return nil
}

func (x *EgressPolicy) GetMatchPorts() []string {
	if x != nil {
		return x.MatchPorts
	}
	return nil
}

func (x *EgressPolicy) GetPolicy() EgressPolicyAction {
	if x != nil {
		return x.Policy
	}
	return EgressPolicyAction_PASSTHROUGH
}

func (x *EgressPolicy) GetGateway() *GatewayAddress {
	if x != nil {
		return x.Gateway
	}
	return nil
}

func (x *EgressPolicy) GetMatchHosts() []string {
	if x != nil {
		return x.MatchHosts
	}
	return nil
}

// GatewayAddress represents the address of a gateway.
type GatewayAddress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service name of the gateway (e.g. egress-gateway.istio-system.svc.cluster.local).
	Service string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// Port is the port to reach the gateway at.
	Port          uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayAddress) Reset() {
	*x = GatewayAddress{}
	mi := &file_api_extensions_v1_egresspolicy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayAddress) ProtoMessage() {}

func (x *GatewayAddress) ProtoReflect() protoreflect.Message {
	mi := &file_api_extensions_v1_egresspolicy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayAddress.ProtoReflect.Descriptor instead.
func (*GatewayAddress) Descriptor() ([]byte, []int) {
	return file_api_extensions_v1_egresspolicy_proto_rawDescGZIP(), []int{2}
}

func (x *GatewayAddress) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GatewayAddress) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

var File_api_extensions_v1_egresspolicy_proto protoreflect.FileDescriptor

const file_api_extensions_v1_egresspolicy_proto_rawDesc = "" +
	"\n" +
	"$api/extensions/v1/egresspolicy.proto\x12\x1fkruise.networking.extensions.v1\"h\n" +
	"\x0eEgressPolicies\x12V\n" +
	"\x0fegress_policies\x18\x01 \x03(\v2-.kruise.networking.extensions.v1.EgressPolicyR\x0eegressPolicies\"\xa9\x02\n" +
	"\fEgressPolicy\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\tR\n" +
	"namespaces\x12\x1f\n" +
	"\vmatch_cidrs\x18\x02 \x03(\tR\n" +
	"matchCidrs\x12\x1f\n" +
	"\vmatch_ports\x18\x05 \x03(\tR\n" +
	"matchPorts\x12K\n" +
	"\x06policy\x18\x03 \x01(\x0e23.kruise.networking.extensions.v1.EgressPolicyActionR\x06policy\x12I\n" +
	"\agateway\x18\x04 \x01(\v2/.kruise.networking.extensions.v1.GatewayAddressR\agateway\x12\x1f\n" +
	"\vmatch_hosts\x18\x06 \x03(\tR\n" +
	"matchHosts\">\n" +
	"\x0eGatewayAddress\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port*<\n" +
	"\x12EgressPolicyAction\x12\x0f\n" +
	"\vPASSTHROUGH\x10\x00\x12\b\n" +
	"\x04DENY\x10\x01\x12\v\n" +
	"\aGATEWAY\x10\x02B>Z<github.com/openkruise/agentio/api/extensions/v1;extensionsv1b\x06proto3"

var (
	file_api_extensions_v1_egresspolicy_proto_rawDescOnce sync.Once
	file_api_extensions_v1_egresspolicy_proto_rawDescData []byte
)

func file_api_extensions_v1_egresspolicy_proto_rawDescGZIP() []byte {
	file_api_extensions_v1_egresspolicy_proto_rawDescOnce.Do(func() {
		file_api_extensions_v1_egresspolicy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_extensions_v1_egresspolicy_proto_rawDesc), len(file_api_extensions_v1_egresspolicy_proto_rawDesc)))
	})
	return file_api_extensions_v1_egresspolicy_proto_rawDescData
}

var file_api_extensions_v1_egresspolicy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_extensions_v1_egresspolicy_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_extensions_v1_egresspolicy_proto_goTypes = []any{
	(EgressPolicyAction)(0), // 0: kruise.networking.extensions.v1.EgressPolicyAction
	(*EgressPolicies)(nil),  // 1: kruise.networking.extensions.v1.EgressPolicies
	(*EgressPolicy)(nil),    // 2: kruise.networking.extensions.v1.EgressPolicy
	(*GatewayAddress)(nil),  // 3: kruise.networking.extensions.v1.GatewayAddress
}
var file_api_extensions_v1_egresspolicy_proto_depIdxs = []int32{
	2, // 0: kruise.networking.extensions.v1.EgressPolicies.egress_policies:type_name -> kruise.networking.extensions.v1.EgressPolicy
	0, // 1: kruise.networking.extensions.v1.EgressPolicy.policy:type_name -> kruise.networking.extensions.v1.EgressPolicyAction
	3, // 2: kruise.networking.extensions.v1.EgressPolicy.gateway:type_name -> kruise.networking.extensions.v1.GatewayAddress
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_extensions_v1_egresspolicy_proto_init() }
func file_api_extensions_v1_egresspolicy_proto_init() {
	if File_api_extensions_v1_egresspolicy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_extensions_v1_egresspolicy_proto_rawDesc), len(file_api_extensions_v1_egresspolicy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_extensions_v1_egresspolicy_proto_goTypes,
		DependencyIndexes: file_api_extensions_v1_egresspolicy_proto_depIdxs,
		EnumInfos:         file_api_extensions_v1_egresspolicy_proto_enumTypes,
		MessageInfos:      file_api_extensions_v1_egresspolicy_proto_msgTypes,
	}.Build()
	File_api_extensions_v1_egresspolicy_proto = out.File
	file_api_extensions_v1_egresspolicy_proto_goTypes = nil
	file_api_extensions_v1_egresspolicy_proto_depIdxs = nil
}
