apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ include "agentio.controller.name" . }}
  name: {{ include "agentio.controller.name" . }}
  namespace: {{ include "agentio.namespace" . }}
