// Copyright 2026 The Kruise Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func TestExportGeneratesFlatAgentioChart(t *testing.T) {
	source := t.TempDir()
	target := t.TempDir()

	writeTestFile(t, source, "values.yaml", `global:
  hub: docker.io/openkruise
agentiod:
  replicas: 1
`)
	writeTestFile(t, source, "Chart.yaml", "name: agentio\nversion: 0.1.0\nappVersion: 0.1.0\n")
	writeTestFile(t, source, "templates/_helpers.tpl", `{{/* .Values.inAComment */}}
{{- define "agentio.example" -}}
{{ .Values.global.hub }} {{ printf ".Values.inAString" }} {{ .Chart.Name }}
{{- end -}}
`)
	writeTestFile(t, source, "templates/deployment.yaml", `apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentiod
  annotations:
    example: ".Values.outsideAnAction"
spec:
  replicas: {{ .Values.agentiod.replicas }}
  {{- range .Values.agentiod.extraContainers }}
  image: {{ $.Values.global.hub }}/{{ .image }}
  {{- end }}
  config: |
{{ .Files.Get "files/config.yaml" | indent 4 }}
`)
	writeTestFile(t, source, "files/config.yaml", "feature: enabled\n")
	writeTestFile(t, source, "addons/dashboard.json", "{}\n")

	writeTestFile(t, target, "values.yaml", "replicaCount: 2\n")
	writeTestFile(t, target, "templates/manager.yaml", "kind: Deployment\n")

	if err := Export(source, target); err != nil {
		t.Fatalf("Export() error = %v", err)
	}

	wantValues := `replicaCount: 2

# BEGIN GENERATED AGENTIO VALUES - DO NOT EDIT
agentio:
  enabled: false
  global:
    hub: docker.io/openkruise
  agentiod:
    replicas: 1
# END GENERATED AGENTIO VALUES
`
	assertTestFile(t, target, "values.yaml", wantValues)
	assertTestFile(t, target, "templates/manager.yaml", "kind: Deployment\n")
	assertTestFile(t, target, "files/agentio/config.yaml", "feature: enabled\n")

	helper := readTestFile(t, target, "templates/agentio/_helpers.tpl")
	for _, want := range []string{
		"Code generated by agentio-chart-exporter. DO NOT EDIT.",
		"{{ .Values.agentio.global.hub }}",
		`{{ printf ".Values.inAString" }}`,
		"{{ .Chart.Name }}",
		"{{/* .Values.inAComment */}}",
	} {
		if !strings.Contains(helper, want) {
			t.Errorf("generated helper does not contain %q:\n%s", want, helper)
		}
	}
	if strings.Contains(helper, ".Values.agentio.inAString") || strings.Contains(helper, ".Values.agentio.inAComment") {
		t.Fatalf("generated helper rewrote a string or template comment:\n%s", helper)
	}

	resource := readTestFile(t, target, "templates/agentio/deployment.yaml")
	for _, want := range []string{
		"{{- if .Values.agentio.enabled }}",
		"replicas: {{ .Values.agentio.agentiod.replicas }}",
		"{{- range .Values.agentio.agentiod.extraContainers }}",
		"{{ $.Values.agentio.global.hub }}",
		`.Files.Get "files/agentio/config.yaml"`,
		`example: ".Values.outsideAnAction"`,
	} {
		if !strings.Contains(resource, want) {
			t.Errorf("generated resource does not contain %q:\n%s", want, resource)
		}
	}
	if !strings.HasSuffix(resource, "{{- end }}\n") {
		t.Fatalf("generated resource is not guarded through EOF:\n%s", resource)
	}

	for _, unwanted := range []string{"chartVersion", "appVersion", "sourceCommit", "addons/dashboard.json"} {
		if strings.Contains(readAllGenerated(t, target), unwanted) {
			t.Errorf("generated chart unexpectedly contains %q", unwanted)
		}
	}
}

func TestExportReplacesOnlyGeneratedValuesAndIsIdempotent(t *testing.T) {
	source := t.TempDir()
	target := t.TempDir()

	writeTestFile(t, source, "values.yaml", "global:\n  hub: first.example\n")
	writeTestFile(t, source, "templates/config.yaml", "kind: ConfigMap\n")
	writeTestFile(t, target, "values.yaml", "managerHead: true\n")

	if err := Export(source, target); err != nil {
		t.Fatalf("first Export() error = %v", err)
	}
	values := readTestFile(t, target, "values.yaml") + "managerTail: true\n"
	writeTestFile(t, target, "values.yaml", values)
	writeTestFile(t, source, "values.yaml", "global:\n  hub: second.example\n")

	if err := Export(source, target); err != nil {
		t.Fatalf("second Export() error = %v", err)
	}
	firstSnapshot := readAllGenerated(t, target)
	if err := Export(source, target); err != nil {
		t.Fatalf("idempotent Export() error = %v", err)
	}
	secondSnapshot := readAllGenerated(t, target)

	if firstSnapshot != secondSnapshot {
		t.Fatalf("repeated Export() changed generated output\nfirst:\n%s\nsecond:\n%s", firstSnapshot, secondSnapshot)
	}
	gotValues := readTestFile(t, target, "values.yaml")
	if strings.Count(gotValues, "BEGIN GENERATED AGENTIO VALUES") != 1 || strings.Count(gotValues, "END GENERATED AGENTIO VALUES") != 1 {
		t.Fatalf("generated values markers are not unique:\n%s", gotValues)
	}
	for _, want := range []string{"managerHead: true", "managerTail: true", "hub: second.example"} {
		if !strings.Contains(gotValues, want) {
			t.Errorf("values.yaml does not preserve %q:\n%s", want, gotValues)
		}
	}
	if strings.Contains(gotValues, "first.example") {
		t.Fatalf("values.yaml retained stale generated defaults:\n%s", gotValues)
	}
}

func TestExportRejectsRootEnabledWithoutChangingTarget(t *testing.T) {
	source := t.TempDir()
	target := t.TempDir()

	writeTestFile(t, source, "values.yaml", "enabled: true\nglobal: {}\n")
	writeTestFile(t, source, "templates/config.yaml", "kind: ConfigMap\n")
	writeTestFile(t, target, "values.yaml", "manager: unchanged\n")
	writeTestFile(t, target, "templates/agentio/keep.yaml", "keep\n")

	err := Export(source, target)
	if err == nil || !strings.Contains(err.Error(), "root-level enabled") {
		t.Fatalf("Export() error = %v, want root-level enabled rejection", err)
	}
	assertTestFile(t, target, "values.yaml", "manager: unchanged\n")
	assertTestFile(t, target, "templates/agentio/keep.yaml", "keep\n")
}

func TestExportKeepsLeadingNamedTemplateOutsideResourceGuard(t *testing.T) {
	source := t.TempDir()
	target := t.TempDir()

	writeTestFile(t, source, "values.yaml", "global: {}\n")
	writeTestFile(t, source, "templates/config.yaml", `{{- define "enhancedTrafficManagement.meshConfig" }}
{{- if .Values.global.enabled }}enabled{{- end }}
{{- end }}

kind: ConfigMap
data:
  config: {{ include "enhancedTrafficManagement.meshConfig" . | quote }}
`)
	writeTestFile(t, target, "values.yaml", "manager: unchanged\n")

	if err := Export(source, target); err != nil {
		t.Fatalf("Export() error = %v", err)
	}
	generated := readTestFile(t, target, "templates/agentio/config.yaml")
	define := strings.Index(generated, `define "agentio.meshConfig.defaults"`)
	guard := strings.Index(generated, "{{- if .Values.agentio.enabled }}")
	resource := strings.Index(generated, "kind: ConfigMap")
	if define < 0 || guard < 0 || resource < 0 || !(define < guard && guard < resource) {
		t.Fatalf("helper definition and resource guard are ordered incorrectly:\n%s", generated)
	}
	for _, want := range []string{
		"{{- if .Values.agentio.global.enabled }}",
		`include "agentio.meshConfig.defaults"`,
	} {
		if !strings.Contains(generated, want) {
			t.Errorf("generated template does not contain %q:\n%s", want, generated)
		}
	}
}

func TestExportRejectsNonLeadingNamedTemplateInResourceFile(t *testing.T) {
	source := t.TempDir()
	target := t.TempDir()

	writeTestFile(t, source, "values.yaml", "global: {}\n")
	writeTestFile(t, source, "templates/config.yaml", "kind: ConfigMap\n{{- define \"agentio.config\" }}x{{- end }}\n")
	writeTestFile(t, target, "values.yaml", "manager: unchanged\n")

	err := Export(source, target)
	if err == nil || !strings.Contains(err.Error(), "non-leading named template") {
		t.Fatalf("Export() error = %v, want non-leading named template rejection", err)
	}
	assertTestFile(t, target, "values.yaml", "manager: unchanged\n")
}

func TestRepositoryAgentioChartCanBeExported(t *testing.T) {
	_, testFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller() did not return the test file path")
	}
	repositoryRoot := filepath.Clean(filepath.Join(filepath.Dir(testFile), "..", ".."))
	source := filepath.Join(repositoryRoot, "manifests", "charts", "agentio")
	target := t.TempDir()
	writeTestFile(t, target, "values.yaml", "manager: unchanged\n")

	if err := Export(source, target); err != nil {
		t.Fatalf("Export(repository Agentio chart) error = %v", err)
	}
	if !strings.Contains(readTestFile(t, target, "templates/agentio/agentiod.yaml"), ".Values.agentio.agentiod") {
		t.Fatal("generated repository chart does not scope agentiod values below agentio")
	}
}

func writeTestFile(t *testing.T, root, name, content string) {
	t.Helper()
	path := filepath.Join(root, filepath.FromSlash(name))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("MkdirAll(%q): %v", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("WriteFile(%q): %v", path, err)
	}
}

func assertTestFile(t *testing.T, root, name, want string) {
	t.Helper()
	if got := readTestFile(t, root, name); got != want {
		t.Fatalf("%s mismatch\ngot:\n%s\nwant:\n%s", name, got, want)
	}
}

func readTestFile(t *testing.T, root, name string) string {
	t.Helper()
	path := filepath.Join(root, filepath.FromSlash(name))
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile(%q): %v", path, err)
	}
	return string(content)
}

func readAllGenerated(t *testing.T, target string) string {
	t.Helper()
	var out strings.Builder
	for _, root := range []string{"values.yaml", "templates/agentio", "files/agentio"} {
		path := filepath.Join(target, filepath.FromSlash(root))
		info, err := os.Stat(path)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			t.Fatalf("Stat(%q): %v", path, err)
		}
		if !info.IsDir() {
			fmt.Fprintf(&out, "-- %s --\n%s", root, readTestFile(t, target, root))
			continue
		}
		err = filepath.WalkDir(path, func(file string, entry os.DirEntry, walkErr error) error {
			if walkErr != nil {
				return walkErr
			}
			if entry.IsDir() {
				return nil
			}
			rel, err := filepath.Rel(target, file)
			if err != nil {
				return err
			}
			content, err := os.ReadFile(file)
			if err != nil {
				return err
			}
			fmt.Fprintf(&out, "-- %s --\n%s", filepath.ToSlash(rel), content)
			return nil
		})
		if err != nil {
			t.Fatalf("WalkDir(%q): %v", path, err)
		}
	}
	return out.String()
}
