{{- if and (eq .Values.egressGateway.mode "gatewayAPI") .Values.egressGateway.gatewayAPI.create }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.egressGateway.gatewayAPI.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: agentio
    app.kubernetes.io/component: egress-gateway
    {{- with .Values.egressGateway.gatewayAPI.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.egressGateway.gatewayAPI.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.egressGateway.gatewayAPI.gatewayClassName }}
  listeners:
    {{- toYaml .Values.egressGateway.gatewayAPI.listeners | nindent 4 }}
{{- end }}
