// Copyright 2026 The Kruise Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
package main

import (
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"unicode"

	yamlv3 "go.yaml.in/yaml/v3"
	"sigs.k8s.io/yaml"
)

const (
	valuesBegin                  = "# BEGIN GENERATED AGENTIO VALUES - DO NOT EDIT"
	valuesEnd                    = "# END GENERATED AGENTIO VALUES"
	controllerValuesBegin        = "# BEGIN GENERATED AGENTIO TRAFFIC PROXY VALUES - DO NOT EDIT"
	controllerValuesEnd          = "# END GENERATED AGENTIO TRAFFIC PROXY VALUES"
	trafficProxyBegin            = "  # BEGIN GENERATED AGENTIO TRAFFIC PROXY - DO NOT EDIT"
	trafficProxyEnd              = "  # END GENERATED AGENTIO TRAFFIC PROXY"
	trafficProxyTemplateFile     = "kruise-agents-traffic-proxy-injection.tpl"
	generatedInjectionConfigFile = "sandbox-injection-config.yaml"
	warning                      = "{{/* Code generated by agentio-chart-sync. DO NOT EDIT. */}}\n"
)

var (
	definePattern = regexp.MustCompile(`\{\{-?\s*define\s+`)
	filesPattern  = regexp.MustCompile(`((?:\$)?\.Files\.(?:Get|Glob)\s+)"files/`)

	helperNamePattern = regexp.MustCompile(`((?:define|include|template)\s+")(agentiod|gateway|epe)\.`)

	sandboxManagerExcludedTemplates = map[string]struct{}{
		"cni": {}, "ztunnel": {}, "NOTES.txt": {},
	}
	sandboxManagerExcludedFiles = map[string]struct{}{
		trafficProxyTemplateFile: {}, "ztunnel-injection-template.yaml": {},
	}
)

// BuildIntegrationBundle derives the reviewed OpenKruise integration sources
// from the standalone Agentio chart. Release workflows rebuild the bundle only
// after preparing the standalone chart's release image tags.
func BuildIntegrationBundle(source, target string) error {
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return fmt.Errorf("create integration bundle parent: %w", err)
	}
	staging, err := os.MkdirTemp(filepath.Dir(target), ".agentio-openkruise-bundle-")
	if err != nil {
		return fmt.Errorf("create integration bundle staging directory: %w", err)
	}
	defer cleanupPath(staging)

	manager := filepath.Join(staging, "sandbox-manager")
	controller := filepath.Join(staging, "sandbox-controller")
	for _, path := range []string{
		filepath.Join(manager, "values.yaml"),
		filepath.Join(controller, "values.yaml"),
	} {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return fmt.Errorf("create integration bundle directory: %w", err)
		}
		if err := os.WriteFile(path, nil, 0o644); err != nil {
			return fmt.Errorf("initialize integration bundle values: %w", err)
		}
	}
	if err := os.MkdirAll(filepath.Join(controller, "templates"), 0o755); err != nil {
		return fmt.Errorf("create sandbox-controller bundle templates: %w", err)
	}
	if err := buildSandboxManagerBundle(source, manager); err != nil {
		return err
	}
	if err := buildSandboxControllerBundle(source, controller); err != nil {
		return err
	}
	if err := replaceDirectory(staging, target); err != nil {
		return fmt.Errorf("replace OpenKruise integration bundle: %w", err)
	}
	return nil
}

// Export copies an already prepared sandbox-manager integration into the
// downstream chart. It deliberately performs no Helm-template rewriting or
// capability filtering; those decisions belong to the reviewed bundle.
func Export(source, target string) error {
	sourceValues, err := os.ReadFile(filepath.Join(source, "values.yaml"))
	if err != nil {
		return fmt.Errorf("read prepared sandbox-manager values: %w", err)
	}
	if err := validatePreparedBlock(sourceValues, valuesBegin, valuesEnd, "sandbox-manager values"); err != nil {
		return err
	}
	targetValuesPath := filepath.Join(target, "values.yaml")
	targetValues, err := os.ReadFile(targetValuesPath)
	if err != nil {
		return fmt.Errorf("read target values: %w", err)
	}
	nextValues, err := replaceMarkedBlock(targetValues, sourceValues, valuesBegin, valuesEnd, "target values")
	if err != nil {
		return err
	}

	staging, err := os.MkdirTemp(target, ".agentio-chart-export-")
	if err != nil {
		return fmt.Errorf("create staging directory: %w", err)
	}
	defer cleanupPath(staging)

	for _, directory := range []string{"templates", "files"} {
		sourceDirectory := filepath.Join(source, directory, "agentio")
		info, statErr := os.Stat(sourceDirectory)
		if statErr != nil {
			if os.IsNotExist(statErr) && directory == "files" {
				continue
			}
			return fmt.Errorf("validate prepared %s: %w", directory, statErr)
		}
		if !info.IsDir() {
			return fmt.Errorf("validate prepared %s: not a directory", directory)
		}
		if err := copyTree(sourceDirectory, filepath.Join(staging, directory), nil); err != nil {
			return fmt.Errorf("copy prepared %s: %w", directory, err)
		}
	}

	if err := replaceDirectory(filepath.Join(staging, "templates"), filepath.Join(target, "templates", "agentio")); err != nil {
		return fmt.Errorf("replace generated templates: %w", err)
	}
	if err := replaceDirectory(filepath.Join(staging, "files"), filepath.Join(target, "files", "agentio")); err != nil {
		return fmt.Errorf("replace generated files: %w", err)
	}
	if err := writeFileAtomically(targetValuesPath, nextValues, 0o644); err != nil {
		return fmt.Errorf("write target values: %w", err)
	}
	return nil
}

// buildSandboxManagerBundle converts a standalone Agentio chart into generated,
// optional sandbox-manager templates and values.
func buildSandboxManagerBundle(source, target string) error {
	sourceValuesPath := filepath.Join(source, "values.yaml")
	sourceValues, err := os.ReadFile(sourceValuesPath)
	if err != nil {
		return fmt.Errorf("read source values: %w", err)
	}
	if err := validateSourceValues(sourceValues); err != nil {
		return err
	}
	sandboxManagerValues, err := prepareSandboxManagerValues(sourceValues)
	if err != nil {
		return err
	}

	targetValuesPath := filepath.Join(target, "values.yaml")
	targetValues, err := os.ReadFile(targetValuesPath)
	if err != nil {
		return fmt.Errorf("read target values: %w", err)
	}
	nextValues, err := replaceValuesBlock(targetValues, sandboxManagerValues)
	if err != nil {
		return err
	}

	templatesSource := filepath.Join(source, "templates")
	filesSource := filepath.Join(source, "files")
	if info, err := os.Stat(templatesSource); err != nil || !info.IsDir() {
		if err == nil {
			err = errors.New("not a directory")
		}
		return fmt.Errorf("validate source templates: %w", err)
	}

	staging, err := os.MkdirTemp(target, ".agentio-chart-export-")
	if err != nil {
		return fmt.Errorf("create staging directory: %w", err)
	}
	defer cleanupPath(staging)

	stagedTemplates := filepath.Join(staging, "templates")
	if err := exportTemplates(templatesSource, stagedTemplates); err != nil {
		return err
	}
	stagedFiles := filepath.Join(staging, "files")
	if info, statErr := os.Stat(filesSource); statErr == nil && info.IsDir() {
		if err := copyTree(filesSource, stagedFiles, sandboxManagerExcludedFiles); err != nil {
			return fmt.Errorf("copy chart files: %w", err)
		}
	} else if statErr != nil && !os.IsNotExist(statErr) {
		return fmt.Errorf("validate source files: %w", statErr)
	}

	if err := buildManagerSupport(source, stagedTemplates, stagedFiles); err != nil {
		return err
	}

	if err := replaceDirectory(stagedTemplates, filepath.Join(target, "templates", "agentio")); err != nil {
		return fmt.Errorf("replace generated templates: %w", err)
	}
	if err := replaceDirectory(stagedFiles, filepath.Join(target, "files", "agentio")); err != nil {
		return fmt.Errorf("replace generated files: %w", err)
	}
	if err := writeFileAtomically(targetValuesPath, nextValues, 0o644); err != nil {
		return fmt.Errorf("write target values: %w", err)
	}
	return nil
}

type chartImageValues struct {
	Repository string `json:"repository"`
	Name       string `json:"name"`
	Tag        string `json:"tag"`
	Digest     string `json:"digest"`
}

type sandboxControllerSourceValues struct {
	Global struct {
		Hub             string `json:"hub"`
		Tag             string `json:"tag"`
		ClusterID       string `json:"clusterId"`
		ClusterDomain   string `json:"clusterDomain"`
		ImagePullPolicy string `json:"imagePullPolicy"`
	} `json:"global"`
	Agentiod struct {
		NameOverride     string `json:"nameOverride"`
		FullnameOverride string `json:"fullnameOverride"`
		TokenAudience    string `json:"tokenAudience"`
		CA               struct {
			TrustBundleConfigMapName string `json:"trustBundleConfigMapName"`
		} `json:"ca"`
		Injector struct {
			Ztunnel struct {
				Image               string `json:"image"`
				ImageName           string `json:"imageName"`
				EnableFirewallRules bool   `json:"enableFirewallRules"`
				FirewallBackend     string `json:"firewallBackend"`
			} `json:"ztunnel"`
			ProxyInit struct {
				Image     string `json:"image"`
				ImageName string `json:"imageName"`
			} `json:"proxyInit"`
		} `json:"injector"`
	} `json:"agentiod"`
}

// ExportSandboxController installs an already prepared traffic-proxy entry
// without replacing other sandbox runtime injection entries.
func ExportSandboxController(source, target string) error {
	sourceValues, err := os.ReadFile(filepath.Join(source, "values.yaml"))
	if err != nil {
		return fmt.Errorf("read prepared sandbox-controller values: %w", err)
	}
	if err := validatePreparedBlock(sourceValues, controllerValuesBegin, controllerValuesEnd, "sandbox-controller values"); err != nil {
		return err
	}
	targetValuesPath := filepath.Join(target, "values.yaml")
	targetValues, err := os.ReadFile(targetValuesPath)
	if err != nil {
		return fmt.Errorf("read sandbox-controller values: %w", err)
	}
	nextValues, err := replaceMarkedBlock(targetValues, sourceValues, controllerValuesBegin, controllerValuesEnd, "sandbox-controller values")
	if err != nil {
		return err
	}

	bundleTemplatePath, bundleTemplate, err := findSandboxInjectionConfigTemplate(filepath.Join(source, "templates"))
	if err != nil {
		return err
	}
	if bundleTemplate == nil {
		return errors.New("prepared sandbox-controller bundle does not contain sandbox-injection-config")
	}
	block, err := extractTrafficProxyBlock(bundleTemplate, "prepared traffic-proxy template")
	if err != nil {
		return err
	}
	targetTemplatePath, existing, err := findSandboxInjectionConfigTemplate(filepath.Join(target, "templates"))
	if err != nil {
		return err
	}
	var nextTemplate []byte
	if existing == nil {
		targetTemplatePath = filepath.Join(target, "templates", filepath.Base(bundleTemplatePath))
		nextTemplate = bundleTemplate
	} else {
		nextTemplate, err = mergeTrafficProxyBlock(existing, block)
		if err != nil {
			return fmt.Errorf("update sandbox injection ConfigMap %q: %w", targetTemplatePath, err)
		}
	}

	if err := os.MkdirAll(filepath.Dir(targetTemplatePath), 0o755); err != nil {
		return fmt.Errorf("create sandbox-controller template directory: %w", err)
	}
	if err := writeFileAtomically(targetTemplatePath, nextTemplate, 0o644); err != nil {
		return fmt.Errorf("write sandbox injection ConfigMap: %w", err)
	}
	if err := writeFileAtomically(targetValuesPath, nextValues, 0o644); err != nil {
		return fmt.Errorf("write sandbox-controller values: %w", err)
	}
	return nil
}

// buildSandboxControllerBundle prepares the traffic-proxy integration source
// from the standalone Agentio chart.
func buildSandboxControllerBundle(source, target string) error {
	sourceValues, err := os.ReadFile(filepath.Join(source, "values.yaml"))
	if err != nil {
		return fmt.Errorf("read source values for sandbox-controller: %w", err)
	}
	controllerValues, err := generatedSandboxControllerValuesBlock(sourceValues)
	if err != nil {
		return err
	}
	targetValuesPath := filepath.Join(target, "values.yaml")
	targetValues, err := os.ReadFile(targetValuesPath)
	if err != nil {
		return fmt.Errorf("read sandbox-controller values: %w", err)
	}
	nextValues, err := replaceSandboxControllerValuesBlock(targetValues, controllerValues)
	if err != nil {
		return err
	}

	templatePath := filepath.Join(source, "files", trafficProxyTemplateFile)
	template, err := os.ReadFile(templatePath)
	if err != nil {
		return fmt.Errorf("read Kruise Agents traffic-proxy template: %w", err)
	}
	block := generatedTrafficProxyBlock(template)
	targetTemplatePath, existing, err := findSandboxInjectionConfigTemplate(filepath.Join(target, "templates"))
	if err != nil {
		return err
	}
	var nextTemplate []byte
	if existing == nil {
		targetTemplatePath = filepath.Join(target, "templates", generatedInjectionConfigFile)
		nextTemplate = newSandboxInjectionConfigTemplate(block)
	} else {
		nextTemplate, err = mergeTrafficProxyBlock(existing, block)
		if err != nil {
			return fmt.Errorf("update sandbox injection ConfigMap %q: %w", targetTemplatePath, err)
		}
	}

	if err := os.MkdirAll(filepath.Dir(targetTemplatePath), 0o755); err != nil {
		return fmt.Errorf("create sandbox-controller template directory: %w", err)
	}
	if err := writeFileAtomically(targetTemplatePath, nextTemplate, 0o644); err != nil {
		return fmt.Errorf("write sandbox injection ConfigMap: %w", err)
	}
	if err := writeFileAtomically(targetValuesPath, nextValues, 0o644); err != nil {
		return fmt.Errorf("write sandbox-controller values: %w", err)
	}
	return nil
}

func generatedSandboxControllerValuesBlock(content []byte) ([]byte, error) {
	values := sandboxControllerSourceValues{}
	if err := yaml.Unmarshal(content, &values); err != nil {
		return nil, fmt.Errorf("parse source values for sandbox-controller: %w", err)
	}
	resolve := func(image, name string) (string, error) {
		if image != "" {
			return image, nil
		}
		return resolveChartImage(values.Global.Hub, values.Global.Tag, chartImageValues{Name: name})
	}
	ztunnelImage, err := resolve(values.Agentiod.Injector.Ztunnel.Image, values.Agentiod.Injector.Ztunnel.ImageName)
	if err != nil {
		return nil, fmt.Errorf("resolve ztunnel image: %w", err)
	}
	proxyInitImage, err := resolve(values.Agentiod.Injector.ProxyInit.Image, values.Agentiod.Injector.ProxyInit.ImageName)
	if err != nil {
		return nil, fmt.Errorf("resolve proxy-init image: %w", err)
	}
	service := values.Agentiod.FullnameOverride
	if service == "" {
		service = values.Agentiod.NameOverride
	}
	if service == "" {
		service = "agentiod"
	}
	service = strings.TrimRight(truncateName(service), "-")

	generated := map[string]any{
		"agentio": map[string]any{
			"trafficProxy": map[string]any{
				"controlPlaneNamespace":   "agentio-system",
				"controlPlaneService":     service,
				"xdsAddress":              "",
				"clusterDomain":           values.Global.ClusterDomain,
				"tokenAudience":           values.Agentiod.TokenAudience,
				"enableFirewallRules":     values.Agentiod.Injector.Ztunnel.EnableFirewallRules,
				"firewallBackend":         values.Agentiod.Injector.Ztunnel.FirewallBackend,
				"caAddress":               "",
				"caCertConfigMap":         values.Agentiod.CA.TrustBundleConfigMapName,
				"clusterId":               values.Global.ClusterID,
				"image":                   ztunnelImage,
				"initImage":               proxyInitImage,
				"imagePullPolicy":         values.Global.ImagePullPolicy,
				"healthProbeRewrite":      true,
				"dnsCapture":              true,
				"includeOutboundIPRanges": "*",
				"excludeOutboundIPRanges": "",
				"includeInboundPorts":     "*",
				"excludeInboundPorts":     "",
				"includeOutboundPorts":    "",
				"excludeOutboundPorts":    "",
				"resources": map[string]any{
					"requests": map[string]string{"cpu": "100m", "memory": "64Mi"},
					"limits":   map[string]string{"cpu": "200m", "memory": "128Mi"},
				},
				"initResources": map[string]any{
					"requests": map[string]string{"cpu": "100m", "memory": "128Mi"},
					"limits":   map[string]string{"cpu": "1", "memory": "1Gi"},
				},
			},
		},
	}
	encoded, err := yaml.Marshal(generated)
	if err != nil {
		return nil, fmt.Errorf("marshal sandbox-controller Agentio values: %w", err)
	}
	var out bytes.Buffer
	fmt.Fprintln(&out, controllerValuesBegin)
	out.Write(encoded)
	fmt.Fprintln(&out, controllerValuesEnd)
	return out.Bytes(), nil
}

func truncateName(name string) string {
	if len(name) > 63 {
		return name[:63]
	}
	return name
}

func resolveChartImage(globalHub, globalTag string, image chartImageValues) (string, error) {
	repository := image.Repository
	if image.Digest != "" {
		if repository == "" {
			return "", errors.New("repository is required when digest is set")
		}
		return repository + "@" + image.Digest, nil
	}
	if repository == "" {
		if globalHub == "" || image.Name == "" {
			return "", errors.New("hub and name must be non-empty")
		}
		repository = strings.TrimSuffix(globalHub, "/") + "/" + strings.TrimPrefix(image.Name, "/")
	}
	tag := image.Tag
	if tag == "" {
		tag = globalTag
	}
	if tag == "" {
		return "", errors.New("image tag must be non-empty")
	}
	return repository + ":" + tag, nil
}

func replaceSandboxControllerValuesBlock(target, block []byte) ([]byte, error) {
	return replaceMarkedBlock(target, block, controllerValuesBegin, controllerValuesEnd, "sandbox-controller values")
}

func generatedTrafficProxyBlock(template []byte) []byte {
	template = bytes.TrimSuffix(template, []byte("\n"))
	var out bytes.Buffer
	fmt.Fprintln(&out, "  traffic-proxy: |")
	for _, line := range bytes.Split(template, []byte("\n")) {
		if len(line) > 0 {
			out.WriteString("    ")
			out.Write(line)
		}
		out.WriteByte('\n')
	}
	return out.Bytes()
}

func newSandboxInjectionConfigTemplate(block []byte) []byte {
	var out bytes.Buffer
	fmt.Fprintln(&out, "apiVersion: v1")
	fmt.Fprintln(&out, "kind: ConfigMap")
	fmt.Fprintln(&out, "metadata:")
	fmt.Fprintln(&out, "  name: sandbox-injection-config")
	fmt.Fprintln(&out, "  namespace: {{ include \"sandbox-controller.namespace\" . }}")
	fmt.Fprintln(&out, "data:")
	out.Write(block)
	return out.Bytes()
}

var sandboxInjectionConfigNamePattern = regexp.MustCompile(`(?m)^[ \t]*name:[ \t]*["']?sandbox-injection-config["']?[ \t]*\r?$`)
var yamlDataLinePattern = regexp.MustCompile(`(?m)^data:[ \t]*\r?\n`)
var yamlTrafficProxyLinePattern = regexp.MustCompile(`(?m)^  traffic-proxy:[^\r\n]*(?:\r?\n|$)`)

func findSandboxInjectionConfigTemplate(templates string) (string, []byte, error) {
	var foundPath string
	var foundContent []byte
	err := filepath.WalkDir(templates, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			return nil
		}
		if entry.Type()&os.ModeSymlink != 0 {
			return fmt.Errorf("sandbox-controller template %q is a symlink", path)
		}
		ext := strings.ToLower(filepath.Ext(path))
		if ext != ".yaml" && ext != ".yml" {
			return nil
		}
		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if !sandboxInjectionConfigNamePattern.Match(content) {
			return nil
		}
		if foundPath != "" {
			return fmt.Errorf("multiple sandbox-injection-config templates found: %q and %q", foundPath, path)
		}
		foundPath = path
		foundContent = content
		return nil
	})
	if err != nil {
		return "", nil, fmt.Errorf("find sandbox injection ConfigMap template: %w", err)
	}
	return foundPath, foundContent, nil
}

func mergeTrafficProxyBlock(content, block []byte) ([]byte, error) {
	content = removeLegacyControllerWholeFileWarning(content)
	beginCount := bytes.Count(content, []byte(trafficProxyBegin))
	endCount := bytes.Count(content, []byte(trafficProxyEnd))
	if beginCount != 0 || endCount != 0 {
		if beginCount != 1 || endCount != 1 {
			return nil, errors.New("template must contain exactly one matching Agentio traffic-proxy marker pair")
		}
		begin := bytes.Index(content, []byte(trafficProxyBegin))
		end := bytes.Index(content, []byte(trafficProxyEnd))
		if begin > end {
			return nil, errors.New("Agentio traffic-proxy template markers are out of order")
		}
		end += len(trafficProxyEnd)
		if end < len(content) && content[end] == '\r' {
			end++
		}
		if end < len(content) && content[end] == '\n' {
			end++
		}
		out := make([]byte, 0, begin+len(block)+len(content)-end)
		out = append(out, content[:begin]...)
		out = append(out, block...)
		out = append(out, content[end:]...)
		return out, nil
	}

	name := sandboxInjectionConfigNamePattern.FindIndex(content)
	if name == nil {
		return nil, errors.New("sandbox-injection-config metadata.name not found")
	}
	documentStart := bytes.LastIndex(content[:name[0]], []byte("\n---"))
	if documentStart < 0 {
		documentStart = 0
	} else {
		documentStart += len("\n---")
	}
	documentEndRelative := bytes.Index(content[name[1]:], []byte("\n---"))
	documentEnd := len(content)
	if documentEndRelative >= 0 {
		documentEnd = name[1] + documentEndRelative
	}
	document := content[documentStart:documentEnd]
	data := yamlDataLinePattern.FindIndex(document)
	if data != nil {
		insert := documentStart + data[1]
		if existing := yamlTrafficProxyLinePattern.FindIndex(content[insert:documentEnd]); existing != nil {
			entryStart := insert + existing[0]
			entryEnd := yamlEntryEnd(content, insert+existing[1], documentEnd, 2)
			out := make([]byte, 0, len(content)-entryEnd+entryStart+len(block))
			out = append(out, content[:entryStart]...)
			out = append(out, block...)
			out = append(out, content[entryEnd:]...)
			return out, nil
		}
		out := make([]byte, 0, len(content)+len(block))
		out = append(out, content[:insert]...)
		out = append(out, block...)
		out = append(out, content[insert:]...)
		return out, nil
	}

	insert := documentEnd
	var addition bytes.Buffer
	if insert > 0 && content[insert-1] != '\n' {
		addition.WriteByte('\n')
	}
	fmt.Fprintln(&addition, "data:")
	addition.Write(block)
	out := make([]byte, 0, len(content)+addition.Len())
	out = append(out, content[:insert]...)
	out = append(out, addition.Bytes()...)
	out = append(out, content[insert:]...)
	return out, nil
}

func removeLegacyControllerWholeFileWarning(content []byte) []byte {
	for _, legacyWarning := range [][]byte{
		[]byte(warning),
		[]byte("{{/* Code generated by agentio-chart-exporter. DO NOT EDIT. */}}\n"),
	} {
		if bytes.HasPrefix(content, legacyWarning) {
			return content[len(legacyWarning):]
		}
	}
	return content
}

func extractTrafficProxyBlock(content []byte, description string) ([]byte, error) {
	name := sandboxInjectionConfigNamePattern.FindIndex(content)
	if name == nil {
		return nil, fmt.Errorf("%s metadata.name not found", description)
	}
	documentStart := bytes.LastIndex(content[:name[0]], []byte("\n---"))
	if documentStart < 0 {
		documentStart = 0
	} else {
		documentStart += len("\n---")
	}
	documentEndRelative := bytes.Index(content[name[1]:], []byte("\n---"))
	documentEnd := len(content)
	if documentEndRelative >= 0 {
		documentEnd = name[1] + documentEndRelative
	}
	document := content[documentStart:documentEnd]
	data := yamlDataLinePattern.FindIndex(document)
	if data == nil {
		return nil, fmt.Errorf("%s data mapping not found", description)
	}
	dataStart := documentStart + data[1]
	entry := yamlTrafficProxyLinePattern.FindIndex(content[dataStart:documentEnd])
	if entry == nil {
		return nil, fmt.Errorf("%s data.traffic-proxy entry not found", description)
	}
	entryStart := dataStart + entry[0]
	entryEnd := yamlEntryEnd(content, dataStart+entry[1], documentEnd, 2)
	return append([]byte(nil), content[entryStart:entryEnd]...), nil
}

func yamlEntryEnd(content []byte, start, limit, indentation int) int {
	for offset := start; offset < limit; {
		lineEnd := bytes.IndexByte(content[offset:limit], '\n')
		next := limit
		if lineEnd >= 0 {
			next = offset + lineEnd + 1
		}
		line := bytes.TrimSuffix(content[offset:next], []byte("\n"))
		line = bytes.TrimSuffix(line, []byte("\r"))
		if len(bytes.TrimSpace(line)) > 0 {
			leading := len(line) - len(bytes.TrimLeft(line, " \t"))
			if leading <= indentation {
				return offset
			}
		}
		offset = next
	}
	return limit
}

func validateSourceValues(content []byte) error {
	values := map[string]any{}
	if err := yaml.Unmarshal(content, &values); err != nil {
		return fmt.Errorf("parse source values: %w", err)
	}
	if _, found := values["enabled"]; found {
		return errors.New("source values contain a conflicting root-level enabled key")
	}
	return nil
}

func prepareSandboxManagerValues(content []byte) ([]byte, error) {
	document := yamlv3.Node{}
	if err := yamlv3.Unmarshal(content, &document); err != nil {
		return nil, fmt.Errorf("parse source values for sandbox-manager: %w", err)
	}
	if len(document.Content) != 1 || document.Content[0].Kind != yamlv3.MappingNode {
		return nil, errors.New("source values for sandbox-manager must be a YAML mapping")
	}
	root := document.Content[0]
	removeYAMLMappingKeys(root, "profile", "cni", "ztunnel")
	if global := yamlMappingValue(root, "global"); global != nil {
		global.Content = append(global.Content,
			&yamlv3.Node{Kind: yamlv3.ScalarNode, Value: "namespace"}, &yamlv3.Node{Kind: yamlv3.ScalarNode, Tag: "!!str", Value: "agentio-system"},
			&yamlv3.Node{Kind: yamlv3.ScalarNode, Value: "createNamespace"}, &yamlv3.Node{Kind: yamlv3.ScalarNode, Tag: "!!bool", Value: "true"})
	}
	if agentiod := yamlMappingValue(root, "agentiod"); agentiod != nil {
		removeYAMLMappingKeys(agentiod, "trustedNodeServiceAccount", "trustPackage", "clientTrustBundle")
		if injector := yamlMappingValue(agentiod, "injector"); injector != nil {
			for i := len(injector.Content) - 2; i >= 0; i -= 2 {
				if injector.Content[i].Value != "configMapName" {
					removeYAMLMappingKeys(injector, injector.Content[i].Value)
				}
			}
		}
	}

	var out bytes.Buffer
	encoder := yamlv3.NewEncoder(&out)
	encoder.SetIndent(2)
	if err := encoder.Encode(&document); err != nil {
		return nil, fmt.Errorf("encode sandbox-manager Agentio values: %w", err)
	}
	if err := encoder.Close(); err != nil {
		return nil, fmt.Errorf("finish sandbox-manager Agentio values: %w", err)
	}
	return out.Bytes(), nil
}

func yamlMappingValue(mapping *yamlv3.Node, key string) *yamlv3.Node {
	if mapping == nil || mapping.Kind != yamlv3.MappingNode {
		return nil
	}
	for i := 0; i+1 < len(mapping.Content); i += 2 {
		if mapping.Content[i].Value == key {
			return mapping.Content[i+1]
		}
	}
	return nil
}

func removeYAMLMappingKeys(mapping *yamlv3.Node, keys ...string) {
	if mapping == nil || mapping.Kind != yamlv3.MappingNode {
		return
	}
	excluded := make(map[string]struct{}, len(keys))
	for _, key := range keys {
		excluded[key] = struct{}{}
	}
	content := mapping.Content[:0]
	for i := 0; i+1 < len(mapping.Content); i += 2 {
		if _, found := excluded[mapping.Content[i].Value]; found {
			continue
		}
		content = append(content, mapping.Content[i], mapping.Content[i+1])
	}
	mapping.Content = content
}

// prepareSandboxManagerTemplate removes admission injection from the embedded
// control plane; Sandbox Pods are injected by sandbox-controller instead.
func prepareSandboxManagerTemplate(rel string, content []byte) ([]byte, error) {
	var err error
	removeBlock := func(marker string) {
		if err != nil {
			return
		}
		for {
			start := bytes.Index(content, []byte(marker))
			if start < 0 {
				return
			}
			end, blockErr := matchingDefinitionEnd(content, start)
			if blockErr != nil {
				err = fmt.Errorf("remove %s from %s: %w", marker, rel, blockErr)
				return
			}
			content = append(content[:start], content[end:]...)
		}
	}
	switch rel {
	case "agentiod/deployment.yaml":
		start := bytes.Index(content, []byte("apiVersion:"))
		if start < 0 {
			return nil, errors.New("agentiod deployment is missing apiVersion")
		}
		content = content[start:]
		removeBlock("{{- if $useTrustPackage }}")
		for _, name := range []string{"AGENTIO_TRUSTED_NODE_ACCOUNTS", "AGENTIO_INJECTION_WEBHOOK_CONFIG_NAME", "AGENTIO_NATIVE_SIDECARS"} {
			content = regexp.MustCompile(`(?m)^            - name: `+name+`\n              value: [^\n]*\n`).ReplaceAll(content, nil)
		}
		content = bytes.ReplaceAll(content, []byte("$clientTrustEnabled"), []byte("false"))
	case "agentiod/injector.yaml":
		removeBlock(`{{- if eq .Values.profile "sidecar" }}`)
		content = regexp.MustCompile(`(?m)^\{\{- \$(ztunnelImage|proxyInitImage) :=[^\n]*\n`).ReplaceAll(content, nil)
		for _, pair := range [][2]string{
			{"      ztunnel: |", "      egress-gateway: |"},
			{"    clientTrust:", "    global:"},
			{"      proxyInit:", "      sds:"},
			{"    pilot:", "{{- end }}"},
		} {
			start := bytes.Index(content, []byte(pair[0]))
			if start < 0 {
				return nil, fmt.Errorf("missing gateway config section %q", pair[0])
			}
			end := bytes.Index(content[start:], []byte(pair[1]))
			if end < 0 {
				return nil, fmt.Errorf("missing gateway config boundary %q", pair[1])
			}
			content = append(content[:start], content[start+end:]...)
		}
		content = regexp.MustCompile(`(?m)^      clusterTrustBundleName:[^\n]*\n`).ReplaceAll(content, nil)
		content = bytes.ReplaceAll(content, []byte("defaultTemplates: [ztunnel]"), []byte("defaultTemplates: [egress-gateway]"))
	case "_helpers.tpl":
		for _, prefix := range []string{"agentio-cni.", "ztunnel.", "agentiod.webhookName", "agentiod.componentImage", "agentio.sidecarEnabled"} {
			for {
				pattern := regexp.MustCompile(`\{\{- define "` + regexp.QuoteMeta(prefix) + `[^"\n]*"[^\n]*`)
				loc := pattern.FindIndex(content)
				if loc == nil {
					break
				}
				removeBlock(string(content[loc[0]:loc[1]]))
				if err != nil {
					break
				}
			}
		}
	}
	removeBlock(`{{- if eq .Values.profile "sidecar" }}`)
	content = bytes.ReplaceAll(content, []byte(`or (eq .Values.profile "sidecar") (eq .Values.egressGateway.mode "gatewayAPI")`), []byte(`eq .Values.egressGateway.mode "gatewayAPI"`))
	content = bytes.ReplaceAll(content, []byte(`(eq .Values.profile "sidecar")`), []byte("false"))
	content = bytes.ReplaceAll(content, []byte(`eq .Values.profile "sidecar"`), []byte("false"))
	content = bytes.ReplaceAll(content, []byte(`eq .Values.profile "ambient"`), []byte("false"))
	if err != nil {
		return nil, err
	}
	for _, forbidden := range []string{".Values.profile", ".Values.cni", ".Values.ztunnel", "15017", "mutatingwebhookconfigurations", "$useTrustPackage"} {
		if bytes.Contains(content, []byte(forbidden)) {
			return nil, fmt.Errorf("sandbox-manager template %q retains unsupported capability %q", rel, forbidden)
		}
	}
	return regexp.MustCompile(`(?m)[ \t]+$`).ReplaceAll(content, nil), nil
}

func validatePreparedBlock(content []byte, beginMarker, endMarker, description string) error {
	block, err := extractMarkedBlock(content, beginMarker, endMarker, description)
	if err != nil {
		return err
	}
	if !bytes.Equal(bytes.TrimSpace(content), bytes.TrimSpace(block)) {
		return fmt.Errorf("%s must contain only its generated marker block", description)
	}
	return nil
}

func extractMarkedBlock(content []byte, beginMarker, endMarker, description string) ([]byte, error) {
	beginCount := bytes.Count(content, []byte(beginMarker))
	endCount := bytes.Count(content, []byte(endMarker))
	if beginCount != 1 || endCount != 1 {
		return nil, fmt.Errorf("%s must contain exactly one matching marker pair", description)
	}
	begin := bytes.Index(content, []byte(beginMarker))
	end := bytes.Index(content, []byte(endMarker))
	if begin > end {
		return nil, fmt.Errorf("%s markers are out of order", description)
	}
	end += len(endMarker)
	if end < len(content) && content[end] == '\r' {
		end++
	}
	if end < len(content) && content[end] == '\n' {
		end++
	}
	return append([]byte(nil), content[begin:end]...), nil
}

func replaceMarkedBlock(target, block []byte, beginMarker, endMarker, description string) ([]byte, error) {
	beginCount := bytes.Count(target, []byte(beginMarker))
	endCount := bytes.Count(target, []byte(endMarker))
	if beginCount == 0 && endCount == 0 {
		var err error
		target, err = prepareValuesAppend(target, description)
		if err != nil {
			return nil, err
		}

		out := append([]byte(nil), target...)
		if len(out) > 0 && out[len(out)-1] != '\n' {
			out = append(out, '\n')
		}
		if len(out) > 0 && !bytes.HasSuffix(out, []byte("\n\n")) {
			out = append(out, '\n')
		}
		return append(out, block...), nil
	}
	if beginCount != 1 || endCount != 1 {
		return nil, fmt.Errorf("%s must contain exactly one matching marker pair", description)
	}
	begin := bytes.Index(target, []byte(beginMarker))
	end := bytes.Index(target, []byte(endMarker))
	if begin > end {
		return nil, fmt.Errorf("%s markers are out of order", description)
	}
	end += len(endMarker)
	if end < len(target) && target[end] == '\r' {
		end++
	}
	if end < len(target) && target[end] == '\n' {
		end++
	}

	out := make([]byte, 0, begin+len(block)+len(target)-end)
	out = append(out, target[:begin]...)
	out = append(out, block...)
	out = append(out, target[end:]...)
	return out, nil
}

func prepareValuesAppend(target []byte, description string) ([]byte, error) {
	var document yamlv3.Node
	if err := yamlv3.Unmarshal(target, &document); err != nil {
		return nil, fmt.Errorf("parse %s: %w", description, err)
	}
	if len(document.Content) > 0 {
		root := document.Content[0]
		if root.Kind != yamlv3.MappingNode {
			return nil, fmt.Errorf("%s must be a YAML mapping", description)
		}
		if yamlMappingValue(root, "agentio") != nil {
			return nil, fmt.Errorf("%s contains unmarked agentio values", description)
		}
		if root.Style&yamlv3.FlowStyle != 0 {
			if len(root.Content) == 0 {
				target = nil
			} else {
				root.Style &^= yamlv3.FlowStyle
				var out bytes.Buffer
				encoder := yamlv3.NewEncoder(&out)
				encoder.SetIndent(2)
				if err := encoder.Encode(&document); err != nil {
					return nil, err
				}
				if err := encoder.Close(); err != nil {
					return nil, err
				}
				target = out.Bytes()
			}
		}
	}
	return target, nil
}

func replaceValuesBlock(target, source []byte) ([]byte, error) {
	return replaceMarkedBlock(target, generatedValuesBlock(source), valuesBegin, valuesEnd, "target values")
}

func generatedValuesBlock(source []byte) []byte {
	source = bytes.TrimSuffix(source, []byte("\n"))
	var out bytes.Buffer
	fmt.Fprintln(&out, valuesBegin)
	fmt.Fprintln(&out, "agentio:")
	fmt.Fprintln(&out, "  enabled: false")
	for _, line := range bytes.Split(source, []byte("\n")) {
		if len(line) == 0 {
			out.WriteByte('\n')
			continue
		}
		out.WriteString("  ")
		out.Write(line)
		out.WriteByte('\n')
	}
	fmt.Fprintln(&out, valuesEnd)
	return out.Bytes()
}

func exportTemplates(source, target string) error {
	return filepath.WalkDir(source, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			if _, excluded := sandboxManagerExcludedTemplates[entry.Name()]; excluded {
				return filepath.SkipDir
			}
			return nil
		}
		if entry.Type()&os.ModeSymlink != 0 {
			return fmt.Errorf("source template %q is a symlink", path)
		}
		rel, err := filepath.Rel(source, path)
		if err != nil {
			return fmt.Errorf("resolve source template path %q: %w", path, err)
		}
		rel = filepath.ToSlash(rel)
		if _, excluded := sandboxManagerExcludedTemplates[rel]; excluded {
			return nil
		}

		ext := strings.ToLower(filepath.Ext(path))
		if ext != ".yaml" && ext != ".yml" && ext != ".tpl" {
			return fmt.Errorf("unsupported source template file %q", path)
		}
		content, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read source template %q: %w", path, err)
		}
		content, err = convertManagerTemplate(rel, ext, content)
		if err != nil {
			return fmt.Errorf("convert source template %q: %w", path, err)
		}

		destination := filepath.Join(target, rel)
		if err := os.MkdirAll(filepath.Dir(destination), 0o755); err != nil {
			return fmt.Errorf("create generated template directory: %w", err)
		}
		if err := os.WriteFile(destination, content, 0o644); err != nil {
			return fmt.Errorf("write generated template %q: %w", destination, err)
		}
		return nil
	})
}

func convertManagerTemplate(rel, ext string, content []byte) ([]byte, error) {
	var err error

	content, err = prepareSandboxManagerTemplate(rel, content)
	if err != nil {
		return nil, err
	}
	if ext == ".tpl" {
		content, err = rewriteTemplate(content)
		if err != nil {
			return nil, fmt.Errorf("rewrite source template %q: %w", rel, err)
		}
		content = append([]byte(warning), content...)
	} else {
		helpers, resource, err := splitLeadingDefinitions(content)
		if err != nil {
			return nil, fmt.Errorf("split source template %q: %w", rel, err)
		}
		if definePattern.Match(resource) {
			return nil, fmt.Errorf("resource template %q contains a non-leading named template definition", rel)
		}
		helpers, err = rewriteTemplate(helpers)
		if err != nil {
			return nil, fmt.Errorf("rewrite helpers in source template %q: %w", rel, err)
		}
		resource, err = rewriteTemplate(resource)
		if err != nil {
			return nil, fmt.Errorf("rewrite resources in source template %q: %w", rel, err)
		}
		var guarded bytes.Buffer
		guarded.WriteString(warning)
		guarded.Write(helpers)
		if len(helpers) > 0 && helpers[len(helpers)-1] != '\n' {
			guarded.WriteByte('\n')
		}
		guardResource := filepath.ToSlash(rel) != "crds.yaml"
		if guardResource {
			guarded.WriteString("{{- if .Values.agentio.enabled }}\n")
		}
		guarded.Write(resource)
		if len(resource) > 0 && resource[len(resource)-1] != '\n' {
			guarded.WriteByte('\n')
		}
		if guardResource {
			guarded.WriteString("{{- end }}\n")
		}
		content = guarded.Bytes()
	}
	return content, nil
}

func splitLeadingDefinitions(content []byte) ([]byte, []byte, error) {
	position := 0
	helperEnd := 0
	for {
		start := position
		for start < len(content) && unicode.IsSpace(rune(content[start])) {
			start++
		}
		if start+2 > len(content) || !bytes.HasPrefix(content[start:], []byte("{{")) {
			break
		}
		end, err := templateActionEnd(content[start:])
		if err != nil {
			return nil, nil, err
		}
		if templateCommand(content[start:start+end]) != "define" {
			break
		}
		definitionEnd, err := matchingDefinitionEnd(content, start)
		if err != nil {
			return nil, nil, err
		}
		helperEnd = definitionEnd
		position = definitionEnd
	}
	return content[:helperEnd], content[helperEnd:], nil
}

func matchingDefinitionEnd(content []byte, start int) (int, error) {
	depth := 0
	position := start
	for position < len(content) {
		next := bytes.Index(content[position:], []byte("{{"))
		if next < 0 {
			break
		}
		next += position
		trimmed := bytes.TrimLeft(content[next+2:], "- \t\r\n")
		var end int
		var err error
		if bytes.HasPrefix(trimmed, []byte("/*")) {
			end, err = templateCommentEnd(content[next:])
		} else {
			end, err = templateActionEnd(content[next:])
		}
		if err != nil {
			return 0, err
		}
		command := templateCommand(content[next : next+end])
		switch command {
		case "define", "if", "range", "with", "block":
			depth++
		case "end":
			depth--
			if depth == 0 {
				return next + end, nil
			}
			if depth < 0 {
				return 0, errors.New("named template has an unmatched end action")
			}
		}
		position = next + end
	}
	return 0, errors.New("named template definition is not closed")
}

func templateCommand(action []byte) string {
	if len(action) < 4 {
		return ""
	}
	body := strings.TrimSpace(string(action[2 : len(action)-2]))
	body = strings.TrimSpace(strings.Trim(body, "-"))
	if body == "" || strings.HasPrefix(body, "/*") {
		return ""
	}
	command, _, _ := strings.Cut(body, " ")
	return command
}

func rewriteTemplate(content []byte) ([]byte, error) {
	var out bytes.Buffer
	for len(content) > 0 {
		start := bytes.Index(content, []byte("{{"))
		if start < 0 {
			out.Write(content)
			break
		}
		out.Write(content[:start])
		content = content[start:]
		trimmed := bytes.TrimLeft(content[2:], "- \t\r\n")
		var end int
		var err error
		if bytes.HasPrefix(trimmed, []byte("/*")) {
			end, err = templateCommentEnd(content)
		} else {
			end, err = templateActionEnd(content)
		}
		if err != nil {
			return nil, err
		}
		action := content[:end]
		if bytes.HasPrefix(trimmed, []byte("/*")) {
			out.Write(action)
		} else {
			rewritten := rewriteContextReferences(action)
			rewritten = bytes.ReplaceAll(rewritten,
				[]byte(`"enhancedTrafficManagement.meshConfig"`),
				[]byte(`"agentio.meshConfig.defaults"`))
			rewritten = filesPattern.ReplaceAll(rewritten, []byte(`${1}"files/agentio/`))
			rewritten = helperNamePattern.ReplaceAll(rewritten, []byte(`${1}agentio.${2}.`))
			out.Write(rewritten)
		}
		content = content[end:]
	}
	return out.Bytes(), nil
}

func templateCommentEnd(action []byte) (int, error) {
	commentEnd := bytes.Index(action, []byte("*/"))
	if commentEnd < 0 {
		return 0, errors.New("unterminated Helm template comment")
	}
	for i := commentEnd + 2; i+1 < len(action); i++ {
		if action[i] == '}' && action[i+1] == '}' {
			return i + 2, nil
		}
		if action[i] != '-' && action[i] != ' ' && action[i] != '\t' && action[i] != '\r' && action[i] != '\n' {
			break
		}
	}
	return 0, errors.New("invalid Helm template comment terminator")
}

func templateActionEnd(action []byte) (int, error) {
	var quote byte
	escaped := false
	for i := 2; i+1 < len(action); i++ {
		ch := action[i]
		if quote != 0 {
			if quote != '`' && escaped {
				escaped = false
				continue
			}
			if quote != '`' && ch == '\\' {
				escaped = true
				continue
			}
			if ch == quote {
				quote = 0
			}
			continue
		}
		if ch == '"' || ch == '\'' || ch == '`' {
			quote = ch
			continue
		}
		if ch == '}' && action[i+1] == '}' {
			return i + 2, nil
		}
	}
	return 0, errors.New("unterminated Helm template action")
}

func rewriteContextReferences(action []byte) []byte {
	const token = ".Values"
	var out bytes.Buffer
	var quote byte
	escaped := false
	for i := 0; i < len(action); {
		ch := action[i]
		if quote != 0 {
			out.WriteByte(ch)
			i++
			if quote != '`' && escaped {
				escaped = false
				continue
			}
			if quote != '`' && ch == '\\' {
				escaped = true
				continue
			}
			if ch == quote {
				quote = 0
			}
			continue
		}
		if ch == '"' || ch == '\'' || ch == '`' {
			quote = ch
			out.WriteByte(ch)
			i++
			continue
		}
		const rootNamespace = "$.Release.Namespace"
		const namespace = ".Release.Namespace"
		if bytes.HasPrefix(action[i:], []byte(rootNamespace)) && valueTokenBoundary(action, i, len(rootNamespace)) {
			out.WriteString(`(include "agentio.namespace" $)`)
			i += len(rootNamespace)
			continue
		}
		if bytes.HasPrefix(action[i:], []byte(namespace)) && valueTokenBoundary(action, i, len(namespace)) {
			out.WriteString(`(include "agentio.namespace" .)`)
			i += len(namespace)
			continue
		}
		if strings.HasPrefix(string(action[i:]), token) && valueTokenBoundary(action, i, len(token)) {
			out.WriteString(token)
			if !hasAgentioSegment(action[i+len(token):]) {
				out.WriteString(".agentio")
			}
			i += len(token)
			continue
		}
		out.WriteByte(ch)
		i++
	}
	return out.Bytes()
}

func hasAgentioSegment(content []byte) bool {
	const segment = ".agentio"
	if !bytes.HasPrefix(content, []byte(segment)) {
		return false
	}
	if len(content) == len(segment) {
		return true
	}
	next := rune(content[len(segment)])
	return !unicode.IsLetter(next) && !unicode.IsDigit(next) && next != '_'
}

func valueTokenBoundary(content []byte, start, length int) bool {
	if start > 0 {
		previous := rune(content[start-1])
		if unicode.IsLetter(previous) || unicode.IsDigit(previous) || previous == '_' {
			return false
		}
	}
	end := start + length
	if end < len(content) {
		next := rune(content[end])
		if unicode.IsLetter(next) || unicode.IsDigit(next) || next == '_' {
			return false
		}
	}
	return true
}

func copyTree(source, target string, excluded map[string]struct{}) error {
	return filepath.WalkDir(source, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.Type()&os.ModeSymlink != 0 {
			return fmt.Errorf("source file %q is a symlink", path)
		}
		rel, err := filepath.Rel(source, path)
		if err != nil {
			return err
		}
		if _, found := excluded[filepath.ToSlash(rel)]; found {
			return nil
		}
		destination := filepath.Join(target, rel)
		if entry.IsDir() {
			return os.MkdirAll(destination, 0o755)
		}
		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if err := os.MkdirAll(filepath.Dir(destination), 0o755); err != nil {
			return err
		}
		return os.WriteFile(destination, content, 0o644)
	})
}

func replaceDirectory(source, target string) error {
	if err := os.RemoveAll(target); err != nil {
		return err
	}
	if _, err := os.Stat(source); os.IsNotExist(err) {
		return nil
	} else if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return err
	}
	return os.Rename(source, target)
}

func writeFileAtomically(path string, content []byte, mode fs.FileMode) error {
	temporary, err := os.CreateTemp(filepath.Dir(path), ".agentio-values-")
	if err != nil {
		return err
	}
	temporaryName := temporary.Name()
	defer cleanupPath(temporaryName)
	if err := temporary.Chmod(mode); err != nil {
		return errors.Join(err, temporary.Close())
	}
	if _, err := temporary.Write(content); err != nil {
		return errors.Join(err, temporary.Close())
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	return os.Rename(temporaryName, path)
}

func cleanupPath(path string) {
	if err := os.RemoveAll(path); err != nil {
		fmt.Fprintf(os.Stderr, "clean up temporary path %s: %v\n", path, err)
	}
}
