// Copyright 2026 The Kruise Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
package main

import (
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"unicode"

	yamlv3 "gopkg.in/yaml.v3"
	"sigs.k8s.io/yaml"
)

const (
	valuesBegin                  = "# BEGIN GENERATED AGENTIO VALUES - DO NOT EDIT"
	valuesEnd                    = "# END GENERATED AGENTIO VALUES"
	controllerValuesBegin        = "# BEGIN GENERATED AGENTIO TRAFFIC PROXY VALUES - DO NOT EDIT"
	controllerValuesEnd          = "# END GENERATED AGENTIO TRAFFIC PROXY VALUES"
	trafficProxyBegin            = "  # BEGIN GENERATED AGENTIO TRAFFIC PROXY - DO NOT EDIT"
	trafficProxyEnd              = "  # END GENERATED AGENTIO TRAFFIC PROXY"
	trafficProxyTemplateFile     = "kruise-agents-traffic-proxy-injection.tpl"
	generatedInjectionConfigFile = "sandbox-injection-config.yaml"
	warning                      = "{{/* Code generated by agentio-chart-sync. DO NOT EDIT. */}}\n"
)

var (
	definePattern = regexp.MustCompile(`\{\{-?\s*define\s+`)
	filesPattern  = regexp.MustCompile(`((?:\$)?\.Files\.(?:Get|Glob)\s+)"files/`)

	sandboxManagerExcludedTemplates = map[string]struct{}{
		"cni-configmap.yaml":          {},
		"cni-daemonset.yaml":          {},
		"cni-rbac.yaml":               {},
		"cni-serviceaccount.yaml":     {},
		"injection-templates.yaml":    {},
		"webhook.yaml":                {},
		"ztunnel-daemonset.yaml":      {},
		"ztunnel-serviceaccount.yaml": {},
	}
	sandboxManagerExcludedFiles = map[string]struct{}{
		trafficProxyTemplateFile:           {},
		"waypoint-injection-template.yaml": {},
		"ztunnel-injection-template.yaml":  {},
	}
)

// BuildIntegrationBundle derives the reviewed OpenKruise integration sources
// from the standalone Agentio chart. Release workflows rebuild the bundle only
// after preparing the standalone chart's release image tags.
func BuildIntegrationBundle(source, target string) error {
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return fmt.Errorf("create integration bundle parent: %w", err)
	}
	staging, err := os.MkdirTemp(filepath.Dir(target), ".agentio-openkruise-bundle-")
	if err != nil {
		return fmt.Errorf("create integration bundle staging directory: %w", err)
	}
	defer os.RemoveAll(staging)

	manager := filepath.Join(staging, "sandbox-manager")
	controller := filepath.Join(staging, "sandbox-controller")
	for _, path := range []string{
		filepath.Join(manager, "values.yaml"),
		filepath.Join(controller, "values.yaml"),
	} {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return fmt.Errorf("create integration bundle directory: %w", err)
		}
		if err := os.WriteFile(path, nil, 0o644); err != nil {
			return fmt.Errorf("initialize integration bundle values: %w", err)
		}
	}
	if err := os.MkdirAll(filepath.Join(controller, "templates"), 0o755); err != nil {
		return fmt.Errorf("create sandbox-controller bundle templates: %w", err)
	}
	if err := buildSandboxManagerBundle(source, manager); err != nil {
		return err
	}
	if err := buildSandboxControllerBundle(source, controller); err != nil {
		return err
	}
	if err := replaceDirectory(staging, target); err != nil {
		return fmt.Errorf("replace OpenKruise integration bundle: %w", err)
	}
	return nil
}

// Export copies an already prepared sandbox-manager integration into the
// downstream chart. It deliberately performs no Helm-template rewriting or
// capability filtering; those decisions belong to the reviewed bundle.
func Export(source, target string) error {
	sourceValues, err := os.ReadFile(filepath.Join(source, "values.yaml"))
	if err != nil {
		return fmt.Errorf("read prepared sandbox-manager values: %w", err)
	}
	if err := validatePreparedBlock(sourceValues, valuesBegin, valuesEnd, "sandbox-manager values"); err != nil {
		return err
	}
	targetValuesPath := filepath.Join(target, "values.yaml")
	targetValues, err := os.ReadFile(targetValuesPath)
	if err != nil {
		return fmt.Errorf("read target values: %w", err)
	}
	nextValues, err := replaceMarkedBlock(targetValues, sourceValues, valuesBegin, valuesEnd, "target values")
	if err != nil {
		return err
	}

	staging, err := os.MkdirTemp(target, ".agentio-chart-export-")
	if err != nil {
		return fmt.Errorf("create staging directory: %w", err)
	}
	defer os.RemoveAll(staging)

	for _, directory := range []string{"templates", "files"} {
		sourceDirectory := filepath.Join(source, directory, "agentio")
		info, statErr := os.Stat(sourceDirectory)
		if statErr != nil {
			if os.IsNotExist(statErr) && directory == "files" {
				continue
			}
			return fmt.Errorf("validate prepared %s: %w", directory, statErr)
		}
		if !info.IsDir() {
			return fmt.Errorf("validate prepared %s: not a directory", directory)
		}
		if err := copyTree(sourceDirectory, filepath.Join(staging, directory), nil); err != nil {
			return fmt.Errorf("copy prepared %s: %w", directory, err)
		}
	}

	if err := replaceDirectory(filepath.Join(staging, "templates"), filepath.Join(target, "templates", "agentio")); err != nil {
		return fmt.Errorf("replace generated templates: %w", err)
	}
	if err := replaceDirectory(filepath.Join(staging, "files"), filepath.Join(target, "files", "agentio")); err != nil {
		return fmt.Errorf("replace generated files: %w", err)
	}
	if err := writeFileAtomically(targetValuesPath, nextValues, 0o644); err != nil {
		return fmt.Errorf("write target values: %w", err)
	}
	return nil
}

// buildSandboxManagerBundle converts a standalone Agentio chart into generated,
// optional sandbox-manager templates and values.
func buildSandboxManagerBundle(source, target string) error {
	sourceValuesPath := filepath.Join(source, "values.yaml")
	sourceValues, err := os.ReadFile(sourceValuesPath)
	if err != nil {
		return fmt.Errorf("read source values: %w", err)
	}
	if err := validateSourceValues(sourceValues); err != nil {
		return err
	}
	sandboxManagerValues, err := prepareSandboxManagerValues(sourceValues)
	if err != nil {
		return err
	}

	targetValuesPath := filepath.Join(target, "values.yaml")
	targetValues, err := os.ReadFile(targetValuesPath)
	if err != nil {
		return fmt.Errorf("read target values: %w", err)
	}
	nextValues, err := replaceValuesBlock(targetValues, sandboxManagerValues)
	if err != nil {
		return err
	}

	templatesSource := filepath.Join(source, "templates")
	filesSource := filepath.Join(source, "files")
	if info, err := os.Stat(templatesSource); err != nil || !info.IsDir() {
		if err == nil {
			err = errors.New("not a directory")
		}
		return fmt.Errorf("validate source templates: %w", err)
	}

	staging, err := os.MkdirTemp(target, ".agentio-chart-export-")
	if err != nil {
		return fmt.Errorf("create staging directory: %w", err)
	}
	defer os.RemoveAll(staging)

	stagedTemplates := filepath.Join(staging, "templates")
	if err := exportTemplates(templatesSource, stagedTemplates); err != nil {
		return err
	}
	stagedFiles := filepath.Join(staging, "files")
	if info, statErr := os.Stat(filesSource); statErr == nil && info.IsDir() {
		if err := copyTree(filesSource, stagedFiles, sandboxManagerExcludedFiles); err != nil {
			return fmt.Errorf("copy chart files: %w", err)
		}
	} else if statErr != nil && !os.IsNotExist(statErr) {
		return fmt.Errorf("validate source files: %w", statErr)
	}

	if err := replaceDirectory(stagedTemplates, filepath.Join(target, "templates", "agentio")); err != nil {
		return fmt.Errorf("replace generated templates: %w", err)
	}
	if err := replaceDirectory(stagedFiles, filepath.Join(target, "files", "agentio")); err != nil {
		return fmt.Errorf("replace generated files: %w", err)
	}
	if err := writeFileAtomically(targetValuesPath, nextValues, 0o644); err != nil {
		return fmt.Errorf("write target values: %w", err)
	}
	return nil
}

type chartImageValues struct {
	Hub  string `yaml:"hub"`
	Name string `yaml:"name"`
	Tag  string `yaml:"tag"`
}

type sandboxControllerSourceValues struct {
	Global struct {
		Hub             string `yaml:"hub"`
		ClusterID       string `yaml:"clusterId"`
		CACertConfigMap string `yaml:"caCertConfigMap"`
	} `yaml:"global"`
	Ztunnel struct {
		Image chartImageValues `yaml:"image"`
	} `yaml:"ztunnel"`
	ProxyInit struct {
		Image chartImageValues `yaml:"image"`
	} `yaml:"proxyInit"`
}

// ExportSandboxController installs an already prepared traffic-proxy entry
// without replacing other sandbox runtime injection entries.
func ExportSandboxController(source, target string) error {
	sourceValues, err := os.ReadFile(filepath.Join(source, "values.yaml"))
	if err != nil {
		return fmt.Errorf("read prepared sandbox-controller values: %w", err)
	}
	if err := validatePreparedBlock(sourceValues, controllerValuesBegin, controllerValuesEnd, "sandbox-controller values"); err != nil {
		return err
	}
	targetValuesPath := filepath.Join(target, "values.yaml")
	targetValues, err := os.ReadFile(targetValuesPath)
	if err != nil {
		return fmt.Errorf("read sandbox-controller values: %w", err)
	}
	nextValues, err := replaceMarkedBlock(targetValues, sourceValues, controllerValuesBegin, controllerValuesEnd, "sandbox-controller values")
	if err != nil {
		return err
	}

	bundleTemplatePath, bundleTemplate, err := findSandboxInjectionConfigTemplate(filepath.Join(source, "templates"))
	if err != nil {
		return err
	}
	if bundleTemplate == nil {
		return errors.New("prepared sandbox-controller bundle does not contain sandbox-injection-config")
	}
	block, err := extractMarkedBlock(bundleTemplate, trafficProxyBegin, trafficProxyEnd, "prepared traffic-proxy template")
	if err != nil {
		return err
	}
	targetTemplatePath, existing, err := findSandboxInjectionConfigTemplate(filepath.Join(target, "templates"))
	if err != nil {
		return err
	}
	var nextTemplate []byte
	if existing == nil {
		targetTemplatePath = filepath.Join(target, "templates", filepath.Base(bundleTemplatePath))
		nextTemplate = bundleTemplate
	} else {
		nextTemplate, err = mergeTrafficProxyBlock(existing, block)
		if err != nil {
			return fmt.Errorf("update sandbox injection ConfigMap %q: %w", targetTemplatePath, err)
		}
	}

	if err := os.MkdirAll(filepath.Dir(targetTemplatePath), 0o755); err != nil {
		return fmt.Errorf("create sandbox-controller template directory: %w", err)
	}
	if err := writeFileAtomically(targetTemplatePath, nextTemplate, 0o644); err != nil {
		return fmt.Errorf("write sandbox injection ConfigMap: %w", err)
	}
	if err := writeFileAtomically(targetValuesPath, nextValues, 0o644); err != nil {
		return fmt.Errorf("write sandbox-controller values: %w", err)
	}
	return nil
}

// buildSandboxControllerBundle prepares the traffic-proxy integration source
// from the standalone Agentio chart.
func buildSandboxControllerBundle(source, target string) error {
	sourceValues, err := os.ReadFile(filepath.Join(source, "values.yaml"))
	if err != nil {
		return fmt.Errorf("read source values for sandbox-controller: %w", err)
	}
	controllerValues, err := generatedSandboxControllerValuesBlock(sourceValues)
	if err != nil {
		return err
	}
	targetValuesPath := filepath.Join(target, "values.yaml")
	targetValues, err := os.ReadFile(targetValuesPath)
	if err != nil {
		return fmt.Errorf("read sandbox-controller values: %w", err)
	}
	nextValues, err := replaceSandboxControllerValuesBlock(targetValues, controllerValues)
	if err != nil {
		return err
	}

	templatePath := filepath.Join(source, "files", trafficProxyTemplateFile)
	template, err := os.ReadFile(templatePath)
	if err != nil {
		return fmt.Errorf("read Kruise Agents traffic-proxy template: %w", err)
	}
	block := generatedTrafficProxyBlock(template)
	targetTemplatePath, existing, err := findSandboxInjectionConfigTemplate(filepath.Join(target, "templates"))
	if err != nil {
		return err
	}
	var nextTemplate []byte
	if existing == nil {
		targetTemplatePath = filepath.Join(target, "templates", generatedInjectionConfigFile)
		nextTemplate = newSandboxInjectionConfigTemplate(block)
	} else {
		nextTemplate, err = mergeTrafficProxyBlock(existing, block)
		if err != nil {
			return fmt.Errorf("update sandbox injection ConfigMap %q: %w", targetTemplatePath, err)
		}
	}

	if err := os.MkdirAll(filepath.Dir(targetTemplatePath), 0o755); err != nil {
		return fmt.Errorf("create sandbox-controller template directory: %w", err)
	}
	if err := writeFileAtomically(targetTemplatePath, nextTemplate, 0o644); err != nil {
		return fmt.Errorf("write sandbox injection ConfigMap: %w", err)
	}
	if err := writeFileAtomically(targetValuesPath, nextValues, 0o644); err != nil {
		return fmt.Errorf("write sandbox-controller values: %w", err)
	}
	return nil
}

func generatedSandboxControllerValuesBlock(content []byte) ([]byte, error) {
	values := sandboxControllerSourceValues{}
	if err := yaml.Unmarshal(content, &values); err != nil {
		return nil, fmt.Errorf("parse source values for sandbox-controller: %w", err)
	}
	ztunnelImage, err := resolveChartImage(values.Global.Hub, values.Ztunnel.Image)
	if err != nil {
		return nil, fmt.Errorf("resolve ztunnel image: %w", err)
	}
	proxyInitImage, err := resolveChartImage(values.Global.Hub, values.ProxyInit.Image)
	if err != nil {
		return nil, fmt.Errorf("resolve proxy-init image: %w", err)
	}
	clusterID := values.Global.ClusterID
	if clusterID == "" {
		clusterID = "Kubernetes"
	}
	caCertConfigMap := values.Global.CACertConfigMap
	if caCertConfigMap == "" {
		caCertConfigMap = "agentio-ca-certs"
	}

	generated := map[string]any{
		"agentio": map[string]any{
			"trafficProxy": map[string]any{
				"controlPlaneNamespace":   "agentio-system",
				"controlPlaneService":     "agentiod",
				"xdsAddress":              "",
				"caAddress":               "",
				"caCertConfigMap":         caCertConfigMap,
				"clusterId":               clusterID,
				"image":                   ztunnelImage,
				"initImage":               proxyInitImage,
				"imagePullPolicy":         "IfNotPresent",
				"healthProbeRewrite":      true,
				"dnsCapture":              true,
				"includeOutboundIPRanges": "*",
				"excludeOutboundIPRanges": "",
				"includeInboundPorts":     "*",
				"excludeInboundPorts":     "",
				"includeOutboundPorts":    "",
				"excludeOutboundPorts":    "",
				"resources": map[string]any{
					"requests": map[string]string{"cpu": "100m", "memory": "64Mi"},
					"limits":   map[string]string{"cpu": "200m", "memory": "128Mi"},
				},
				"initResources": map[string]any{
					"requests": map[string]string{"cpu": "100m", "memory": "128Mi"},
					"limits":   map[string]string{"cpu": "1", "memory": "1Gi"},
				},
			},
		},
	}
	encoded, err := yaml.Marshal(generated)
	if err != nil {
		return nil, fmt.Errorf("marshal sandbox-controller Agentio values: %w", err)
	}
	var out bytes.Buffer
	fmt.Fprintln(&out, controllerValuesBegin)
	out.Write(encoded)
	fmt.Fprintln(&out, controllerValuesEnd)
	return out.Bytes(), nil
}

func resolveChartImage(globalHub string, image chartImageValues) (string, error) {
	hub := image.Hub
	if hub == "" {
		hub = globalHub
	}
	if hub == "" || image.Name == "" || image.Tag == "" {
		return "", errors.New("hub, name, and tag must be non-empty")
	}
	return fmt.Sprintf("%s/%s:%s", strings.TrimSuffix(hub, "/"), strings.TrimPrefix(image.Name, "/"), image.Tag), nil
}

func replaceSandboxControllerValuesBlock(target, block []byte) ([]byte, error) {
	beginCount := bytes.Count(target, []byte(controllerValuesBegin))
	endCount := bytes.Count(target, []byte(controllerValuesEnd))
	if beginCount == 0 && endCount == 0 {
		out := append([]byte(nil), target...)
		if len(out) > 0 && out[len(out)-1] != '\n' {
			out = append(out, '\n')
		}
		if len(out) > 0 && !bytes.HasSuffix(out, []byte("\n\n")) {
			out = append(out, '\n')
		}
		return append(out, block...), nil
	}
	if beginCount != 1 || endCount != 1 {
		return nil, errors.New("sandbox-controller values must contain exactly one matching Agentio traffic-proxy marker pair")
	}
	begin := bytes.Index(target, []byte(controllerValuesBegin))
	end := bytes.Index(target, []byte(controllerValuesEnd))
	if begin > end {
		return nil, errors.New("sandbox-controller Agentio traffic-proxy markers are out of order")
	}
	end += len(controllerValuesEnd)
	if end < len(target) && target[end] == '\r' {
		end++
	}
	if end < len(target) && target[end] == '\n' {
		end++
	}
	out := make([]byte, 0, begin+len(block)+len(target)-end)
	out = append(out, target[:begin]...)
	out = append(out, block...)
	out = append(out, target[end:]...)
	return out, nil
}

func generatedTrafficProxyBlock(template []byte) []byte {
	template = bytes.TrimSuffix(template, []byte("\n"))
	var out bytes.Buffer
	fmt.Fprintln(&out, trafficProxyBegin)
	fmt.Fprintln(&out, "  traffic-proxy: |")
	for _, line := range bytes.Split(template, []byte("\n")) {
		if len(line) > 0 {
			out.WriteString("    ")
			out.Write(line)
		}
		out.WriteByte('\n')
	}
	fmt.Fprintln(&out, trafficProxyEnd)
	return out.Bytes()
}

func newSandboxInjectionConfigTemplate(block []byte) []byte {
	var out bytes.Buffer
	out.WriteString(warning)
	fmt.Fprintln(&out, "apiVersion: v1")
	fmt.Fprintln(&out, "kind: ConfigMap")
	fmt.Fprintln(&out, "metadata:")
	fmt.Fprintln(&out, "  name: sandbox-injection-config")
	fmt.Fprintln(&out, "  namespace: {{ include \"sandbox-controller.namespace\" . }}")
	fmt.Fprintln(&out, "data:")
	out.Write(block)
	return out.Bytes()
}

var sandboxInjectionConfigNamePattern = regexp.MustCompile(`(?m)^[ \t]*name:[ \t]*["']?sandbox-injection-config["']?[ \t]*\r?$`)
var yamlDataLinePattern = regexp.MustCompile(`(?m)^data:[ \t]*\r?\n`)
var yamlTrafficProxyLinePattern = regexp.MustCompile(`(?m)^  traffic-proxy:[^\r\n]*(?:\r?\n|$)`)

func findSandboxInjectionConfigTemplate(templates string) (string, []byte, error) {
	var foundPath string
	var foundContent []byte
	err := filepath.WalkDir(templates, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			return nil
		}
		if entry.Type()&os.ModeSymlink != 0 {
			return fmt.Errorf("sandbox-controller template %q is a symlink", path)
		}
		ext := strings.ToLower(filepath.Ext(path))
		if ext != ".yaml" && ext != ".yml" {
			return nil
		}
		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if !sandboxInjectionConfigNamePattern.Match(content) {
			return nil
		}
		if foundPath != "" {
			return fmt.Errorf("multiple sandbox-injection-config templates found: %q and %q", foundPath, path)
		}
		foundPath = path
		foundContent = content
		return nil
	})
	if err != nil {
		return "", nil, fmt.Errorf("find sandbox injection ConfigMap template: %w", err)
	}
	return foundPath, foundContent, nil
}

func mergeTrafficProxyBlock(content, block []byte) ([]byte, error) {
	beginCount := bytes.Count(content, []byte(trafficProxyBegin))
	endCount := bytes.Count(content, []byte(trafficProxyEnd))
	if beginCount != 0 || endCount != 0 {
		if beginCount != 1 || endCount != 1 {
			return nil, errors.New("template must contain exactly one matching Agentio traffic-proxy marker pair")
		}
		begin := bytes.Index(content, []byte(trafficProxyBegin))
		end := bytes.Index(content, []byte(trafficProxyEnd))
		if begin > end {
			return nil, errors.New("Agentio traffic-proxy template markers are out of order")
		}
		end += len(trafficProxyEnd)
		if end < len(content) && content[end] == '\r' {
			end++
		}
		if end < len(content) && content[end] == '\n' {
			end++
		}
		out := make([]byte, 0, begin+len(block)+len(content)-end)
		out = append(out, content[:begin]...)
		out = append(out, block...)
		out = append(out, content[end:]...)
		return out, nil
	}

	name := sandboxInjectionConfigNamePattern.FindIndex(content)
	if name == nil {
		return nil, errors.New("sandbox-injection-config metadata.name not found")
	}
	documentStart := bytes.LastIndex(content[:name[0]], []byte("\n---"))
	if documentStart < 0 {
		documentStart = 0
	} else {
		documentStart += len("\n---")
	}
	documentEndRelative := bytes.Index(content[name[1]:], []byte("\n---"))
	documentEnd := len(content)
	if documentEndRelative >= 0 {
		documentEnd = name[1] + documentEndRelative
	}
	document := content[documentStart:documentEnd]
	data := yamlDataLinePattern.FindIndex(document)
	if data != nil {
		insert := documentStart + data[1]
		if existing := yamlTrafficProxyLinePattern.FindIndex(content[insert:documentEnd]); existing != nil {
			entryStart := insert + existing[0]
			entryEnd := yamlEntryEnd(content, insert+existing[1], documentEnd, 2)
			out := make([]byte, 0, len(content)-entryEnd+entryStart+len(block))
			out = append(out, content[:entryStart]...)
			out = append(out, block...)
			out = append(out, content[entryEnd:]...)
			return out, nil
		}
		out := make([]byte, 0, len(content)+len(block))
		out = append(out, content[:insert]...)
		out = append(out, block...)
		out = append(out, content[insert:]...)
		return out, nil
	}

	insert := documentEnd
	var addition bytes.Buffer
	if insert > 0 && content[insert-1] != '\n' {
		addition.WriteByte('\n')
	}
	fmt.Fprintln(&addition, "data:")
	addition.Write(block)
	out := make([]byte, 0, len(content)+addition.Len())
	out = append(out, content[:insert]...)
	out = append(out, addition.Bytes()...)
	out = append(out, content[insert:]...)
	return out, nil
}

func yamlEntryEnd(content []byte, start, limit, indentation int) int {
	for offset := start; offset < limit; {
		lineEnd := bytes.IndexByte(content[offset:limit], '\n')
		next := limit
		if lineEnd >= 0 {
			next = offset + lineEnd + 1
		}
		line := bytes.TrimSuffix(content[offset:next], []byte("\n"))
		line = bytes.TrimSuffix(line, []byte("\r"))
		if len(bytes.TrimSpace(line)) > 0 {
			leading := len(line) - len(bytes.TrimLeft(line, " \t"))
			if leading <= indentation {
				return offset
			}
		}
		offset = next
	}
	return limit
}

func validateSourceValues(content []byte) error {
	values := map[string]any{}
	if err := yaml.Unmarshal(content, &values); err != nil {
		return fmt.Errorf("parse source values: %w", err)
	}
	if _, found := values["enabled"]; found {
		return errors.New("source values contain a conflicting root-level enabled key")
	}
	return nil
}

func prepareSandboxManagerValues(content []byte) ([]byte, error) {
	document := yamlv3.Node{}
	if err := yamlv3.Unmarshal(content, &document); err != nil {
		return nil, fmt.Errorf("parse source values for sandbox-manager: %w", err)
	}
	if len(document.Content) != 1 || document.Content[0].Kind != yamlv3.MappingNode {
		return nil, errors.New("source values for sandbox-manager must be a YAML mapping")
	}
	root := document.Content[0]
	removeYAMLMappingKeys(root, "ambient", "sidecarInjector", "ztunnel", "proxy", "proxyInit")
	if global := yamlMappingValue(root, "global"); global != nil {
		removeYAMLMappingKeys(global, "enableFirewallRules", "enableClusterTrustBundle")
		setYAMLKeyHeadComment(global, "caCertConfigMap", "-- CA certificate ConfigMap name distributed to traffic-proxy workload namespaces.")
		setYAMLKeyHeadComment(global, "resourcePrefix", "-- Identifier shared by Agentio configuration and leader-election resources.")
	}

	var out bytes.Buffer
	encoder := yamlv3.NewEncoder(&out)
	encoder.SetIndent(2)
	if err := encoder.Encode(&document); err != nil {
		return nil, fmt.Errorf("encode sandbox-manager Agentio values: %w", err)
	}
	if err := encoder.Close(); err != nil {
		return nil, fmt.Errorf("finish sandbox-manager Agentio values: %w", err)
	}
	return out.Bytes(), nil
}

func yamlMappingValue(mapping *yamlv3.Node, key string) *yamlv3.Node {
	if mapping == nil || mapping.Kind != yamlv3.MappingNode {
		return nil
	}
	for i := 0; i+1 < len(mapping.Content); i += 2 {
		if mapping.Content[i].Value == key {
			return mapping.Content[i+1]
		}
	}
	return nil
}

func removeYAMLMappingKeys(mapping *yamlv3.Node, keys ...string) {
	if mapping == nil || mapping.Kind != yamlv3.MappingNode {
		return
	}
	excluded := make(map[string]struct{}, len(keys))
	for _, key := range keys {
		excluded[key] = struct{}{}
	}
	content := mapping.Content[:0]
	for i := 0; i+1 < len(mapping.Content); i += 2 {
		if _, found := excluded[mapping.Content[i].Value]; found {
			continue
		}
		content = append(content, mapping.Content[i], mapping.Content[i+1])
	}
	mapping.Content = content
}

func setYAMLKeyHeadComment(mapping *yamlv3.Node, key, comment string) {
	if mapping == nil || mapping.Kind != yamlv3.MappingNode {
		return
	}
	for i := 0; i+1 < len(mapping.Content); i += 2 {
		if mapping.Content[i].Value == key {
			mapping.Content[i].HeadComment = comment
			return
		}
	}
}

func prepareSandboxManagerTemplate(rel string, content []byte) ([]byte, error) {
	var replacements [][2]string
	switch rel {
	case "agentiod.yaml":
		replacements = [][2]string{
			{`        {{- if .Values.ambient.enabled }}
        - name: CA_TRUSTED_NODE_ACCOUNTS
          value: {{ include "agentio.namespace" . }}/{{ include "agentio.ztunnel.name" . }}
        {{- end }}
`, ""},
			{`        - name: INJECTOR_CONFIG_MAP_NAME
          value: {{ printf "%s-sidecar-injector" .Values.global.resourcePrefix | quote }}
`, ""},
			{`        {{- if .Values.global.enableClusterTrustBundle }}
        - name: ENABLE_CLUSTER_TRUST_BUNDLE_API
          value: "true"
        {{- end }}
`, ""},
			{`        - name: INJECT_ENABLED
          value: "{{ .Values.sidecarInjector.enabled }}"
`, `        - name: INJECT_ENABLED
          value: "false"
`},
			{`        {{- if .Values.sidecarInjector.enabled }}
        - name: INJECTION_WEBHOOK_CONFIG_NAME
          value: {{ .Values.global.resourcePrefix }}-sidecar-injector-{{ include "agentio.namespace" . }}
        {{- end }}
`, ""},
			{`        - containerPort: 15017
          name: https-webhooks
          protocol: TCP
`, ""},
			{`  - name: https-webhook
    port: 443
    protocol: TCP
    targetPort: 15017
`, ""},
		}
	case "clusterrole.yaml":
		replacements = [][2]string{
			{`- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
  - update
  - patch
`, ""},
		}
	case "agentio-config.yaml":
		replacements = [][2]string{
			{"user overrides from .Values.agentioConfig.", "user overrides from .Values.agentio.agentioConfig."},
		}
	case "meshconfig.yaml":
		replacements = [][2]string{
			{"user overrides from .Values.meshConfig.", "user overrides from .Values.agentio.meshConfig."},
		}
	default:
		return content, nil
	}
	for _, replacement := range replacements {
		count := bytes.Count(content, []byte(replacement[0]))
		if count > 1 {
			return nil, fmt.Errorf("sandbox-manager capability block is duplicated in %q", rel)
		}
		if count == 1 {
			content = bytes.Replace(content, []byte(replacement[0]), []byte(replacement[1]), 1)
		}
	}
	for _, forbidden := range []string{
		".Values.ambient.enabled",
		".Values.sidecarInjector.enabled",
		".Values.global.enableClusterTrustBundle",
		"INJECTOR_CONFIG_MAP_NAME",
		"INJECTION_WEBHOOK_CONFIG_NAME",
		"CA_TRUSTED_NODE_ACCOUNTS",
		"ENABLE_CLUSTER_TRUST_BUNDLE_API",
		"https-webhook",
		"15017",
		"mutatingwebhookconfigurations",
	} {
		if bytes.Contains(content, []byte(forbidden)) {
			return nil, fmt.Errorf("sandbox-manager template %q retains unsupported capability %q", rel, forbidden)
		}
	}
	return content, nil
}

func validatePreparedBlock(content []byte, beginMarker, endMarker, description string) error {
	block, err := extractMarkedBlock(content, beginMarker, endMarker, description)
	if err != nil {
		return err
	}
	if !bytes.Equal(bytes.TrimSpace(content), bytes.TrimSpace(block)) {
		return fmt.Errorf("%s must contain only its generated marker block", description)
	}
	return nil
}

func extractMarkedBlock(content []byte, beginMarker, endMarker, description string) ([]byte, error) {
	beginCount := bytes.Count(content, []byte(beginMarker))
	endCount := bytes.Count(content, []byte(endMarker))
	if beginCount != 1 || endCount != 1 {
		return nil, fmt.Errorf("%s must contain exactly one matching marker pair", description)
	}
	begin := bytes.Index(content, []byte(beginMarker))
	end := bytes.Index(content, []byte(endMarker))
	if begin > end {
		return nil, fmt.Errorf("%s markers are out of order", description)
	}
	end += len(endMarker)
	if end < len(content) && content[end] == '\r' {
		end++
	}
	if end < len(content) && content[end] == '\n' {
		end++
	}
	return append([]byte(nil), content[begin:end]...), nil
}

func replaceMarkedBlock(target, block []byte, beginMarker, endMarker, description string) ([]byte, error) {
	beginCount := bytes.Count(target, []byte(beginMarker))
	endCount := bytes.Count(target, []byte(endMarker))
	if beginCount == 0 && endCount == 0 {
		out := append([]byte(nil), target...)
		if len(out) > 0 && out[len(out)-1] != '\n' {
			out = append(out, '\n')
		}
		if len(out) > 0 && !bytes.HasSuffix(out, []byte("\n\n")) {
			out = append(out, '\n')
		}
		return append(out, block...), nil
	}
	if beginCount != 1 || endCount != 1 {
		return nil, fmt.Errorf("%s must contain exactly one matching marker pair", description)
	}
	begin := bytes.Index(target, []byte(beginMarker))
	end := bytes.Index(target, []byte(endMarker))
	if begin > end {
		return nil, fmt.Errorf("%s markers are out of order", description)
	}
	end += len(endMarker)
	if end < len(target) && target[end] == '\r' {
		end++
	}
	if end < len(target) && target[end] == '\n' {
		end++
	}

	out := make([]byte, 0, begin+len(block)+len(target)-end)
	out = append(out, target[:begin]...)
	out = append(out, block...)
	out = append(out, target[end:]...)
	return out, nil
}

func replaceValuesBlock(target, source []byte) ([]byte, error) {
	block := generatedValuesBlock(source)
	beginCount := bytes.Count(target, []byte(valuesBegin))
	endCount := bytes.Count(target, []byte(valuesEnd))
	if beginCount == 0 && endCount == 0 {
		out := append([]byte(nil), target...)
		if len(out) > 0 && out[len(out)-1] != '\n' {
			out = append(out, '\n')
		}
		if len(out) > 0 && !bytes.HasSuffix(out, []byte("\n\n")) {
			out = append(out, '\n')
		}
		return append(out, block...), nil
	}
	if beginCount != 1 || endCount != 1 {
		return nil, fmt.Errorf("target values must contain exactly one matching Agentio generated-values marker pair")
	}

	begin := bytes.Index(target, []byte(valuesBegin))
	end := bytes.Index(target, []byte(valuesEnd))
	if begin > end {
		return nil, errors.New("target values Agentio generated-values markers are out of order")
	}
	end += len(valuesEnd)
	if end < len(target) && target[end] == '\r' {
		end++
	}
	if end < len(target) && target[end] == '\n' {
		end++
	}

	out := make([]byte, 0, begin+len(block)+len(target)-end)
	out = append(out, target[:begin]...)
	out = append(out, block...)
	out = append(out, target[end:]...)
	return out, nil
}

func generatedValuesBlock(source []byte) []byte {
	source = bytes.TrimSuffix(source, []byte("\n"))
	var out bytes.Buffer
	fmt.Fprintln(&out, valuesBegin)
	fmt.Fprintln(&out, "agentio:")
	fmt.Fprintln(&out, "  enabled: false")
	for _, line := range bytes.Split(source, []byte("\n")) {
		if len(line) == 0 {
			out.WriteByte('\n')
			continue
		}
		out.WriteString("  ")
		out.Write(line)
		out.WriteByte('\n')
	}
	fmt.Fprintln(&out, valuesEnd)
	return out.Bytes()
}

func exportTemplates(source, target string) error {
	return filepath.WalkDir(source, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			return nil
		}
		if entry.Type()&os.ModeSymlink != 0 {
			return fmt.Errorf("source template %q is a symlink", path)
		}
		rel, err := filepath.Rel(source, path)
		if err != nil {
			return fmt.Errorf("resolve source template path %q: %w", path, err)
		}
		rel = filepath.ToSlash(rel)
		if _, excluded := sandboxManagerExcludedTemplates[rel]; excluded {
			return nil
		}

		ext := strings.ToLower(filepath.Ext(path))
		if ext != ".yaml" && ext != ".yml" && ext != ".tpl" {
			return fmt.Errorf("unsupported source template file %q", path)
		}
		content, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read source template %q: %w", path, err)
		}
		content, err = prepareSandboxManagerTemplate(rel, content)
		if err != nil {
			return err
		}
		if ext == ".tpl" {
			content, err = rewriteTemplate(content)
			if err != nil {
				return fmt.Errorf("rewrite source template %q: %w", path, err)
			}
			content = append([]byte(warning), content...)
		} else {
			helpers, resource, err := splitLeadingDefinitions(content)
			if err != nil {
				return fmt.Errorf("split source template %q: %w", path, err)
			}
			if definePattern.Match(resource) {
				return fmt.Errorf("resource template %q contains a non-leading named template definition", path)
			}
			helpers, err = rewriteTemplate(helpers)
			if err != nil {
				return fmt.Errorf("rewrite helpers in source template %q: %w", path, err)
			}
			resource, err = rewriteTemplate(resource)
			if err != nil {
				return fmt.Errorf("rewrite resources in source template %q: %w", path, err)
			}
			var guarded bytes.Buffer
			guarded.WriteString(warning)
			guarded.Write(helpers)
			if len(helpers) > 0 && helpers[len(helpers)-1] != '\n' {
				guarded.WriteByte('\n')
			}
			guardResource := filepath.ToSlash(rel) != "crds.yaml"
			if guardResource {
				guarded.WriteString("{{- if .Values.agentio.enabled }}\n")
			}
			guarded.Write(resource)
			if len(resource) > 0 && resource[len(resource)-1] != '\n' {
				guarded.WriteByte('\n')
			}
			if guardResource {
				guarded.WriteString("{{- end }}\n")
			}
			content = guarded.Bytes()
		}

		destination := filepath.Join(target, rel)
		if err := os.MkdirAll(filepath.Dir(destination), 0o755); err != nil {
			return fmt.Errorf("create generated template directory: %w", err)
		}
		if err := os.WriteFile(destination, content, 0o644); err != nil {
			return fmt.Errorf("write generated template %q: %w", destination, err)
		}
		return nil
	})
}

func splitLeadingDefinitions(content []byte) ([]byte, []byte, error) {
	position := 0
	helperEnd := 0
	for {
		start := position
		for start < len(content) && unicode.IsSpace(rune(content[start])) {
			start++
		}
		if start+2 > len(content) || !bytes.HasPrefix(content[start:], []byte("{{")) {
			break
		}
		end, err := templateActionEnd(content[start:])
		if err != nil {
			return nil, nil, err
		}
		if templateCommand(content[start:start+end]) != "define" {
			break
		}
		definitionEnd, err := matchingDefinitionEnd(content, start)
		if err != nil {
			return nil, nil, err
		}
		helperEnd = definitionEnd
		position = definitionEnd
	}
	return content[:helperEnd], content[helperEnd:], nil
}

func matchingDefinitionEnd(content []byte, start int) (int, error) {
	depth := 0
	position := start
	for position < len(content) {
		next := bytes.Index(content[position:], []byte("{{"))
		if next < 0 {
			break
		}
		next += position
		trimmed := bytes.TrimLeft(content[next+2:], "- \t\r\n")
		var end int
		var err error
		if bytes.HasPrefix(trimmed, []byte("/*")) {
			end, err = templateCommentEnd(content[next:])
		} else {
			end, err = templateActionEnd(content[next:])
		}
		if err != nil {
			return 0, err
		}
		command := templateCommand(content[next : next+end])
		switch command {
		case "define", "if", "range", "with", "block":
			depth++
		case "end":
			depth--
			if depth == 0 {
				return next + end, nil
			}
			if depth < 0 {
				return 0, errors.New("named template has an unmatched end action")
			}
		}
		position = next + end
	}
	return 0, errors.New("named template definition is not closed")
}

func templateCommand(action []byte) string {
	if len(action) < 4 {
		return ""
	}
	body := strings.TrimSpace(string(action[2 : len(action)-2]))
	body = strings.TrimSpace(strings.Trim(body, "-"))
	if body == "" || strings.HasPrefix(body, "/*") {
		return ""
	}
	command, _, _ := strings.Cut(body, " ")
	return command
}

func rewriteTemplate(content []byte) ([]byte, error) {
	var out bytes.Buffer
	for len(content) > 0 {
		start := bytes.Index(content, []byte("{{"))
		if start < 0 {
			out.Write(content)
			break
		}
		out.Write(content[:start])
		content = content[start:]
		trimmed := bytes.TrimLeft(content[2:], "- \t\r\n")
		var end int
		var err error
		if bytes.HasPrefix(trimmed, []byte("/*")) {
			end, err = templateCommentEnd(content)
		} else {
			end, err = templateActionEnd(content)
		}
		if err != nil {
			return nil, err
		}
		action := content[:end]
		if bytes.HasPrefix(trimmed, []byte("/*")) {
			out.Write(action)
		} else {
			rewritten := rewriteValuesReferences(action)
			rewritten = bytes.ReplaceAll(rewritten,
				[]byte(`"enhancedTrafficManagement.meshConfig"`),
				[]byte(`"agentio.meshConfig.defaults"`))
			rewritten = filesPattern.ReplaceAll(rewritten, []byte(`${1}"files/agentio/`))
			out.Write(rewritten)
		}
		content = content[end:]
	}
	return out.Bytes(), nil
}

func templateCommentEnd(action []byte) (int, error) {
	commentEnd := bytes.Index(action, []byte("*/"))
	if commentEnd < 0 {
		return 0, errors.New("unterminated Helm template comment")
	}
	for i := commentEnd + 2; i+1 < len(action); i++ {
		if action[i] == '}' && action[i+1] == '}' {
			return i + 2, nil
		}
		if action[i] != '-' && action[i] != ' ' && action[i] != '\t' && action[i] != '\r' && action[i] != '\n' {
			break
		}
	}
	return 0, errors.New("invalid Helm template comment terminator")
}

func templateActionEnd(action []byte) (int, error) {
	var quote byte
	escaped := false
	for i := 2; i+1 < len(action); i++ {
		ch := action[i]
		if quote != 0 {
			if quote != '`' && escaped {
				escaped = false
				continue
			}
			if quote != '`' && ch == '\\' {
				escaped = true
				continue
			}
			if ch == quote {
				quote = 0
			}
			continue
		}
		if ch == '"' || ch == '\'' || ch == '`' {
			quote = ch
			continue
		}
		if ch == '}' && action[i+1] == '}' {
			return i + 2, nil
		}
	}
	return 0, errors.New("unterminated Helm template action")
}

func rewriteValuesReferences(action []byte) []byte {
	const token = ".Values"
	var out bytes.Buffer
	var quote byte
	escaped := false
	for i := 0; i < len(action); {
		ch := action[i]
		if quote != 0 {
			out.WriteByte(ch)
			i++
			if quote != '`' && escaped {
				escaped = false
				continue
			}
			if quote != '`' && ch == '\\' {
				escaped = true
				continue
			}
			if ch == quote {
				quote = 0
			}
			continue
		}
		if ch == '"' || ch == '\'' || ch == '`' {
			quote = ch
			out.WriteByte(ch)
			i++
			continue
		}
		if strings.HasPrefix(string(action[i:]), token) && valueTokenBoundary(action, i, len(token)) {
			out.WriteString(token)
			if !hasAgentioSegment(action[i+len(token):]) {
				out.WriteString(".agentio")
			}
			i += len(token)
			continue
		}
		out.WriteByte(ch)
		i++
	}
	return out.Bytes()
}

func hasAgentioSegment(content []byte) bool {
	const segment = ".agentio"
	if !bytes.HasPrefix(content, []byte(segment)) {
		return false
	}
	if len(content) == len(segment) {
		return true
	}
	next := rune(content[len(segment)])
	return !unicode.IsLetter(next) && !unicode.IsDigit(next) && next != '_'
}

func valueTokenBoundary(content []byte, start, length int) bool {
	if start > 0 {
		previous := rune(content[start-1])
		if unicode.IsLetter(previous) || unicode.IsDigit(previous) || previous == '_' {
			return false
		}
	}
	end := start + length
	if end < len(content) {
		next := rune(content[end])
		if unicode.IsLetter(next) || unicode.IsDigit(next) || next == '_' {
			return false
		}
	}
	return true
}

func copyTree(source, target string, excluded map[string]struct{}) error {
	return filepath.WalkDir(source, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.Type()&os.ModeSymlink != 0 {
			return fmt.Errorf("source file %q is a symlink", path)
		}
		rel, err := filepath.Rel(source, path)
		if err != nil {
			return err
		}
		if _, found := excluded[filepath.ToSlash(rel)]; found {
			return nil
		}
		destination := filepath.Join(target, rel)
		if entry.IsDir() {
			return os.MkdirAll(destination, 0o755)
		}
		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if err := os.MkdirAll(filepath.Dir(destination), 0o755); err != nil {
			return err
		}
		return os.WriteFile(destination, content, 0o644)
	})
}

func replaceDirectory(source, target string) error {
	if err := os.RemoveAll(target); err != nil {
		return err
	}
	if _, err := os.Stat(source); os.IsNotExist(err) {
		return nil
	} else if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return err
	}
	return os.Rename(source, target)
}

func writeFileAtomically(path string, content []byte, mode fs.FileMode) error {
	temporary, err := os.CreateTemp(filepath.Dir(path), ".agentio-values-")
	if err != nil {
		return err
	}
	temporaryName := temporary.Name()
	defer os.Remove(temporaryName)
	if err := temporary.Chmod(mode); err != nil {
		temporary.Close()
		return err
	}
	if _, err := temporary.Write(content); err != nil {
		temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	return os.Rename(temporaryName, path)
}
