// Copyright 2026 The Kruise Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: api/security/v1/trafficpolicy.proto

package securityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// One compiled TrafficPolicy/GlobalTrafficPolicy, retaining both directions.
// Selection and explicit attachment are resolved before publication.
type TrafficPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable identity, e.g. trafficpolicy/demo/internet or
	// globaltrafficpolicy/platform-baseline.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Source namespace; required for NAMESPACE scope.
	// Empty for a cluster-scoped GlobalTrafficPolicy.
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Nonnegative; higher values are evaluated first, following the source API.
	// The compiler materializes the source default (1000).
	Priority int32 `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	// Absent = direction not configured; present with no rules = no rule matches.
	Ingress *TrafficPolicy_PolicyRule `protobuf:"bytes,4,opt,name=ingress,proto3" json:"ingress,omitempty"`
	Egress  *TrafficPolicy_PolicyRule `protobuf:"bytes,5,opt,name=egress,proto3" json:"egress,omitempty"`
	// GLOBAL: applies to all workloads; NAMESPACE: applies within namespace.
	// WORKLOAD_SELECTOR: applies through control-plane-generated workload refs,
	// including selector-based GlobalTrafficPolicies. Do not infer scope from name.
	Scope         Scope `protobuf:"varint,6,opt,name=scope,proto3,enum=agentio.security.Scope" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficPolicy) Reset() {
	*x = TrafficPolicy{}
	mi := &file_api_security_v1_trafficpolicy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficPolicy) ProtoMessage() {}

func (x *TrafficPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_api_security_v1_trafficpolicy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficPolicy.ProtoReflect.Descriptor instead.
func (*TrafficPolicy) Descriptor() ([]byte, []int) {
	return file_api_security_v1_trafficpolicy_proto_rawDescGZIP(), []int{0}
}

func (x *TrafficPolicy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrafficPolicy) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *TrafficPolicy) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *TrafficPolicy) GetIngress() *TrafficPolicy_PolicyRule {
	if x != nil {
		return x.Ingress
	}
	return nil
}

func (x *TrafficPolicy) GetEgress() *TrafficPolicy_PolicyRule {
	if x != nil {
		return x.Egress
	}
	return nil
}

func (x *TrafficPolicy) GetScope() Scope {
	if x != nil {
		return x.Scope
	}
	return Scope_GLOBAL
}

type TrafficPolicy_PolicyRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// First matching rule wins, in declaration order.
	// No match continues to the next policy; no per-policy default.
	Rules         []*TrafficPolicy_Rule `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficPolicy_PolicyRule) Reset() {
	*x = TrafficPolicy_PolicyRule{}
	mi := &file_api_security_v1_trafficpolicy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficPolicy_PolicyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficPolicy_PolicyRule) ProtoMessage() {}

func (x *TrafficPolicy_PolicyRule) ProtoReflect() protoreflect.Message {
	mi := &file_api_security_v1_trafficpolicy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficPolicy_PolicyRule.ProtoReflect.Descriptor instead.
func (*TrafficPolicy_PolicyRule) Descriptor() ([]byte, []int) {
	return file_api_security_v1_trafficpolicy_proto_rawDescGZIP(), []int{0, 0}
}

func (x *TrafficPolicy_PolicyRule) GetRules() []*TrafficPolicy_Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type TrafficPolicy_Rule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reuse ALLOW/DENY (source allow/reject); the compiler sets the action.
	// The protobuf default is ALLOW. Unknown values are invalid.
	Action Action `protobuf:"varint,1,opt,name=action,proto3,enum=agentio.security.Action" json:"action,omitempty"`
	// Required presence. Explicit {} matches all traffic.
	Match         *TrafficPolicy_Match `protobuf:"bytes,2,opt,name=match,proto3" json:"match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficPolicy_Rule) Reset() {
	*x = TrafficPolicy_Rule{}
	mi := &file_api_security_v1_trafficpolicy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficPolicy_Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficPolicy_Rule) ProtoMessage() {}

func (x *TrafficPolicy_Rule) ProtoReflect() protoreflect.Message {
	mi := &file_api_security_v1_trafficpolicy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficPolicy_Rule.ProtoReflect.Descriptor instead.
func (*TrafficPolicy_Rule) Descriptor() ([]byte, []int) {
	return file_api_security_v1_trafficpolicy_proto_rawDescGZIP(), []int{0, 1}
}

func (x *TrafficPolicy_Rule) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ALLOW
}

func (x *TrafficPolicy_Rule) GetMatch() *TrafficPolicy_Match {
	if x != nil {
		return x.Match
	}
	return nil
}

type TrafficPolicy_Match struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Dimensions are ANDed; values within each dimension are ORed.
	// Empty address list = unconstrained.
	// Resolve peers in the control plane. If an explicitly configured source
	// or destination peer list resolves to no addresses, omit the entire Rule
	// while retaining the configured direction, even if no rules remain.
	// Validate Address byte/prefix lengths and normalize host bits.
	SourceIps      []*Address `protobuf:"bytes,1,rep,name=source_ips,json=sourceIps,proto3" json:"source_ips,omitempty"`
	DestinationIps []*Address `protobuf:"bytes,2,rep,name=destination_ips,json=destinationIps,proto3" json:"destination_ips,omitempty"`
	// Empty = any protocol/port. Entries are ORed.
	Ports         []*TrafficPolicy_PortMatch `protobuf:"bytes,3,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficPolicy_Match) Reset() {
	*x = TrafficPolicy_Match{}
	mi := &file_api_security_v1_trafficpolicy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficPolicy_Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficPolicy_Match) ProtoMessage() {}

func (x *TrafficPolicy_Match) ProtoReflect() protoreflect.Message {
	mi := &file_api_security_v1_trafficpolicy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficPolicy_Match.ProtoReflect.Descriptor instead.
func (*TrafficPolicy_Match) Descriptor() ([]byte, []int) {
	return file_api_security_v1_trafficpolicy_proto_rawDescGZIP(), []int{0, 2}
}

func (x *TrafficPolicy_Match) GetSourceIps() []*Address {
	if x != nil {
		return x.SourceIps
	}
	return nil
}

func (x *TrafficPolicy_Match) GetDestinationIps() []*Address {
	if x != nil {
		return x.DestinationIps
	}
	return nil
}

func (x *TrafficPolicy_Match) GetPorts() []*TrafficPolicy_PortMatch {
	if x != nil {
		return x.Ports
	}
	return nil
}

type TrafficPolicy_PortMatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reuse ALL/TCP/UDP/ICMP/SCTP. Unknown values are invalid.
	// ALL with a port constraint only matches protocols with destination ports.
	Protocol Protocol `protobuf:"varint,1,opt,name=protocol,proto3,enum=agentio.security.Protocol" json:"protocol,omitempty"`
	// Inclusive destination port bounds, when present, must be in 1..65535.
	// Only port: match that single port.
	// Only end_port: match 1..end_port.
	// Both: match port..end_port, requiring port <= end_port.
	// Neither: any port (no port test). ICMP requires both fields absent.
	Port          *uint32 `protobuf:"varint,2,opt,name=port,proto3,oneof" json:"port,omitempty"`
	EndPort       *uint32 `protobuf:"varint,3,opt,name=end_port,json=endPort,proto3,oneof" json:"end_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficPolicy_PortMatch) Reset() {
	*x = TrafficPolicy_PortMatch{}
	mi := &file_api_security_v1_trafficpolicy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficPolicy_PortMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficPolicy_PortMatch) ProtoMessage() {}

func (x *TrafficPolicy_PortMatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_security_v1_trafficpolicy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficPolicy_PortMatch.ProtoReflect.Descriptor instead.
func (*TrafficPolicy_PortMatch) Descriptor() ([]byte, []int) {
	return file_api_security_v1_trafficpolicy_proto_rawDescGZIP(), []int{0, 3}
}

func (x *TrafficPolicy_PortMatch) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_ALL
}

func (x *TrafficPolicy_PortMatch) GetPort() uint32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

func (x *TrafficPolicy_PortMatch) GetEndPort() uint32 {
	if x != nil && x.EndPort != nil {
		return *x.EndPort
	}
	return 0
}

var File_api_security_v1_trafficpolicy_proto protoreflect.FileDescriptor

const file_api_security_v1_trafficpolicy_proto_rawDesc = "" +
	"\n" +
	"#api/security/v1/trafficpolicy.proto\x12\x10agentio.security\x1a#api/security/v1/authorization.proto\"\xb5\x06\n" +
	"\rTrafficPolicy\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12D\n" +
	"\aingress\x18\x04 \x01(\v2*.agentio.security.TrafficPolicy.PolicyRuleR\aingress\x12B\n" +
	"\x06egress\x18\x05 \x01(\v2*.agentio.security.TrafficPolicy.PolicyRuleR\x06egress\x12-\n" +
	"\x05scope\x18\x06 \x01(\x0e2\x17.agentio.security.ScopeR\x05scope\x1aH\n" +
	"\n" +
	"PolicyRule\x12:\n" +
	"\x05rules\x18\x01 \x03(\v2$.agentio.security.TrafficPolicy.RuleR\x05rules\x1au\n" +
	"\x04Rule\x120\n" +
	"\x06action\x18\x01 \x01(\x0e2\x18.agentio.security.ActionR\x06action\x12;\n" +
	"\x05match\x18\x02 \x01(\v2%.agentio.security.TrafficPolicy.MatchR\x05match\x1a\xc6\x01\n" +
	"\x05Match\x128\n" +
	"\n" +
	"source_ips\x18\x01 \x03(\v2\x19.agentio.security.AddressR\tsourceIps\x12B\n" +
	"\x0fdestination_ips\x18\x02 \x03(\v2\x19.agentio.security.AddressR\x0edestinationIps\x12?\n" +
	"\x05ports\x18\x03 \x03(\v2).agentio.security.TrafficPolicy.PortMatchR\x05ports\x1a\x92\x01\n" +
	"\tPortMatch\x126\n" +
	"\bprotocol\x18\x01 \x01(\x0e2\x1a.agentio.security.ProtocolR\bprotocol\x12\x17\n" +
	"\x04port\x18\x02 \x01(\rH\x00R\x04port\x88\x01\x01\x12\x1e\n" +
	"\bend_port\x18\x03 \x01(\rH\x01R\aendPort\x88\x01\x01B\a\n" +
	"\x05_portB\v\n" +
	"\t_end_portB:Z8github.com/openkruise/agentio/api/security/v1;securityv1b\x06proto3"

var (
	file_api_security_v1_trafficpolicy_proto_rawDescOnce sync.Once
	file_api_security_v1_trafficpolicy_proto_rawDescData []byte
)

func file_api_security_v1_trafficpolicy_proto_rawDescGZIP() []byte {
	file_api_security_v1_trafficpolicy_proto_rawDescOnce.Do(func() {
		file_api_security_v1_trafficpolicy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_security_v1_trafficpolicy_proto_rawDesc), len(file_api_security_v1_trafficpolicy_proto_rawDesc)))
	})
	return file_api_security_v1_trafficpolicy_proto_rawDescData
}

var file_api_security_v1_trafficpolicy_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_security_v1_trafficpolicy_proto_goTypes = []any{
	(*TrafficPolicy)(nil),            // 0: agentio.security.TrafficPolicy
	(*TrafficPolicy_PolicyRule)(nil), // 1: agentio.security.TrafficPolicy.PolicyRule
	(*TrafficPolicy_Rule)(nil),       // 2: agentio.security.TrafficPolicy.Rule
	(*TrafficPolicy_Match)(nil),      // 3: agentio.security.TrafficPolicy.Match
	(*TrafficPolicy_PortMatch)(nil),  // 4: agentio.security.TrafficPolicy.PortMatch
	(Scope)(0),                       // 5: agentio.security.Scope
	(Action)(0),                      // 6: agentio.security.Action
	(*Address)(nil),                  // 7: agentio.security.Address
	(Protocol)(0),                    // 8: agentio.security.Protocol
}
var file_api_security_v1_trafficpolicy_proto_depIdxs = []int32{
	1,  // 0: agentio.security.TrafficPolicy.ingress:type_name -> agentio.security.TrafficPolicy.PolicyRule
	1,  // 1: agentio.security.TrafficPolicy.egress:type_name -> agentio.security.TrafficPolicy.PolicyRule
	5,  // 2: agentio.security.TrafficPolicy.scope:type_name -> agentio.security.Scope
	2,  // 3: agentio.security.TrafficPolicy.PolicyRule.rules:type_name -> agentio.security.TrafficPolicy.Rule
	6,  // 4: agentio.security.TrafficPolicy.Rule.action:type_name -> agentio.security.Action
	3,  // 5: agentio.security.TrafficPolicy.Rule.match:type_name -> agentio.security.TrafficPolicy.Match
	7,  // 6: agentio.security.TrafficPolicy.Match.source_ips:type_name -> agentio.security.Address
	7,  // 7: agentio.security.TrafficPolicy.Match.destination_ips:type_name -> agentio.security.Address
	4,  // 8: agentio.security.TrafficPolicy.Match.ports:type_name -> agentio.security.TrafficPolicy.PortMatch
	8,  // 9: agentio.security.TrafficPolicy.PortMatch.protocol:type_name -> agentio.security.Protocol
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_security_v1_trafficpolicy_proto_init() }
func file_api_security_v1_trafficpolicy_proto_init() {
	if File_api_security_v1_trafficpolicy_proto != nil {
		return
	}
	file_api_security_v1_authorization_proto_init()
	file_api_security_v1_trafficpolicy_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_security_v1_trafficpolicy_proto_rawDesc), len(file_api_security_v1_trafficpolicy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_security_v1_trafficpolicy_proto_goTypes,
		DependencyIndexes: file_api_security_v1_trafficpolicy_proto_depIdxs,
		MessageInfos:      file_api_security_v1_trafficpolicy_proto_msgTypes,
	}.Build()
	File_api_security_v1_trafficpolicy_proto = out.File
	file_api_security_v1_trafficpolicy_proto_goTypes = nil
	file_api_security_v1_trafficpolicy_proto_depIdxs = nil
}
