// Copyright 2026 The Kruise Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Command envdocs updates only the generated environment tables in the reference docs.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
)

const (
	beginMarker = "<!-- BEGIN GENERATED ENVIRONMENT VARIABLES -->"
	endMarker   = "<!-- END GENERATED ENVIRONMENT VARIABLES -->"
)

type reference struct {
	command  string
	document string
	content  []byte
}

func main() {
	check := flag.Bool("check", false, "fail if generated environment documentation is out of date")
	flag.Parse()
	if err := run(*check); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(check bool) error {
	temporaryDir, err := os.MkdirTemp("", "agentio-envdocs-")
	if err != nil {
		return err
	}
	defer func() {
		if err := os.RemoveAll(temporaryDir); err != nil {
			fmt.Fprintln(os.Stderr, err)
		}
	}()
	references := []reference{
		{command: "./cmd/agentiod", document: "docs/reference/agentiod-environment-variables.md"},
		{command: "./extensions/epe/cmd/epe", document: "docs/reference/epe-configuration.md"},
	}
	// Prepare both documents before writing either, so a failed build or bad marker
	// does not leave a partially regenerated set of tables.
	for i := range references {
		ref := &references[i]
		binary := filepath.Join(temporaryDir, filepath.Base(ref.command))
		build := exec.Command("go", "build", "-o", binary, ref.command)
		build.Stdout, build.Stderr = os.Stderr, os.Stderr
		if err := build.Run(); err != nil {
			return fmt.Errorf("build %s: %w", ref.command, err)
		}
		export := exec.Command(binary, "-print-env", "-print-env-format=markdown")
		// Read declared defaults independently of the developer's environment.
		// The binary exits before loading Kubernetes config or starting listeners.
		export.Env = []string{"GOMAXPROCS=1"}
		export.Stderr = os.Stderr
		table, err := export.Output()
		if err != nil {
			return fmt.Errorf("export %s: %w", ref.command, err)
		}
		original, err := os.ReadFile(ref.document)
		if err != nil {
			return err
		}
		ref.content, err = replaceTable(original, table)
		if err != nil {
			return fmt.Errorf("%s: %w", ref.document, err)
		}
		if check && !bytes.Equal(original, ref.content) {
			return fmt.Errorf("%s is out of date; run make gen.envdocs", ref.document)
		}
	}
	if !check {
		for _, ref := range references {
			if err := os.WriteFile(ref.document, ref.content, 0o644); err != nil {
				return err
			}
		}
	}
	return nil
}

func replaceTable(document, table []byte) ([]byte, error) {
	begin, end := []byte(beginMarker), []byte(endMarker)
	if bytes.Count(document, begin) != 1 || bytes.Count(document, end) != 1 {
		return nil, fmt.Errorf("expected exactly one pair of generated environment markers")
	}
	start := bytes.Index(document, begin) + len(begin)
	stop := bytes.Index(document, end)
	if start > stop {
		return nil, fmt.Errorf("generated environment markers are in the wrong order")
	}
	if !bytes.HasPrefix(table, []byte("| Variable | Type | Binary default | Description |\n")) || bytes.Count(table, []byte("\n")) < 3 {
		return nil, fmt.Errorf("export did not produce an environment table")
	}
	var result bytes.Buffer
	result.Write(document[:start])
	result.WriteString("\n<!-- Generated by make gen.envdocs from env.Register metadata; do not edit this table. -->\n\n")
	result.Write(bytes.TrimSpace(table))
	result.WriteString("\n\n")
	result.Write(document[stop:])
	return result.Bytes(), nil
}
