// Copyright 2026 The Kruise Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"
)

func TestCheck(t *testing.T) {
	tests := []struct {
		name string
		code string
		want []int
	}{
		{
			name: "mixed field layout",
			code: "package p\nvar x = T{\nA: 1, B: 2,\nC: 3,\n}\n",
			want: []int{3},
		},
		{
			name: "field after nested literal",
			code: "package p\nvar x = T{A: T{\nA: 1,\n}, B: 2}\n",
			want: []int{4},
		},
		{
			name: "separate fields",
			code: "package p\nvar x = T{\nA: 1,\nB: T{C: 2, D: 3},\n}\n",
		},
		{
			name: "grouped declaration",
			code: "package p\ntype T struct {\nA, B string\n}\n",
			want: []int{3},
		},
		{
			name: "function parameters are allowed",
			code: "package p\nfunc f(a, b int) { println(a + b) }\n",
		},
		{
			name: "multiple statements",
			code: "package p\nfunc f() { defer func() { g(); h() }() }\n",
			want: []int{2},
		},
		{
			name: "switch and select bodies",
			code: "package p\nfunc f() {\nswitch { default: g(); h() }\nselect { default: g(); h() }\n}\n",
			want: []int{3, 4},
		},
		{
			name: "control flow semicolons are allowed",
			code: "package p\nfunc f() {\nfor i := 0; i < 2; i++ { g() }\nif x := g(); x { h() }\n}\n",
		},
		{
			name: "comments and strings are not statements",
			code: "package p\nfunc f() { println(\"a;b\") /* g(); h() */ }\n",
		},
		{
			name: "generated file",
			code: "// Code generated by a tool. DO NOT EDIT.\npackage p\nfunc f() { g(); h() }\n",
		},
		{
			name: "literal line directives do not change diagnostic positions",
			code: "package p\n//line elsewhere.go:100\nfunc f() { g(); h() }\n",
			want: []int{3},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			issues, err := check("fixture.go", []byte(tt.code))
			if err != nil {
				t.Fatal(err)
			}
			var lines []int
			for _, issue := range issues {
				lines = append(lines, issue.line)
			}
			if !slices.Equal(lines, tt.want) {
				t.Fatalf("lines = %v, want %v", lines, tt.want)
			}
		})
	}
}

func TestAddedLines(t *testing.T) {
	diff := []byte("@@ -1,0 +2,2 @@\n+a\n+b\n@@ -7 +9 @@ f\n-old\n+new\n@@ -10,2 +11,0 @@\n-old\n-old\n")
	want := []lineRange{
		{start: 2, end: 3},
		{start: 9, end: 9},
	}
	got, err := addedLines(diff)
	if err != nil {
		t.Fatal(err)
	}
	if !slices.Equal(got, want) {
		t.Fatalf("ranges = %v, want %v", got, want)
	}
}

func TestIncrementalCheck(t *testing.T) {
	t.Chdir(t.TempDir())
	runGit := func(args ...string) {
		t.Helper()
		if _, err := git(args...); err != nil {
			t.Fatal(err)
		}
	}
	write := func(name, content string) {
		t.Helper()
		if err := os.MkdirAll(filepath.Dir(name), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(name, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	runGit("init", "-q")
	original := "package p\nfunc old() { g(); h() }\n"
	write("old.go", original)
	write("deleted.go", "package p\n")
	runGit("add", ".")
	runGit("-c", "user.name=Test", "-c", "user.email=test@example.invalid", "commit", "-qm", "base")
	if err := os.Remove("deleted.go"); err != nil {
		t.Fatal(err)
	}
	write("old.go", original+"func newFunction() { g() }\n")
	write("test/e2e/with space_test.go", "package p\nfunc f() { g(); h() }\n")
	runGit("add", "test/e2e/with space_test.go")
	write("new.go", "package p\nfunc f() { g(); h() }\n")
	write("generated.go", "// Code generated by a tool. DO NOT EDIT.\npackage p\nfunc f() { g(); h() }\n")
	write("vendor/dependency.go", original)
	files, err := changedFiles("HEAD")
	if err != nil {
		t.Fatal(err)
	}
	want := []string{"generated.go", "new.go", "old.go", "test/e2e/with space_test.go"}
	if !slices.Equal(files, want) {
		t.Fatalf("files = %v, want %v", files, want)
	}
	if err := run("HEAD", nil); err == nil || !strings.Contains(err.Error(), "2 Go style findings") {
		t.Fatalf("incremental result = %v, want only the two new violations", err)
	}
	if err := run("HEAD", []string{"old.go"}); err == nil {
		t.Fatal("explicit file should include existing violations")
	}
	if _, err := changedFiles("does-not-exist"); err == nil {
		t.Fatal("invalid base should fail")
	}
}
