// Copyright 2026 The Kruise Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/config/v1/agentioconfig.proto

// Control-plane-only configuration. These messages are decoded from ConfigMap
// YAML by field name (jsonpb) and are never packed into an Any or sent over
// xDS, so this proto package name is not a wire contract. Wire-bound egress
// policy messages live in api/extensions/v1/egresspolicy.proto instead.

package configv1

import (
	duration "github.com/golang/protobuf/ptypes/duration"
	v1 "github.com/openkruise/agentio/api/extensions/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1alpha3 "istio.io/api/networking/v1alpha3"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HeaderSendMode mirrors Envoy's ProcessingMode.HeaderSendMode.
type HeaderSendMode int32

const (
	// Use the default behavior (request headers are sent, response headers are not).
	HeaderSendMode_DEFAULT HeaderSendMode = 0
	// Send the header/trailer to the ext_proc server.
	HeaderSendMode_SEND HeaderSendMode = 1
	// Do not send the header/trailer to the ext_proc server.
	HeaderSendMode_SKIP HeaderSendMode = 2
)

// Enum value maps for HeaderSendMode.
var (
	HeaderSendMode_name = map[int32]string{
		0: "DEFAULT",
		1: "SEND",
		2: "SKIP",
	}
	HeaderSendMode_value = map[string]int32{
		"DEFAULT": 0,
		"SEND":    1,
		"SKIP":    2,
	}
)

func (x HeaderSendMode) Enum() *HeaderSendMode {
	p := new(HeaderSendMode)
	*p = x
	return p
}

func (x HeaderSendMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HeaderSendMode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_config_v1_agentioconfig_proto_enumTypes[0].Descriptor()
}

func (HeaderSendMode) Type() protoreflect.EnumType {
	return &file_api_config_v1_agentioconfig_proto_enumTypes[0]
}

func (x HeaderSendMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HeaderSendMode.Descriptor instead.
func (HeaderSendMode) EnumDescriptor() ([]byte, []int) {
	return file_api_config_v1_agentioconfig_proto_rawDescGZIP(), []int{0}
}

// AgentioConfig is the complete configuration for the agentio controller.
type AgentioConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// External processing provider for sandbox traffic inspection and policy enforcement.
	SandboxExtProc *ExtProcProvider `protobuf:"bytes,1,opt,name=sandbox_ext_proc,json=sandboxExtProc,proto3" json:"sandbox_ext_proc,omitempty"`
	// Ordered list of egress policies. Traffic is evaluated against policies
	// in order; the first matching policy's action is applied.
	EgressPolicies []*v1.EgressPolicy `protobuf:"bytes,2,rep,name=egress_policies,json=egressPolicies,proto3" json:"egress_policies,omitempty"`
	// Filter sandbox labels to reduce xds push size.
	SandboxIgnoredLabels []string `protobuf:"bytes,3,rep,name=sandbox_ignored_labels,json=sandboxIgnoredLabels,proto3" json:"sandbox_ignored_labels,omitempty"`
	// Per-gateway settings; tls_termination lives inside each gateway here so
	// SDS can authorize on-demand cert pulls per gateway.
	EgressGateways []*EgressGateway `protobuf:"bytes,4,rep,name=egress_gateways,json=egressGateways,proto3" json:"egress_gateways,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentioConfig) Reset() {
	*x = AgentioConfig{}
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentioConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentioConfig) ProtoMessage() {}

func (x *AgentioConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentioConfig.ProtoReflect.Descriptor instead.
func (*AgentioConfig) Descriptor() ([]byte, []int) {
	return file_api_config_v1_agentioconfig_proto_rawDescGZIP(), []int{0}
}

func (x *AgentioConfig) GetSandboxExtProc() *ExtProcProvider {
	if x != nil {
		return x.SandboxExtProc
	}
	return nil
}

func (x *AgentioConfig) GetEgressPolicies() []*v1.EgressPolicy {
	if x != nil {
		return x.EgressPolicies
	}
	return nil
}

func (x *AgentioConfig) GetSandboxIgnoredLabels() []string {
	if x != nil {
		return x.SandboxIgnoredLabels
	}
	return nil
}

func (x *AgentioConfig) GetEgressGateways() []*EgressGateway {
	if x != nil {
		return x.EgressGateways
	}
	return nil
}

// EgressGateway describes one sandbox egress gateway's behavior. The same
// message is used by AgentioConfig entries and Gateway API parametersRef
// ConfigMaps; runtime Deployment and Pod observations are not part of it.
type EgressGateway struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Declaration name when nested in AgentioConfig.egress_gateways. Omit this
	// field in a Gateway API parametersRef payload because Gateway metadata is
	// authoritative there.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Declaration namespace when nested in AgentioConfig.egress_gateways. Omit
	// this field in a Gateway API parametersRef payload.
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Per-gateway TLS termination policy. nil means this gateway forwards all
	// TLS traffic without termination (the egress-gateway listener falls back to the
	// no-SNI-match protocolMatcher).
	TlsTermination *TlsTerminationConfig `protobuf:"bytes,3,opt,name=tls_termination,json=tlsTermination,proto3" json:"tls_termination,omitempty"`
	// Per-gateway ext_proc override. When set, this gateway uses its own
	// ext_proc endpoint instead of the global AgentioConfig.sandbox_ext_proc.
	// nil means fall back to the global configuration.
	ExtProc *ExtProcProvider `protobuf:"bytes,4,opt,name=ext_proc,json=extProc,proto3" json:"ext_proc,omitempty"`
	// Per-gateway connection pool and timeout settings. Controls HCM
	// StreamIdleTimeout, TCPProxy idle/max-connection-duration, and
	// per-host HTTP route timeouts. nil means use hardcoded defaults
	// (StreamIdleTimeout=30min, TCPProxy IdleTimeout=1h).
	ConnectionPool *ConnectionPoolSettings `protobuf:"bytes,5,opt,name=connection_pool,json=connectionPool,proto3" json:"connection_pool,omitempty"`
	// Per-gateway connect rate limit. Controls the rate at which new
	// H2 CONNECT streams are accepted on the connect_terminate HCM.
	// nil means no rate limiting.
	ConnectRateLimit *LocalRateLimitSettings `protobuf:"bytes,6,opt,name=connect_rate_limit,json=connectRateLimit,proto3" json:"connect_rate_limit,omitempty"`
	// External services whose DNS result is overridden at this gateway. The
	// original request port and detected protocol are preserved; only the
	// upstream address is replaced by the configured endpoint.
	ServiceEntries []*EgressServiceEntry `protobuf:"bytes,7,rep,name=service_entries,json=serviceEntries,proto3" json:"service_entries,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EgressGateway) Reset() {
	*x = EgressGateway{}
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressGateway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressGateway) ProtoMessage() {}

func (x *EgressGateway) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressGateway.ProtoReflect.Descriptor instead.
func (*EgressGateway) Descriptor() ([]byte, []int) {
	return file_api_config_v1_agentioconfig_proto_rawDescGZIP(), []int{1}
}

func (x *EgressGateway) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EgressGateway) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *EgressGateway) GetTlsTermination() *TlsTerminationConfig {
	if x != nil {
		return x.TlsTermination
	}
	return nil
}

func (x *EgressGateway) GetExtProc() *ExtProcProvider {
	if x != nil {
		return x.ExtProc
	}
	return nil
}

func (x *EgressGateway) GetConnectionPool() *ConnectionPoolSettings {
	if x != nil {
		return x.ConnectionPool
	}
	return nil
}

func (x *EgressGateway) GetConnectRateLimit() *LocalRateLimitSettings {
	if x != nil {
		return x.ConnectRateLimit
	}
	return nil
}

func (x *EgressGateway) GetServiceEntries() []*EgressServiceEntry {
	if x != nil {
		return x.ServiceEntries
	}
	return nil
}

// EgressServiceEntry binds one or more HTTP host identities to static upstream
// endpoints. Hosts are exact FQDNs; wildcard matching is intentionally not
// supported for static endpoints.
type EgressServiceEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTP Host / :authority and TLS SNI identities for this service.
	Hosts []string `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	// Static upstream endpoints. Requests are distributed evenly across them.
	// At least one endpoint is required.
	Endpoints     []*EgressServiceEntryEndpoint `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressServiceEntry) Reset() {
	*x = EgressServiceEntry{}
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressServiceEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressServiceEntry) ProtoMessage() {}

func (x *EgressServiceEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressServiceEntry.ProtoReflect.Descriptor instead.
func (*EgressServiceEntry) Descriptor() ([]byte, []int) {
	return file_api_config_v1_agentioconfig_proto_rawDescGZIP(), []int{2}
}

func (x *EgressServiceEntry) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *EgressServiceEntry) GetEndpoints() []*EgressServiceEntryEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

// EgressServiceEntryEndpoint identifies a static upstream address. The request's
// original destination port is used when connecting to this address.
type EgressServiceEntryEndpoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IPv4 address of the upstream endpoint.
	Address       string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressServiceEntryEndpoint) Reset() {
	*x = EgressServiceEntryEndpoint{}
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressServiceEntryEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressServiceEntryEndpoint) ProtoMessage() {}

func (x *EgressServiceEntryEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressServiceEntryEndpoint.ProtoReflect.Descriptor instead.
func (*EgressServiceEntryEndpoint) Descriptor() ([]byte, []int) {
	return file_api_config_v1_agentioconfig_proto_rawDescGZIP(), []int{3}
}

func (x *EgressServiceEntryEndpoint) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// TlsTerminationConfig defines which SNI domains should undergo TLS termination
// and which should bypass it in the sandbox egress gateway.
type TlsTerminationConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Domains that should undergo TLS termination using on-demand certificates.
	// Supports wildcards (e.g. *.example.com). When a TLS ClientHello's SNI
	// matches one of these domains, traffic is routed to the TLS termination
	// filter chain.
	IncludeHosts []string `protobuf:"bytes,1,rep,name=include_hosts,json=includeHosts,proto3" json:"include_hosts,omitempty"`
	// Domains that should bypass TLS termination. Traffic matching these
	// domains is forwarded as-is via the TCP filter chain without certificate
	// termination. Supports wildcards (e.g. *.internal.com).
	ExcludeHosts  []string `protobuf:"bytes,2,rep,name=exclude_hosts,json=excludeHosts,proto3" json:"exclude_hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TlsTerminationConfig) Reset() {
	*x = TlsTerminationConfig{}
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TlsTerminationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TlsTerminationConfig) ProtoMessage() {}

func (x *TlsTerminationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TlsTerminationConfig.ProtoReflect.Descriptor instead.
func (*TlsTerminationConfig) Descriptor() ([]byte, []int) {
	return file_api_config_v1_agentioconfig_proto_rawDescGZIP(), []int{4}
}

func (x *TlsTerminationConfig) GetIncludeHosts() []string {
	if x != nil {
		return x.IncludeHosts
	}
	return nil
}

func (x *TlsTerminationConfig) GetExcludeHosts() []string {
	if x != nil {
		return x.ExcludeHosts
	}
	return nil
}

// ExtProcProvider configures the external processing endpoint.
type ExtProcProvider struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service hostname or address for the ext_proc endpoint.
	Service string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// Service port for the ext_proc endpoint.
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// Request processing mode options.
	Request *ProcessingModeOptions `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	// Response processing mode options.
	Response *ProcessingModeOptions `protobuf:"bytes,4,opt,name=response,proto3" json:"response,omitempty"`
	// If true, the filter will be allowed to continue processing even if the ext_proc
	// server is unavailable or returns an error. Defaults to false.
	FailureModeAllow bool `protobuf:"varint,5,opt,name=failure_mode_allow,json=failureModeAllow,proto3" json:"failure_mode_allow,omitempty"`
	// Cluster-level settings for the ext_proc upstream cluster.
	ClusterSettings *ClusterSettings `protobuf:"bytes,6,opt,name=cluster_settings,json=clusterSettings,proto3" json:"cluster_settings,omitempty"`
	// Timeout for each message sent to the ext_proc server. If the server does not
	// respond within this duration, the request is considered failed.
	// Format: golang duration string (e.g. "200ms", "1s"). Defaults to 200ms if not set.
	MessageTimeout string `protobuf:"bytes,7,opt,name=message_timeout,json=messageTimeout,proto3" json:"message_timeout,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExtProcProvider) Reset() {
	*x = ExtProcProvider{}
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtProcProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtProcProvider) ProtoMessage() {}

func (x *ExtProcProvider) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtProcProvider.ProtoReflect.Descriptor instead.
func (*ExtProcProvider) Descriptor() ([]byte, []int) {
	return file_api_config_v1_agentioconfig_proto_rawDescGZIP(), []int{5}
}

func (x *ExtProcProvider) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ExtProcProvider) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ExtProcProvider) GetRequest() *ProcessingModeOptions {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ExtProcProvider) GetResponse() *ProcessingModeOptions {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ExtProcProvider) GetFailureModeAllow() bool {
	if x != nil {
		return x.FailureModeAllow
	}
	return false
}

func (x *ExtProcProvider) GetClusterSettings() *ClusterSettings {
	if x != nil {
		return x.ClusterSettings
	}
	return nil
}

func (x *ExtProcProvider) GetMessageTimeout() string {
	if x != nil {
		return x.MessageTimeout
	}
	return ""
}

// ClusterSettings configures upstream cluster behavior.
type ClusterSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTP protocol settings for the upstream cluster.
	Http          *HttpSettings `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterSettings) Reset() {
	*x = ClusterSettings{}
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterSettings) ProtoMessage() {}

func (x *ClusterSettings) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterSettings.ProtoReflect.Descriptor instead.
func (*ClusterSettings) Descriptor() ([]byte, []int) {
	return file_api_config_v1_agentioconfig_proto_rawDescGZIP(), []int{6}
}

func (x *ClusterSettings) GetHttp() *HttpSettings {
	if x != nil {
		return x.Http
	}
	return nil
}

// HttpSettings configures HTTP/2 protocol options for the upstream cluster.
type HttpSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of concurrent streams per HTTP/2 connection.
	// Defaults to 100 if not set.
	MaxConcurrentStreams uint32 `protobuf:"varint,1,opt,name=max_concurrent_streams,json=maxConcurrentStreams,proto3" json:"max_concurrent_streams,omitempty"`
	// Maximum number of requests per connection before it is closed.
	// 0 means unlimited (default behavior).
	MaxRequestsPerConnection uint32 `protobuf:"varint,2,opt,name=max_requests_per_connection,json=maxRequestsPerConnection,proto3" json:"max_requests_per_connection,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *HttpSettings) Reset() {
	*x = HttpSettings{}
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpSettings) ProtoMessage() {}

func (x *HttpSettings) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpSettings.ProtoReflect.Descriptor instead.
func (*HttpSettings) Descriptor() ([]byte, []int) {
	return file_api_config_v1_agentioconfig_proto_rawDescGZIP(), []int{7}
}

func (x *HttpSettings) GetMaxConcurrentStreams() uint32 {
	if x != nil {
		return x.MaxConcurrentStreams
	}
	return 0
}

func (x *HttpSettings) GetMaxRequestsPerConnection() uint32 {
	if x != nil {
		return x.MaxRequestsPerConnection
	}
	return 0
}

type ProcessingModeOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Header send mode: DEFAULT, SEND, or SKIP.
	HeaderMode HeaderSendMode `protobuf:"varint,1,opt,name=header_mode,json=headerMode,proto3,enum=agentio.config.v1.HeaderSendMode" json:"header_mode,omitempty"`
	// Attributes to include in ext_proc headers.
	Attributes    []string `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessingModeOptions) Reset() {
	*x = ProcessingModeOptions{}
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingModeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingModeOptions) ProtoMessage() {}

func (x *ProcessingModeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingModeOptions.ProtoReflect.Descriptor instead.
func (*ProcessingModeOptions) Descriptor() ([]byte, []int) {
	return file_api_config_v1_agentioconfig_proto_rawDescGZIP(), []int{8}
}

func (x *ProcessingModeOptions) GetHeaderMode() HeaderSendMode {
	if x != nil {
		return x.HeaderMode
	}
	return HeaderSendMode_DEFAULT
}

func (x *ProcessingModeOptions) GetAttributes() []string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// ConnectionPoolSettings controls TCP and HTTP connection management for the
// sandbox egress path.
type ConnectionPoolSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TCP-level connection pool settings.
	Tcp *TcpSettings `protobuf:"bytes,1,opt,name=tcp,proto3" json:"tcp,omitempty"`
	// HTTP-level connection pool and route settings.
	Http          *ConnectionPoolHttpSettings `protobuf:"bytes,2,opt,name=http,proto3" json:"http,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionPoolSettings) Reset() {
	*x = ConnectionPoolSettings{}
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionPoolSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionPoolSettings) ProtoMessage() {}

func (x *ConnectionPoolSettings) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionPoolSettings.ProtoReflect.Descriptor instead.
func (*ConnectionPoolSettings) Descriptor() ([]byte, []int) {
	return file_api_config_v1_agentioconfig_proto_rawDescGZIP(), []int{9}
}

func (x *ConnectionPoolSettings) GetTcp() *TcpSettings {
	if x != nil {
		return x.Tcp
	}
	return nil
}

func (x *ConnectionPoolSettings) GetHttp() *ConnectionPoolHttpSettings {
	if x != nil {
		return x.Http
	}
	return nil
}

// TcpSettings configures TCP connection timeouts and limits for the
// sandbox egress TCPProxy filters and passthrough path.
type TcpSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum time a TCP connection can be idle before Envoy closes it.
	// Applies to TCPProxy filters on tls-terminate and forward-tcp chains.
	// Default 1h.
	IdleTimeout *duration.Duration `protobuf:"bytes,1,opt,name=idle_timeout,json=idleTimeout,proto3" json:"idle_timeout,omitempty"`
	// Absolute maximum lifetime of a downstream TCP connection regardless
	// of activity. Default unset (no limit).
	MaxConnectionDuration *duration.Duration `protobuf:"bytes,2,opt,name=max_connection_duration,json=maxConnectionDuration,proto3" json:"max_connection_duration,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TcpSettings) Reset() {
	*x = TcpSettings{}
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TcpSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpSettings) ProtoMessage() {}

func (x *TcpSettings) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpSettings.ProtoReflect.Descriptor instead.
func (*TcpSettings) Descriptor() ([]byte, []int) {
	return file_api_config_v1_agentioconfig_proto_rawDescGZIP(), []int{10}
}

func (x *TcpSettings) GetIdleTimeout() *duration.Duration {
	if x != nil {
		return x.IdleTimeout
	}
	return nil
}

func (x *TcpSettings) GetMaxConnectionDuration() *duration.Duration {
	if x != nil {
		return x.MaxConnectionDuration
	}
	return nil
}

// ConnectionPoolHttpSettings configures HTTP connection manager and
// route-level settings for the sandbox egress HCM.
type ConnectionPoolHttpSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum time a stream (including upgraded WebSocket/SSE) can be idle
	// before Envoy closes it. Applies to the HCM StreamIdleTimeout.
	// Default 30min.
	StreamIdleTimeout *duration.Duration `protobuf:"bytes,1,opt,name=stream_idle_timeout,json=streamIdleTimeout,proto3" json:"stream_idle_timeout,omitempty"`
	// Default route settings applied to the fallback wildcard ("*")
	// VirtualHost. If nil, route timeout is 0 (disabled).
	DefaultRoute *HttpRouteSettings `protobuf:"bytes,2,opt,name=default_route,json=defaultRoute,proto3" json:"default_route,omitempty"`
	// Per-host route overrides. Each entry generates a dedicated VirtualHost
	// with the specified hosts as domains. Evaluated by Envoy's domain
	// matching (exact > suffix > prefix > wildcard).
	RouteOverrides []*HttpRouteOverride `protobuf:"bytes,3,rep,name=route_overrides,json=routeOverrides,proto3" json:"route_overrides,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConnectionPoolHttpSettings) Reset() {
	*x = ConnectionPoolHttpSettings{}
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionPoolHttpSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionPoolHttpSettings) ProtoMessage() {}

func (x *ConnectionPoolHttpSettings) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionPoolHttpSettings.ProtoReflect.Descriptor instead.
func (*ConnectionPoolHttpSettings) Descriptor() ([]byte, []int) {
	return file_api_config_v1_agentioconfig_proto_rawDescGZIP(), []int{11}
}

func (x *ConnectionPoolHttpSettings) GetStreamIdleTimeout() *duration.Duration {
	if x != nil {
		return x.StreamIdleTimeout
	}
	return nil
}

func (x *ConnectionPoolHttpSettings) GetDefaultRoute() *HttpRouteSettings {
	if x != nil {
		return x.DefaultRoute
	}
	return nil
}

func (x *ConnectionPoolHttpSettings) GetRouteOverrides() []*HttpRouteOverride {
	if x != nil {
		return x.RouteOverrides
	}
	return nil
}

// HttpRouteOverride binds HTTP route settings to a set of destination hosts.
type HttpRouteOverride struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Destination host patterns. Supports exact ("api.example.com") and
	// wildcard ("*.example.com") matching via Envoy VirtualHost domains.
	Hosts []string `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	// Route settings to apply for these hosts.
	Settings      *HttpRouteSettings `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRouteOverride) Reset() {
	*x = HttpRouteOverride{}
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRouteOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRouteOverride) ProtoMessage() {}

func (x *HttpRouteOverride) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRouteOverride.ProtoReflect.Descriptor instead.
func (*HttpRouteOverride) Descriptor() ([]byte, []int) {
	return file_api_config_v1_agentioconfig_proto_rawDescGZIP(), []int{12}
}

func (x *HttpRouteOverride) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *HttpRouteOverride) GetSettings() *HttpRouteSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

// HttpRouteSettings configures Envoy route-level timeout and retry behavior.
type HttpRouteSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total request timeout. 0 means disabled (Envoy default).
	Timeout *duration.Duration `protobuf:"bytes,1,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// Retry policy for HTTP requests. Uses the Istio HTTPRetry definition.
	Retries       *v1alpha3.HTTPRetry `protobuf:"bytes,2,opt,name=retries,proto3" json:"retries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRouteSettings) Reset() {
	*x = HttpRouteSettings{}
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRouteSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRouteSettings) ProtoMessage() {}

func (x *HttpRouteSettings) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRouteSettings.ProtoReflect.Descriptor instead.
func (*HttpRouteSettings) Descriptor() ([]byte, []int) {
	return file_api_config_v1_agentioconfig_proto_rawDescGZIP(), []int{13}
}

func (x *HttpRouteSettings) GetTimeout() *duration.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *HttpRouteSettings) GetRetries() *v1alpha3.HTTPRetry {
	if x != nil {
		return x.Retries
	}
	return nil
}

// LocalRateLimitSettings configures Envoy's local rate limit HTTP filter
// on the connect_terminate HCM. Each new H2 CONNECT stream (= one client
// TCP connection) consumes one token from the bucket.
type LocalRateLimitSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Global token bucket applied to all streams on this gateway.
	// Acts as the default when no descriptor matches. If unset, only
	// descriptor-level rate limits apply.
	TokenBucket *TokenBucket `protobuf:"bytes,1,opt,name=token_bucket,json=tokenBucket,proto3" json:"token_bucket,omitempty"`
	// Per-descriptor rate limit overrides. The first descriptor whose
	// entries fully match the request uses its own token bucket.
	Descriptors []*RateLimitDescriptor `protobuf:"bytes,2,rep,name=descriptors,proto3" json:"descriptors,omitempty"`
	// When true, each downstream H2 connection (ztunnel → egress gateway) gets
	// its own token bucket. Default false (shared across all connections).
	// Cannot be used together with wildcard descriptor values.
	PerDownstreamConnection bool `protobuf:"varint,3,opt,name=per_downstream_connection,json=perDownstreamConnection,proto3" json:"per_downstream_connection,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *LocalRateLimitSettings) Reset() {
	*x = LocalRateLimitSettings{}
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalRateLimitSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalRateLimitSettings) ProtoMessage() {}

func (x *LocalRateLimitSettings) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalRateLimitSettings.ProtoReflect.Descriptor instead.
func (*LocalRateLimitSettings) Descriptor() ([]byte, []int) {
	return file_api_config_v1_agentioconfig_proto_rawDescGZIP(), []int{14}
}

func (x *LocalRateLimitSettings) GetTokenBucket() *TokenBucket {
	if x != nil {
		return x.TokenBucket
	}
	return nil
}

func (x *LocalRateLimitSettings) GetDescriptors() []*RateLimitDescriptor {
	if x != nil {
		return x.Descriptors
	}
	return nil
}

func (x *LocalRateLimitSettings) GetPerDownstreamConnection() bool {
	if x != nil {
		return x.PerDownstreamConnection
	}
	return false
}

// TokenBucket configures a token bucket rate limiter.
type TokenBucket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum tokens the bucket can hold. Also the initial token count.
	MaxTokens uint32 `protobuf:"varint,1,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	// Tokens added per fill_interval. Defaults to 1 if not set.
	TokensPerFill uint32 `protobuf:"varint,2,opt,name=tokens_per_fill,json=tokensPerFill,proto3" json:"tokens_per_fill,omitempty"`
	// Interval at which tokens_per_fill tokens are added to the bucket.
	// Must be >= 50ms.
	FillInterval  *duration.Duration `protobuf:"bytes,3,opt,name=fill_interval,json=fillInterval,proto3" json:"fill_interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenBucket) Reset() {
	*x = TokenBucket{}
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenBucket) ProtoMessage() {}

func (x *TokenBucket) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenBucket.ProtoReflect.Descriptor instead.
func (*TokenBucket) Descriptor() ([]byte, []int) {
	return file_api_config_v1_agentioconfig_proto_rawDescGZIP(), []int{15}
}

func (x *TokenBucket) GetMaxTokens() uint32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *TokenBucket) GetTokensPerFill() uint32 {
	if x != nil {
		return x.TokensPerFill
	}
	return 0
}

func (x *TokenBucket) GetFillInterval() *duration.Duration {
	if x != nil {
		return x.FillInterval
	}
	return nil
}

// RateLimitDescriptor defines a set of descriptor entries and an
// associated token bucket. When all entries match, this descriptor's
// bucket is used instead of (or in addition to) the global bucket.
type RateLimitDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Entries that must all match for this descriptor to apply.
	Entries []*RateLimitEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	// Token bucket for streams matching this descriptor.
	TokenBucket   *TokenBucket `protobuf:"bytes,2,opt,name=token_bucket,json=tokenBucket,proto3" json:"token_bucket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimitDescriptor) Reset() {
	*x = RateLimitDescriptor{}
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitDescriptor) ProtoMessage() {}

func (x *RateLimitDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitDescriptor.ProtoReflect.Descriptor instead.
func (*RateLimitDescriptor) Descriptor() ([]byte, []int) {
	return file_api_config_v1_agentioconfig_proto_rawDescGZIP(), []int{16}
}

func (x *RateLimitDescriptor) GetEntries() []*RateLimitEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *RateLimitDescriptor) GetTokenBucket() *TokenBucket {
	if x != nil {
		return x.TokenBucket
	}
	return nil
}

// RateLimitEntry is a single key/value pair in a rate limit descriptor.
type RateLimitEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Descriptor key used in the Envoy descriptor matching.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Descriptor value to match. An empty string acts as a wildcard,
	// creating a dynamic per-unique-value token bucket (e.g. per-IP).
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// CEL expression that produces the descriptor value at runtime.
	// Uses the envoy.rate_limit_descriptors.expr extension. The
	// expression has access to filter_state, e.g.:
	//
	//	filter_state["downstream_peer"].name
	//	filter_state["downstream_peer"].namespace
	//	filter_state["io.istio.peer_principal"]
	Cel           string `protobuf:"bytes,3,opt,name=cel,proto3" json:"cel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimitEntry) Reset() {
	*x = RateLimitEntry{}
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitEntry) ProtoMessage() {}

func (x *RateLimitEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_agentioconfig_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitEntry.ProtoReflect.Descriptor instead.
func (*RateLimitEntry) Descriptor() ([]byte, []int) {
	return file_api_config_v1_agentioconfig_proto_rawDescGZIP(), []int{17}
}

func (x *RateLimitEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RateLimitEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *RateLimitEntry) GetCel() string {
	if x != nil {
		return x.Cel
	}
	return ""
}

var File_api_config_v1_agentioconfig_proto protoreflect.FileDescriptor

const file_api_config_v1_agentioconfig_proto_rawDesc = "" +
	"\n" +
	"!api/config/v1/agentioconfig.proto\x12\x11agentio.config.v1\x1a$api/extensions/v1/egresspolicy.proto\x1a\x1egoogle/protobuf/duration.proto\x1a)networking/v1alpha3/virtual_service.proto\"\xb6\x02\n" +
	"\rAgentioConfig\x12L\n" +
	"\x10sandbox_ext_proc\x18\x01 \x01(\v2\".agentio.config.v1.ExtProcProviderR\x0esandboxExtProc\x12V\n" +
	"\x0fegress_policies\x18\x02 \x03(\v2-.kruise.networking.extensions.v1.EgressPolicyR\x0eegressPolicies\x124\n" +
	"\x16sandbox_ignored_labels\x18\x03 \x03(\tR\x14sandboxIgnoredLabels\x12I\n" +
	"\x0fegress_gateways\x18\x04 \x03(\v2 .agentio.config.v1.EgressGatewayR\x0eegressGateways\"\xcf\x03\n" +
	"\rEgressGateway\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12P\n" +
	"\x0ftls_termination\x18\x03 \x01(\v2'.agentio.config.v1.TlsTerminationConfigR\x0etlsTermination\x12=\n" +
	"\bext_proc\x18\x04 \x01(\v2\".agentio.config.v1.ExtProcProviderR\aextProc\x12R\n" +
	"\x0fconnection_pool\x18\x05 \x01(\v2).agentio.config.v1.ConnectionPoolSettingsR\x0econnectionPool\x12W\n" +
	"\x12connect_rate_limit\x18\x06 \x01(\v2).agentio.config.v1.LocalRateLimitSettingsR\x10connectRateLimit\x12N\n" +
	"\x0fservice_entries\x18\a \x03(\v2%.agentio.config.v1.EgressServiceEntryR\x0eserviceEntries\"w\n" +
	"\x12EgressServiceEntry\x12\x14\n" +
	"\x05hosts\x18\x01 \x03(\tR\x05hosts\x12K\n" +
	"\tendpoints\x18\x02 \x03(\v2-.agentio.config.v1.EgressServiceEntryEndpointR\tendpoints\"6\n" +
	"\x1aEgressServiceEntryEndpoint\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"`\n" +
	"\x14TlsTerminationConfig\x12#\n" +
	"\rinclude_hosts\x18\x01 \x03(\tR\fincludeHosts\x12#\n" +
	"\rexclude_hosts\x18\x02 \x03(\tR\fexcludeHosts\"\xef\x02\n" +
	"\x0fExtProcProvider\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12B\n" +
	"\arequest\x18\x03 \x01(\v2(.agentio.config.v1.ProcessingModeOptionsR\arequest\x12D\n" +
	"\bresponse\x18\x04 \x01(\v2(.agentio.config.v1.ProcessingModeOptionsR\bresponse\x12,\n" +
	"\x12failure_mode_allow\x18\x05 \x01(\bR\x10failureModeAllow\x12M\n" +
	"\x10cluster_settings\x18\x06 \x01(\v2\".agentio.config.v1.ClusterSettingsR\x0fclusterSettings\x12'\n" +
	"\x0fmessage_timeout\x18\a \x01(\tR\x0emessageTimeout\"F\n" +
	"\x0fClusterSettings\x123\n" +
	"\x04http\x18\x01 \x01(\v2\x1f.agentio.config.v1.HttpSettingsR\x04http\"\x83\x01\n" +
	"\fHttpSettings\x124\n" +
	"\x16max_concurrent_streams\x18\x01 \x01(\rR\x14maxConcurrentStreams\x12=\n" +
	"\x1bmax_requests_per_connection\x18\x02 \x01(\rR\x18maxRequestsPerConnection\"{\n" +
	"\x15ProcessingModeOptions\x12B\n" +
	"\vheader_mode\x18\x01 \x01(\x0e2!.agentio.config.v1.HeaderSendModeR\n" +
	"headerMode\x12\x1e\n" +
	"\n" +
	"attributes\x18\x02 \x03(\tR\n" +
	"attributes\"\x8d\x01\n" +
	"\x16ConnectionPoolSettings\x120\n" +
	"\x03tcp\x18\x01 \x01(\v2\x1e.agentio.config.v1.TcpSettingsR\x03tcp\x12A\n" +
	"\x04http\x18\x02 \x01(\v2-.agentio.config.v1.ConnectionPoolHttpSettingsR\x04http\"\x9e\x01\n" +
	"\vTcpSettings\x12<\n" +
	"\fidle_timeout\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\vidleTimeout\x12Q\n" +
	"\x17max_connection_duration\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x15maxConnectionDuration\"\x81\x02\n" +
	"\x1aConnectionPoolHttpSettings\x12I\n" +
	"\x13stream_idle_timeout\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x11streamIdleTimeout\x12I\n" +
	"\rdefault_route\x18\x02 \x01(\v2$.agentio.config.v1.HttpRouteSettingsR\fdefaultRoute\x12M\n" +
	"\x0froute_overrides\x18\x03 \x03(\v2$.agentio.config.v1.HttpRouteOverrideR\x0erouteOverrides\"k\n" +
	"\x11HttpRouteOverride\x12\x14\n" +
	"\x05hosts\x18\x01 \x03(\tR\x05hosts\x12@\n" +
	"\bsettings\x18\x02 \x01(\v2$.agentio.config.v1.HttpRouteSettingsR\bsettings\"\x88\x01\n" +
	"\x11HttpRouteSettings\x123\n" +
	"\atimeout\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12>\n" +
	"\aretries\x18\x02 \x01(\v2$.istio.networking.v1alpha3.HTTPRetryR\aretries\"\xe1\x01\n" +
	"\x16LocalRateLimitSettings\x12A\n" +
	"\ftoken_bucket\x18\x01 \x01(\v2\x1e.agentio.config.v1.TokenBucketR\vtokenBucket\x12H\n" +
	"\vdescriptors\x18\x02 \x03(\v2&.agentio.config.v1.RateLimitDescriptorR\vdescriptors\x12:\n" +
	"\x19per_downstream_connection\x18\x03 \x01(\bR\x17perDownstreamConnection\"\x94\x01\n" +
	"\vTokenBucket\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x01 \x01(\rR\tmaxTokens\x12&\n" +
	"\x0ftokens_per_fill\x18\x02 \x01(\rR\rtokensPerFill\x12>\n" +
	"\rfill_interval\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\ffillInterval\"\x95\x01\n" +
	"\x13RateLimitDescriptor\x12;\n" +
	"\aentries\x18\x01 \x03(\v2!.agentio.config.v1.RateLimitEntryR\aentries\x12A\n" +
	"\ftoken_bucket\x18\x02 \x01(\v2\x1e.agentio.config.v1.TokenBucketR\vtokenBucket\"J\n" +
	"\x0eRateLimitEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x10\n" +
	"\x03cel\x18\x03 \x01(\tR\x03cel*1\n" +
	"\x0eHeaderSendMode\x12\v\n" +
	"\aDEFAULT\x10\x00\x12\b\n" +
	"\x04SEND\x10\x01\x12\b\n" +
	"\x04SKIP\x10\x02B6Z4github.com/openkruise/agentio/api/config/v1;configv1b\x06proto3"

var (
	file_api_config_v1_agentioconfig_proto_rawDescOnce sync.Once
	file_api_config_v1_agentioconfig_proto_rawDescData []byte
)

func file_api_config_v1_agentioconfig_proto_rawDescGZIP() []byte {
	file_api_config_v1_agentioconfig_proto_rawDescOnce.Do(func() {
		file_api_config_v1_agentioconfig_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_config_v1_agentioconfig_proto_rawDesc), len(file_api_config_v1_agentioconfig_proto_rawDesc)))
	})
	return file_api_config_v1_agentioconfig_proto_rawDescData
}

var file_api_config_v1_agentioconfig_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_config_v1_agentioconfig_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_config_v1_agentioconfig_proto_goTypes = []any{
	(HeaderSendMode)(0),                // 0: agentio.config.v1.HeaderSendMode
	(*AgentioConfig)(nil),              // 1: agentio.config.v1.AgentioConfig
	(*EgressGateway)(nil),              // 2: agentio.config.v1.EgressGateway
	(*EgressServiceEntry)(nil),         // 3: agentio.config.v1.EgressServiceEntry
	(*EgressServiceEntryEndpoint)(nil), // 4: agentio.config.v1.EgressServiceEntryEndpoint
	(*TlsTerminationConfig)(nil),       // 5: agentio.config.v1.TlsTerminationConfig
	(*ExtProcProvider)(nil),            // 6: agentio.config.v1.ExtProcProvider
	(*ClusterSettings)(nil),            // 7: agentio.config.v1.ClusterSettings
	(*HttpSettings)(nil),               // 8: agentio.config.v1.HttpSettings
	(*ProcessingModeOptions)(nil),      // 9: agentio.config.v1.ProcessingModeOptions
	(*ConnectionPoolSettings)(nil),     // 10: agentio.config.v1.ConnectionPoolSettings
	(*TcpSettings)(nil),                // 11: agentio.config.v1.TcpSettings
	(*ConnectionPoolHttpSettings)(nil), // 12: agentio.config.v1.ConnectionPoolHttpSettings
	(*HttpRouteOverride)(nil),          // 13: agentio.config.v1.HttpRouteOverride
	(*HttpRouteSettings)(nil),          // 14: agentio.config.v1.HttpRouteSettings
	(*LocalRateLimitSettings)(nil),     // 15: agentio.config.v1.LocalRateLimitSettings
	(*TokenBucket)(nil),                // 16: agentio.config.v1.TokenBucket
	(*RateLimitDescriptor)(nil),        // 17: agentio.config.v1.RateLimitDescriptor
	(*RateLimitEntry)(nil),             // 18: agentio.config.v1.RateLimitEntry
	(*v1.EgressPolicy)(nil),            // 19: kruise.networking.extensions.v1.EgressPolicy
	(*duration.Duration)(nil),          // 20: google.protobuf.Duration
	(*v1alpha3.HTTPRetry)(nil),         // 21: istio.networking.v1alpha3.HTTPRetry
}
var file_api_config_v1_agentioconfig_proto_depIdxs = []int32{
	6,  // 0: agentio.config.v1.AgentioConfig.sandbox_ext_proc:type_name -> agentio.config.v1.ExtProcProvider
	19, // 1: agentio.config.v1.AgentioConfig.egress_policies:type_name -> kruise.networking.extensions.v1.EgressPolicy
	2,  // 2: agentio.config.v1.AgentioConfig.egress_gateways:type_name -> agentio.config.v1.EgressGateway
	5,  // 3: agentio.config.v1.EgressGateway.tls_termination:type_name -> agentio.config.v1.TlsTerminationConfig
	6,  // 4: agentio.config.v1.EgressGateway.ext_proc:type_name -> agentio.config.v1.ExtProcProvider
	10, // 5: agentio.config.v1.EgressGateway.connection_pool:type_name -> agentio.config.v1.ConnectionPoolSettings
	15, // 6: agentio.config.v1.EgressGateway.connect_rate_limit:type_name -> agentio.config.v1.LocalRateLimitSettings
	3,  // 7: agentio.config.v1.EgressGateway.service_entries:type_name -> agentio.config.v1.EgressServiceEntry
	4,  // 8: agentio.config.v1.EgressServiceEntry.endpoints:type_name -> agentio.config.v1.EgressServiceEntryEndpoint
	9,  // 9: agentio.config.v1.ExtProcProvider.request:type_name -> agentio.config.v1.ProcessingModeOptions
	9,  // 10: agentio.config.v1.ExtProcProvider.response:type_name -> agentio.config.v1.ProcessingModeOptions
	7,  // 11: agentio.config.v1.ExtProcProvider.cluster_settings:type_name -> agentio.config.v1.ClusterSettings
	8,  // 12: agentio.config.v1.ClusterSettings.http:type_name -> agentio.config.v1.HttpSettings
	0,  // 13: agentio.config.v1.ProcessingModeOptions.header_mode:type_name -> agentio.config.v1.HeaderSendMode
	11, // 14: agentio.config.v1.ConnectionPoolSettings.tcp:type_name -> agentio.config.v1.TcpSettings
	12, // 15: agentio.config.v1.ConnectionPoolSettings.http:type_name -> agentio.config.v1.ConnectionPoolHttpSettings
	20, // 16: agentio.config.v1.TcpSettings.idle_timeout:type_name -> google.protobuf.Duration
	20, // 17: agentio.config.v1.TcpSettings.max_connection_duration:type_name -> google.protobuf.Duration
	20, // 18: agentio.config.v1.ConnectionPoolHttpSettings.stream_idle_timeout:type_name -> google.protobuf.Duration
	14, // 19: agentio.config.v1.ConnectionPoolHttpSettings.default_route:type_name -> agentio.config.v1.HttpRouteSettings
	13, // 20: agentio.config.v1.ConnectionPoolHttpSettings.route_overrides:type_name -> agentio.config.v1.HttpRouteOverride
	14, // 21: agentio.config.v1.HttpRouteOverride.settings:type_name -> agentio.config.v1.HttpRouteSettings
	20, // 22: agentio.config.v1.HttpRouteSettings.timeout:type_name -> google.protobuf.Duration
	21, // 23: agentio.config.v1.HttpRouteSettings.retries:type_name -> istio.networking.v1alpha3.HTTPRetry
	16, // 24: agentio.config.v1.LocalRateLimitSettings.token_bucket:type_name -> agentio.config.v1.TokenBucket
	17, // 25: agentio.config.v1.LocalRateLimitSettings.descriptors:type_name -> agentio.config.v1.RateLimitDescriptor
	20, // 26: agentio.config.v1.TokenBucket.fill_interval:type_name -> google.protobuf.Duration
	18, // 27: agentio.config.v1.RateLimitDescriptor.entries:type_name -> agentio.config.v1.RateLimitEntry
	16, // 28: agentio.config.v1.RateLimitDescriptor.token_bucket:type_name -> agentio.config.v1.TokenBucket
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_api_config_v1_agentioconfig_proto_init() }
func file_api_config_v1_agentioconfig_proto_init() {
	if File_api_config_v1_agentioconfig_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_config_v1_agentioconfig_proto_rawDesc), len(file_api_config_v1_agentioconfig_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_config_v1_agentioconfig_proto_goTypes,
		DependencyIndexes: file_api_config_v1_agentioconfig_proto_depIdxs,
		EnumInfos:         file_api_config_v1_agentioconfig_proto_enumTypes,
		MessageInfos:      file_api_config_v1_agentioconfig_proto_msgTypes,
	}.Build()
	File_api_config_v1_agentioconfig_proto = out.File
	file_api_config_v1_agentioconfig_proto_goTypes = nil
	file_api_config_v1_agentioconfig_proto_depIdxs = nil
}
