// Copyright 2026 The Kruise Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: api/config/v1/epeconfig.proto

package configv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EPEConfig is decoded from the watched ConfigMap's data.config entry.
// Secret and ConfigMap references default to the configuration namespace.
//
// Example: register a callout service and a default credential service.
//
//	extensionProviders:
//	- name: policy-check
//	  httpCallout:
//	    url: https://policy.example.com/check
//	    timeout: 500ms
//	- name: corporate
//	  credentialProvider:
//	    url: https://credentials.example.com/get
//	    timeout: 2s
//	defaultProviders:
//	  credentialProvider: corporate
type EPEConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Named services available to EPE. Names must be unique across provider types.
	// Layers merge by name; a same-name entry replaces the whole provider.
	// Omitted or null lists inherit the lower layer; an explicit [] clears it.
	ExtensionProviders []*ExtensionProvider `protobuf:"bytes,1,rep,name=extension_providers,json=extensionProviders,proto3" json:"extension_providers,omitempty"`
	// Default services used when a caller does not select a provider explicitly.
	DefaultProviders *DefaultExtensionProviders `protobuf:"bytes,2,opt,name=default_providers,json=defaultProviders,proto3" json:"default_providers,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EPEConfig) Reset() {
	*x = EPEConfig{}
	mi := &file_api_config_v1_epeconfig_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EPEConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EPEConfig) ProtoMessage() {}

func (x *EPEConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_epeconfig_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EPEConfig.ProtoReflect.Descriptor instead.
func (*EPEConfig) Descriptor() ([]byte, []int) {
	return file_api_config_v1_epeconfig_proto_rawDescGZIP(), []int{0}
}

func (x *EPEConfig) GetExtensionProviders() []*ExtensionProvider {
	if x != nil {
		return x.ExtensionProviders
	}
	return nil
}

func (x *EPEConfig) GetDefaultProviders() *DefaultExtensionProviders {
	if x != nil {
		return x.DefaultProviders
	}
	return nil
}

// ExtensionProvider registers one typed service under a unique name.
type ExtensionProvider struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Local registration name, such as "corporate". Must be a DNS subdomain.
	// Environment defaults use "agentio-default-credential-provider"; this is an
	// ordinary name that configuration layers can override like any other.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Exactly one provider type must be configured.
	//
	// Types that are valid to be assigned to Provider:
	//
	//	*ExtensionProvider_HttpCallout
	//	*ExtensionProvider_CredentialProvider
	Provider      isExtensionProvider_Provider `protobuf_oneof:"provider"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionProvider) Reset() {
	*x = ExtensionProvider{}
	mi := &file_api_config_v1_epeconfig_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionProvider) ProtoMessage() {}

func (x *ExtensionProvider) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_epeconfig_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionProvider.ProtoReflect.Descriptor instead.
func (*ExtensionProvider) Descriptor() ([]byte, []int) {
	return file_api_config_v1_epeconfig_proto_rawDescGZIP(), []int{1}
}

func (x *ExtensionProvider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExtensionProvider) GetProvider() isExtensionProvider_Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *ExtensionProvider) GetHttpCallout() *HTTPCalloutProvider {
	if x != nil {
		if x, ok := x.Provider.(*ExtensionProvider_HttpCallout); ok {
			return x.HttpCallout
		}
	}
	return nil
}

func (x *ExtensionProvider) GetCredentialProvider() *CredentialProvider {
	if x != nil {
		if x, ok := x.Provider.(*ExtensionProvider_CredentialProvider); ok {
			return x.CredentialProvider
		}
	}
	return nil
}

type isExtensionProvider_Provider interface {
	isExtensionProvider_Provider()
}

type ExtensionProvider_HttpCallout struct {
	HttpCallout *HTTPCalloutProvider `protobuf:"bytes,2,opt,name=http_callout,json=httpCallout,proto3,oneof"`
}

type ExtensionProvider_CredentialProvider struct {
	CredentialProvider *CredentialProvider `protobuf:"bytes,3,opt,name=credential_provider,json=credentialProvider,proto3,oneof"`
}

func (*ExtensionProvider_HttpCallout) isExtensionProvider_Provider() {}

func (*ExtensionProvider_CredentialProvider) isExtensionProvider_Provider() {}

// DefaultExtensionProviders selects services by their ExtensionProvider names.
type DefaultExtensionProviders struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Used only by credential references without an explicit provider.
	// Omitting defaultProviders inherits the lower layer's selection. An explicit
	// empty credentialProvider disables default selection.
	// Must identify a credentialProvider to serve lookups. A missing or wrong-type
	// provider fails at call time; no other provider is selected as a fallback.
	CredentialProvider string `protobuf:"bytes,1,opt,name=credential_provider,json=credentialProvider,proto3" json:"credential_provider,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DefaultExtensionProviders) Reset() {
	*x = DefaultExtensionProviders{}
	mi := &file_api_config_v1_epeconfig_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefaultExtensionProviders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultExtensionProviders) ProtoMessage() {}

func (x *DefaultExtensionProviders) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_epeconfig_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultExtensionProviders.ProtoReflect.Descriptor instead.
func (*DefaultExtensionProviders) Descriptor() ([]byte, []int) {
	return file_api_config_v1_epeconfig_proto_rawDescGZIP(), []int{2}
}

func (x *DefaultExtensionProviders) GetCredentialProvider() string {
	if x != nil {
		return x.CredentialProvider
	}
	return ""
}

// HTTPCalloutProvider defines a service implementing EPE's HTTPCallout protocol:
// EPE posts a JSON Invocation and expects a JSON Decision in response.
// This is distinct from the Envoy ext_proc service that EPE implements.
// Redirects are not followed. The client's response size limit is configured by
// HTTP_CALLOUT_MAX_RESPONSE_BYTES, independently of the rule's body disclosure limit.
type HTTPCalloutProvider struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute HTTP(S) endpoint, without userinfo or a fragment.
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// Positive Go duration, such as "500ms" or "2s". Defaults to 500ms.
	// Bounds the HTTP request, including response body reads. An earlier caller
	// deadline takes precedence; time spent queued by the caller is not included.
	Timeout string `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// HTTPS transport settings. Omission uses system roots without a client certificate.
	Tls           *ProviderTLS `protobuf:"bytes,4,opt,name=tls,proto3" json:"tls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPCalloutProvider) Reset() {
	*x = HTTPCalloutProvider{}
	mi := &file_api_config_v1_epeconfig_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPCalloutProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPCalloutProvider) ProtoMessage() {}

func (x *HTTPCalloutProvider) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_epeconfig_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPCalloutProvider.ProtoReflect.Descriptor instead.
func (*HTTPCalloutProvider) Descriptor() ([]byte, []int) {
	return file_api_config_v1_epeconfig_proto_rawDescGZIP(), []int{3}
}

func (x *HTTPCalloutProvider) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HTTPCalloutProvider) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

func (x *HTTPCalloutProvider) GetTls() *ProviderTLS {
	if x != nil {
		return x.Tls
	}
	return nil
}

// CredentialProvider defines the connection to a credential service.
// Its local ExtensionProvider name selects this connection; the credential
// request's credentialProviderName selects the remote credential configuration.
// Each provider has independent caches, configured process-wide at startup by
// TOKEN_CACHE_TTL, TOKEN_CACHE_MAX_SIZE, and STS_CACHE_MAX_SIZE.
type CredentialProvider struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute HTTP(S) endpoint, without userinfo or a fragment.
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// Positive Go duration, such as "2s". Defaults to 500ms.
	Timeout string `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// HTTPS transport settings. Omission uses system roots without a client certificate.
	Tls           *ProviderTLS `protobuf:"bytes,3,opt,name=tls,proto3" json:"tls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialProvider) Reset() {
	*x = CredentialProvider{}
	mi := &file_api_config_v1_epeconfig_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialProvider) ProtoMessage() {}

func (x *CredentialProvider) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_epeconfig_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialProvider.ProtoReflect.Descriptor instead.
func (*CredentialProvider) Descriptor() ([]byte, []int) {
	return file_api_config_v1_epeconfig_proto_rawDescGZIP(), []int{4}
}

func (x *CredentialProvider) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CredentialProvider) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

func (x *CredentialProvider) GetTls() *ProviderTLS {
	if x != nil {
		return x.Tls
	}
	return nil
}

// ProviderTLS configures HTTPS connections for either provider type. Referenced
// Secrets, ConfigMaps, and files are watched; changes rebuild the affected provider and cache.
// CA and client identity sources are independent, so a Secret CA can be combined
// with a file-based client certificate, or vice versa.
// Omitting client identity configures server-only TLS; a client certificate is
// provided for mTLS only when configured and requested by the remote server.
//
// Example: verify only the server using a ConfigMap's ca.crt trust bundle.
// Place this block under httpCallout or credentialProvider. Omitting tls entirely
// for an HTTPS URL uses system roots and provides no client certificate.
//
//	tls:
//	  caConfigMapRef:
//	    name: provider-ca
//
// Example: use Secrets in the EPEConfig namespace for trust and client identity.
//
//	tls:
//	  caSecretRef:
//	    name: provider-ca
//	  clientCertificateSecretRef:
//	    name: epe-client
//
// Example: use PEM files supplied by the EPE deployment. Paths refer to the EPE
// container filesystem; configuring a path does not create a volume mount.
// Both path changes and certificate contents are reloaded without a restart.
//
//	tls:
//	  caCertificateFile: /etc/epe/certs/ca.crt
//	  clientCertificateFiles:
//	    certificateFile: /etc/epe/certs/tls.crt
//	    privateKeyFile: /etc/epe/certs/tls.key
type ProviderTLS struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Defaults to URL hostname. Mutually exclusive with peerSpiffeIDs.
	ServerName string `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	// Exact URI SAN allowlist, for example:
	//
	//	peerSpiffeIDs: ["spiffe://cluster.local/ns/agentio-system/sa/credential-provider"]
	//
	// Verifies the certificate chain and requires a matching SPIFFE ID instead of
	// hostname verification. Mutually exclusive with serverName and insecureSkipVerify.
	PeerSpiffeIds []string `protobuf:"bytes,2,rep,name=peer_spiffe_ids,json=peerSpiffeIDs,proto3" json:"peer_spiffe_ids,omitempty"`
	// Selects at most one CA source. Omission uses system roots.
	// An explicit but unavailable source fails unless optional is true.
	//
	// Types that are valid to be assigned to CaSource:
	//
	//	*ProviderTLS_CaSecretRef
	//	*ProviderTLS_CaConfigMapRef
	//	*ProviderTLS_CaCertificateFile
	CaSource isProviderTLS_CaSource `protobuf_oneof:"ca_source"`
	// Selects at most one client identity source. Omission provides no client
	// certificate and does not require optional: true for server-only TLS.
	//
	// Types that are valid to be assigned to ClientCertificateSource:
	//
	//	*ProviderTLS_ClientCertificateSecretRef
	//	*ProviderTLS_ClientCertificateFiles
	ClientCertificateSource isProviderTLS_ClientCertificateSource `protobuf_oneof:"client_certificate_source"`
	// Disables server certificate verification; cannot be combined with peer IDs.
	InsecureSkipVerify bool `protobuf:"varint,8,opt,name=insecure_skip_verify,json=insecureSkipVerify,proto3" json:"insecure_skip_verify,omitempty"`
	// Missing or unusable material uses system roots / no client certificate.
	// By default explicit sources fail closed. This does not disable verification.
	Optional      bool `protobuf:"varint,9,opt,name=optional,proto3" json:"optional,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderTLS) Reset() {
	*x = ProviderTLS{}
	mi := &file_api_config_v1_epeconfig_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderTLS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderTLS) ProtoMessage() {}

func (x *ProviderTLS) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_epeconfig_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderTLS.ProtoReflect.Descriptor instead.
func (*ProviderTLS) Descriptor() ([]byte, []int) {
	return file_api_config_v1_epeconfig_proto_rawDescGZIP(), []int{5}
}

func (x *ProviderTLS) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ProviderTLS) GetPeerSpiffeIds() []string {
	if x != nil {
		return x.PeerSpiffeIds
	}
	return nil
}

func (x *ProviderTLS) GetCaSource() isProviderTLS_CaSource {
	if x != nil {
		return x.CaSource
	}
	return nil
}

func (x *ProviderTLS) GetCaSecretRef() *TargetReference {
	if x != nil {
		if x, ok := x.CaSource.(*ProviderTLS_CaSecretRef); ok {
			return x.CaSecretRef
		}
	}
	return nil
}

func (x *ProviderTLS) GetCaConfigMapRef() *TargetReference {
	if x != nil {
		if x, ok := x.CaSource.(*ProviderTLS_CaConfigMapRef); ok {
			return x.CaConfigMapRef
		}
	}
	return nil
}

func (x *ProviderTLS) GetCaCertificateFile() string {
	if x != nil {
		if x, ok := x.CaSource.(*ProviderTLS_CaCertificateFile); ok {
			return x.CaCertificateFile
		}
	}
	return ""
}

func (x *ProviderTLS) GetClientCertificateSource() isProviderTLS_ClientCertificateSource {
	if x != nil {
		return x.ClientCertificateSource
	}
	return nil
}

func (x *ProviderTLS) GetClientCertificateSecretRef() *TargetReference {
	if x != nil {
		if x, ok := x.ClientCertificateSource.(*ProviderTLS_ClientCertificateSecretRef); ok {
			return x.ClientCertificateSecretRef
		}
	}
	return nil
}

func (x *ProviderTLS) GetClientCertificateFiles() *ProviderClientCertificateFiles {
	if x != nil {
		if x, ok := x.ClientCertificateSource.(*ProviderTLS_ClientCertificateFiles); ok {
			return x.ClientCertificateFiles
		}
	}
	return nil
}

func (x *ProviderTLS) GetInsecureSkipVerify() bool {
	if x != nil {
		return x.InsecureSkipVerify
	}
	return false
}

func (x *ProviderTLS) GetOptional() bool {
	if x != nil {
		return x.Optional
	}
	return false
}

type isProviderTLS_CaSource interface {
	isProviderTLS_CaSource()
}

type ProviderTLS_CaSecretRef struct {
	// PEM CA bundle from the Secret's fixed ca.crt data key. Missing or empty
	// ca.crt is unavailable material, handled according to optional.
	CaSecretRef *TargetReference `protobuf:"bytes,3,opt,name=ca_secret_ref,json=caSecretRef,proto3,oneof"`
}

type ProviderTLS_CaConfigMapRef struct {
	// PEM CA bundle from the ConfigMap's fixed data["ca.crt"] entry. Missing
	// or empty ca.crt is unavailable material, handled according to optional.
	CaConfigMapRef *TargetReference `protobuf:"bytes,4,opt,name=ca_config_map_ref,json=caConfigMapRef,proto3,oneof"`
}

type ProviderTLS_CaCertificateFile struct {
	// Non-empty path to a PEM CA bundle inside the EPE container.
	CaCertificateFile string `protobuf:"bytes,5,opt,name=ca_certificate_file,json=caCertificateFile,proto3,oneof"`
}

func (*ProviderTLS_CaSecretRef) isProviderTLS_CaSource() {}

func (*ProviderTLS_CaConfigMapRef) isProviderTLS_CaSource() {}

func (*ProviderTLS_CaCertificateFile) isProviderTLS_CaSource() {}

type isProviderTLS_ClientCertificateSource interface {
	isProviderTLS_ClientCertificateSource()
}

type ProviderTLS_ClientCertificateSecretRef struct {
	// Client identity from the Secret's fixed tls.crt and tls.key data keys,
	// including for environment-derived defaults. Missing or empty entries
	// are unavailable material, handled according to optional.
	ClientCertificateSecretRef *TargetReference `protobuf:"bytes,6,opt,name=client_certificate_secret_ref,json=clientCertificateSecretRef,proto3,oneof"`
}

type ProviderTLS_ClientCertificateFiles struct {
	// Client certificate and private key files, configured together.
	ClientCertificateFiles *ProviderClientCertificateFiles `protobuf:"bytes,7,opt,name=client_certificate_files,json=clientCertificateFiles,proto3,oneof"`
}

func (*ProviderTLS_ClientCertificateSecretRef) isProviderTLS_ClientCertificateSource() {}

func (*ProviderTLS_ClientCertificateFiles) isProviderTLS_ClientCertificateSource() {}

// TargetReference identifies a Kubernetes object. The referring field defines
// the resource kind and fixed data keys to read; key names cannot be configured.
type TargetReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required resource name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Defaults to the EPEConfig namespace, not the calling workload's namespace.
	Namespace     string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetReference) Reset() {
	*x = TargetReference{}
	mi := &file_api_config_v1_epeconfig_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetReference) ProtoMessage() {}

func (x *TargetReference) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_epeconfig_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetReference.ProtoReflect.Descriptor instead.
func (*TargetReference) Descriptor() ([]byte, []int) {
	return file_api_config_v1_epeconfig_proto_rawDescGZIP(), []int{6}
}

func (x *TargetReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TargetReference) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// ProviderClientCertificateFiles reads a PEM client certificate/key pair from
// the EPE container filesystem. Both paths are required. File names are arbitrary;
// the fixed tls.crt/tls.key data keys apply only to Secret references.
type ProviderClientCertificateFiles struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Non-empty path to the PEM client certificate.
	CertificateFile string `protobuf:"bytes,1,opt,name=certificate_file,json=certificateFile,proto3" json:"certificate_file,omitempty"`
	// Non-empty path to the matching PEM private key.
	PrivateKeyFile string `protobuf:"bytes,2,opt,name=private_key_file,json=privateKeyFile,proto3" json:"private_key_file,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProviderClientCertificateFiles) Reset() {
	*x = ProviderClientCertificateFiles{}
	mi := &file_api_config_v1_epeconfig_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderClientCertificateFiles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderClientCertificateFiles) ProtoMessage() {}

func (x *ProviderClientCertificateFiles) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_epeconfig_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderClientCertificateFiles.ProtoReflect.Descriptor instead.
func (*ProviderClientCertificateFiles) Descriptor() ([]byte, []int) {
	return file_api_config_v1_epeconfig_proto_rawDescGZIP(), []int{7}
}

func (x *ProviderClientCertificateFiles) GetCertificateFile() string {
	if x != nil {
		return x.CertificateFile
	}
	return ""
}

func (x *ProviderClientCertificateFiles) GetPrivateKeyFile() string {
	if x != nil {
		return x.PrivateKeyFile
	}
	return ""
}

var File_api_config_v1_epeconfig_proto protoreflect.FileDescriptor

const file_api_config_v1_epeconfig_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/config/v1/epeconfig.proto\x12\x11agentio.config.v1\"\xbd\x01\n" +
	"\tEPEConfig\x12U\n" +
	"\x13extension_providers\x18\x01 \x03(\v2$.agentio.config.v1.ExtensionProviderR\x12extensionProviders\x12Y\n" +
	"\x11default_providers\x18\x02 \x01(\v2,.agentio.config.v1.DefaultExtensionProvidersR\x10defaultProviders\"\xda\x01\n" +
	"\x11ExtensionProvider\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12K\n" +
	"\fhttp_callout\x18\x02 \x01(\v2&.agentio.config.v1.HTTPCalloutProviderH\x00R\vhttpCallout\x12X\n" +
	"\x13credential_provider\x18\x03 \x01(\v2%.agentio.config.v1.CredentialProviderH\x00R\x12credentialProviderB\n" +
	"\n" +
	"\bprovider\"L\n" +
	"\x19DefaultExtensionProviders\x12/\n" +
	"\x13credential_provider\x18\x01 \x01(\tR\x12credentialProvider\"s\n" +
	"\x13HTTPCalloutProvider\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\tR\atimeout\x120\n" +
	"\x03tls\x18\x04 \x01(\v2\x1e.agentio.config.v1.ProviderTLSR\x03tls\"r\n" +
	"\x12CredentialProvider\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\tR\atimeout\x120\n" +
	"\x03tls\x18\x03 \x01(\v2\x1e.agentio.config.v1.ProviderTLSR\x03tls\"\xf3\x04\n" +
	"\vProviderTLS\x12\x1f\n" +
	"\vserver_name\x18\x01 \x01(\tR\n" +
	"serverName\x12&\n" +
	"\x0fpeer_spiffe_ids\x18\x02 \x03(\tR\rpeerSpiffeIDs\x12H\n" +
	"\rca_secret_ref\x18\x03 \x01(\v2\".agentio.config.v1.TargetReferenceH\x00R\vcaSecretRef\x12O\n" +
	"\x11ca_config_map_ref\x18\x04 \x01(\v2\".agentio.config.v1.TargetReferenceH\x00R\x0ecaConfigMapRef\x120\n" +
	"\x13ca_certificate_file\x18\x05 \x01(\tH\x00R\x11caCertificateFile\x12g\n" +
	"\x1dclient_certificate_secret_ref\x18\x06 \x01(\v2\".agentio.config.v1.TargetReferenceH\x01R\x1aclientCertificateSecretRef\x12m\n" +
	"\x18client_certificate_files\x18\a \x01(\v21.agentio.config.v1.ProviderClientCertificateFilesH\x01R\x16clientCertificateFiles\x120\n" +
	"\x14insecure_skip_verify\x18\b \x01(\bR\x12insecureSkipVerify\x12\x1a\n" +
	"\boptional\x18\t \x01(\bR\boptionalB\v\n" +
	"\tca_sourceB\x1b\n" +
	"\x19client_certificate_source\"C\n" +
	"\x0fTargetReference\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"u\n" +
	"\x1eProviderClientCertificateFiles\x12)\n" +
	"\x10certificate_file\x18\x01 \x01(\tR\x0fcertificateFile\x12(\n" +
	"\x10private_key_file\x18\x02 \x01(\tR\x0eprivateKeyFileB6Z4github.com/openkruise/agentio/api/config/v1;configv1b\x06proto3"

var (
	file_api_config_v1_epeconfig_proto_rawDescOnce sync.Once
	file_api_config_v1_epeconfig_proto_rawDescData []byte
)

func file_api_config_v1_epeconfig_proto_rawDescGZIP() []byte {
	file_api_config_v1_epeconfig_proto_rawDescOnce.Do(func() {
		file_api_config_v1_epeconfig_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_config_v1_epeconfig_proto_rawDesc), len(file_api_config_v1_epeconfig_proto_rawDesc)))
	})
	return file_api_config_v1_epeconfig_proto_rawDescData
}

var file_api_config_v1_epeconfig_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_config_v1_epeconfig_proto_goTypes = []any{
	(*EPEConfig)(nil),                      // 0: agentio.config.v1.EPEConfig
	(*ExtensionProvider)(nil),              // 1: agentio.config.v1.ExtensionProvider
	(*DefaultExtensionProviders)(nil),      // 2: agentio.config.v1.DefaultExtensionProviders
	(*HTTPCalloutProvider)(nil),            // 3: agentio.config.v1.HTTPCalloutProvider
	(*CredentialProvider)(nil),             // 4: agentio.config.v1.CredentialProvider
	(*ProviderTLS)(nil),                    // 5: agentio.config.v1.ProviderTLS
	(*TargetReference)(nil),                // 6: agentio.config.v1.TargetReference
	(*ProviderClientCertificateFiles)(nil), // 7: agentio.config.v1.ProviderClientCertificateFiles
}
var file_api_config_v1_epeconfig_proto_depIdxs = []int32{
	1,  // 0: agentio.config.v1.EPEConfig.extension_providers:type_name -> agentio.config.v1.ExtensionProvider
	2,  // 1: agentio.config.v1.EPEConfig.default_providers:type_name -> agentio.config.v1.DefaultExtensionProviders
	3,  // 2: agentio.config.v1.ExtensionProvider.http_callout:type_name -> agentio.config.v1.HTTPCalloutProvider
	4,  // 3: agentio.config.v1.ExtensionProvider.credential_provider:type_name -> agentio.config.v1.CredentialProvider
	5,  // 4: agentio.config.v1.HTTPCalloutProvider.tls:type_name -> agentio.config.v1.ProviderTLS
	5,  // 5: agentio.config.v1.CredentialProvider.tls:type_name -> agentio.config.v1.ProviderTLS
	6,  // 6: agentio.config.v1.ProviderTLS.ca_secret_ref:type_name -> agentio.config.v1.TargetReference
	6,  // 7: agentio.config.v1.ProviderTLS.ca_config_map_ref:type_name -> agentio.config.v1.TargetReference
	6,  // 8: agentio.config.v1.ProviderTLS.client_certificate_secret_ref:type_name -> agentio.config.v1.TargetReference
	7,  // 9: agentio.config.v1.ProviderTLS.client_certificate_files:type_name -> agentio.config.v1.ProviderClientCertificateFiles
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_config_v1_epeconfig_proto_init() }
func file_api_config_v1_epeconfig_proto_init() {
	if File_api_config_v1_epeconfig_proto != nil {
		return
	}
	file_api_config_v1_epeconfig_proto_msgTypes[1].OneofWrappers = []any{
		(*ExtensionProvider_HttpCallout)(nil),
		(*ExtensionProvider_CredentialProvider)(nil),
	}
	file_api_config_v1_epeconfig_proto_msgTypes[5].OneofWrappers = []any{
		(*ProviderTLS_CaSecretRef)(nil),
		(*ProviderTLS_CaConfigMapRef)(nil),
		(*ProviderTLS_CaCertificateFile)(nil),
		(*ProviderTLS_ClientCertificateSecretRef)(nil),
		(*ProviderTLS_ClientCertificateFiles)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_config_v1_epeconfig_proto_rawDesc), len(file_api_config_v1_epeconfig_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_config_v1_epeconfig_proto_goTypes,
		DependencyIndexes: file_api_config_v1_epeconfig_proto_depIdxs,
		MessageInfos:      file_api_config_v1_epeconfig_proto_msgTypes,
	}.Build()
	File_api_config_v1_epeconfig_proto = out.File
	file_api_config_v1_epeconfig_proto_goTypes = nil
	file_api_config_v1_epeconfig_proto_depIdxs = nil
}
