#!/usr/bin/env bash

# Copyright 2026 The Kruise Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Regenerates the CRD API reference pages in docs/reference from the CRD
# schemas shipped in manifests/charts/agentio/crds.

set -euo pipefail

script_dir="$(cd "$(dirname "$0")" && pwd)"
repo_root="$(cd "$script_dir/.." && pwd)"
crds_dir="$repo_root/manifests/charts/agentio/crds"
template="$script_dir/crd-docs.tmpl"
crdoc_version="v0.6.4"

temporary_dir="$(mktemp -d)"
trap 'rm -rf "$temporary_dir"' EXIT

# generate <output> <title> <intro> <crd yaml>...
generate() {
  local output="$1" title="$2" intro="$3"
  shift 3

  local staging="$temporary_dir/$(basename "$output" .md)"
  mkdir -p "$staging"
  cp "$@" "$staging/"

  local body="$temporary_dir/$(basename "$output")"
  go run "fybrik.io/crdoc@$crdoc_version" \
    --resources "$staging" \
    --template "$template" \
    --output "$body"

  {
    printf '# %s\n\n' "$title"
    printf '<!-- Generated by tools/generate-crd-docs.sh; do not edit manually. -->\n'
    printf '<!-- markdownlint-disable MD007 MD012 MD032 -->\n\n'
    printf '%s\n' "$intro"
    cat "$body"
  } > "$output"
}

generate "$repo_root/docs/reference/traffic-policy-api.md" \
  "TrafficPolicy API reference" \
  "This page is generated from the CustomResourceDefinition schemas installed by the Agentio chart. See [Configure a TrafficPolicy](../tasks/configure-traffic-policy.md) for usage." \
  "$crds_dir/trafficpolicies.yaml" \
  "$crds_dir/globaltrafficpolicies.yaml"

generate "$repo_root/docs/reference/security-profile-api.md" \
  "SecurityProfile API reference" \
  "This page is generated from the CustomResourceDefinition schemas installed by the Agentio chart. See [SecurityProfile reference](security-profile.md) for the evaluation behavior." \
  "$crds_dir/securityprofiles.yaml" \
  "$crds_dir/globalsecurityprofiles.yaml"
