// Copyright 2026 The Kruise Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: api/sandbox/v1/egressrouting.proto

package sandboxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Access denial belongs to TrafficPolicy, not routing.
type EgressRouting_Action int32

const (
	// Continue normal forwarding without selecting an egress gateway.
	EgressRouting_PASSTHROUGH EgressRouting_Action = 0
	EgressRouting_GATEWAY     EgressRouting_Action = 1
)

// Enum value maps for EgressRouting_Action.
var (
	EgressRouting_Action_name = map[int32]string{
		0: "PASSTHROUGH",
		1: "GATEWAY",
	}
	EgressRouting_Action_value = map[string]int32{
		"PASSTHROUGH": 0,
		"GATEWAY":     1,
	}
)

func (x EgressRouting_Action) Enum() *EgressRouting_Action {
	p := new(EgressRouting_Action)
	*p = x
	return p
}

func (x EgressRouting_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EgressRouting_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_api_sandbox_v1_egressrouting_proto_enumTypes[0].Descriptor()
}

func (EgressRouting_Action) Type() protoreflect.EnumType {
	return &file_api_sandbox_v1_egressrouting_proto_enumTypes[0]
}

func (x EgressRouting_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EgressRouting_Action.Descriptor instead.
func (EgressRouting_Action) EnumDescriptor() ([]byte, []int) {
	return file_api_sandbox_v1_egressrouting_proto_rawDescGZIP(), []int{0, 0}
}

// EgressRouting selects a path after TrafficPolicy permits the connection.
// Routing matches the original destination, before gateway redirection.
// Absent routing, an empty route list, or no matching route uses PASSTHROUGH.
// To require a gateway for all egress, end the list with a catch-all GATEWAY.
type EgressRouting struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// First matching route wins, in control-plane order.
	Routes        []*EgressRouting_Route `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressRouting) Reset() {
	*x = EgressRouting{}
	mi := &file_api_sandbox_v1_egressrouting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressRouting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressRouting) ProtoMessage() {}

func (x *EgressRouting) ProtoReflect() protoreflect.Message {
	mi := &file_api_sandbox_v1_egressrouting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressRouting.ProtoReflect.Descriptor instead.
func (*EgressRouting) Descriptor() ([]byte, []int) {
	return file_api_sandbox_v1_egressrouting_proto_rawDescGZIP(), []int{0}
}

func (x *EgressRouting) GetRoutes() []*EgressRouting_Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

type EgressRouting_Route struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Destination CIDRs and ports are ANDed; entries within each list are ORed.
	// An empty list is unconstrained. CIDRs are normalized by the control plane.
	MatchCidrs []string `protobuf:"bytes,1,rep,name=match_cidrs,json=matchCidrs,proto3" json:"match_cidrs,omitempty"`
	// Exact destination ports as decimal strings in 1..65535.
	MatchPorts []string `protobuf:"bytes,2,rep,name=match_ports,json=matchPorts,proto3" json:"match_ports,omitempty"`
	// Forwarding action for matching traffic.
	Action EgressRouting_Action `protobuf:"varint,3,opt,name=action,proto3,enum=io.kruise.agentio.sandbox.v1.EgressRouting_Action" json:"action,omitempty"`
	// Required for GATEWAY, absent for PASSTHROUGH. An unavailable selected gateway
	// fails the connection; consumers must not fall back to PASSTHROUGH.
	Gateway       *EgressRouting_GatewayAddress `protobuf:"bytes,4,opt,name=gateway,proto3" json:"gateway,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressRouting_Route) Reset() {
	*x = EgressRouting_Route{}
	mi := &file_api_sandbox_v1_egressrouting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressRouting_Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressRouting_Route) ProtoMessage() {}

func (x *EgressRouting_Route) ProtoReflect() protoreflect.Message {
	mi := &file_api_sandbox_v1_egressrouting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressRouting_Route.ProtoReflect.Descriptor instead.
func (*EgressRouting_Route) Descriptor() ([]byte, []int) {
	return file_api_sandbox_v1_egressrouting_proto_rawDescGZIP(), []int{0, 0}
}

func (x *EgressRouting_Route) GetMatchCidrs() []string {
	if x != nil {
		return x.MatchCidrs
	}
	return nil
}

func (x *EgressRouting_Route) GetMatchPorts() []string {
	if x != nil {
		return x.MatchPorts
	}
	return nil
}

func (x *EgressRouting_Route) GetAction() EgressRouting_Action {
	if x != nil {
		return x.Action
	}
	return EgressRouting_PASSTHROUGH
}

func (x *EgressRouting_Route) GetGateway() *EgressRouting_GatewayAddress {
	if x != nil {
		return x.Gateway
	}
	return nil
}

type EgressRouting_GatewayAddress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gateway service name, e.g. egress-gateway.agentio-system.svc.cluster.local.
	Service string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// Gateway port.
	Port          uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressRouting_GatewayAddress) Reset() {
	*x = EgressRouting_GatewayAddress{}
	mi := &file_api_sandbox_v1_egressrouting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressRouting_GatewayAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressRouting_GatewayAddress) ProtoMessage() {}

func (x *EgressRouting_GatewayAddress) ProtoReflect() protoreflect.Message {
	mi := &file_api_sandbox_v1_egressrouting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressRouting_GatewayAddress.ProtoReflect.Descriptor instead.
func (*EgressRouting_GatewayAddress) Descriptor() ([]byte, []int) {
	return file_api_sandbox_v1_egressrouting_proto_rawDescGZIP(), []int{0, 1}
}

func (x *EgressRouting_GatewayAddress) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *EgressRouting_GatewayAddress) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

var File_api_sandbox_v1_egressrouting_proto protoreflect.FileDescriptor

const file_api_sandbox_v1_egressrouting_proto_rawDesc = "" +
	"\n" +
	"\"api/sandbox/v1/egressrouting.proto\x12\x1cio.kruise.agentio.sandbox.v1\"\xb0\x03\n" +
	"\rEgressRouting\x12I\n" +
	"\x06routes\x18\x01 \x03(\v21.io.kruise.agentio.sandbox.v1.EgressRouting.RouteR\x06routes\x1a\xeb\x01\n" +
	"\x05Route\x12\x1f\n" +
	"\vmatch_cidrs\x18\x01 \x03(\tR\n" +
	"matchCidrs\x12\x1f\n" +
	"\vmatch_ports\x18\x02 \x03(\tR\n" +
	"matchPorts\x12J\n" +
	"\x06action\x18\x03 \x01(\x0e22.io.kruise.agentio.sandbox.v1.EgressRouting.ActionR\x06action\x12T\n" +
	"\agateway\x18\x04 \x01(\v2:.io.kruise.agentio.sandbox.v1.EgressRouting.GatewayAddressR\agateway\x1a>\n" +
	"\x0eGatewayAddress\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"&\n" +
	"\x06Action\x12\x0f\n" +
	"\vPASSTHROUGH\x10\x00\x12\v\n" +
	"\aGATEWAY\x10\x01B8Z6github.com/openkruise/agentio/api/sandbox/v1;sandboxv1b\x06proto3"

var (
	file_api_sandbox_v1_egressrouting_proto_rawDescOnce sync.Once
	file_api_sandbox_v1_egressrouting_proto_rawDescData []byte
)

func file_api_sandbox_v1_egressrouting_proto_rawDescGZIP() []byte {
	file_api_sandbox_v1_egressrouting_proto_rawDescOnce.Do(func() {
		file_api_sandbox_v1_egressrouting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_sandbox_v1_egressrouting_proto_rawDesc), len(file_api_sandbox_v1_egressrouting_proto_rawDesc)))
	})
	return file_api_sandbox_v1_egressrouting_proto_rawDescData
}

var file_api_sandbox_v1_egressrouting_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_sandbox_v1_egressrouting_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_sandbox_v1_egressrouting_proto_goTypes = []any{
	(EgressRouting_Action)(0),            // 0: io.kruise.agentio.sandbox.v1.EgressRouting.Action
	(*EgressRouting)(nil),                // 1: io.kruise.agentio.sandbox.v1.EgressRouting
	(*EgressRouting_Route)(nil),          // 2: io.kruise.agentio.sandbox.v1.EgressRouting.Route
	(*EgressRouting_GatewayAddress)(nil), // 3: io.kruise.agentio.sandbox.v1.EgressRouting.GatewayAddress
}
var file_api_sandbox_v1_egressrouting_proto_depIdxs = []int32{
	2, // 0: io.kruise.agentio.sandbox.v1.EgressRouting.routes:type_name -> io.kruise.agentio.sandbox.v1.EgressRouting.Route
	0, // 1: io.kruise.agentio.sandbox.v1.EgressRouting.Route.action:type_name -> io.kruise.agentio.sandbox.v1.EgressRouting.Action
	3, // 2: io.kruise.agentio.sandbox.v1.EgressRouting.Route.gateway:type_name -> io.kruise.agentio.sandbox.v1.EgressRouting.GatewayAddress
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_sandbox_v1_egressrouting_proto_init() }
func file_api_sandbox_v1_egressrouting_proto_init() {
	if File_api_sandbox_v1_egressrouting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_sandbox_v1_egressrouting_proto_rawDesc), len(file_api_sandbox_v1_egressrouting_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_sandbox_v1_egressrouting_proto_goTypes,
		DependencyIndexes: file_api_sandbox_v1_egressrouting_proto_depIdxs,
		EnumInfos:         file_api_sandbox_v1_egressrouting_proto_enumTypes,
		MessageInfos:      file_api_sandbox_v1_egressrouting_proto_msgTypes,
	}.Build()
	File_api_sandbox_v1_egressrouting_proto = out.File
	file_api_sandbox_v1_egressrouting_proto_goTypes = nil
	file_api_sandbox_v1_egressrouting_proto_depIdxs = nil
}
