// Copyright 2026 The Kruise Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: api/sandbox/v1/sandbox.proto

package sandboxv1

import (
	any1 "github.com/golang/protobuf/ptypes/any"
	v1 "github.com/openkruise/agentio/api/security/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Provider-neutral lifecycle state of the Sandbox.
type SandboxState int32

const (
	// The current runtime state is unknown; do not assume it is RUNNING.
	SandboxState_SANDBOX_STATE_UNSPECIFIED SandboxState = 0
	// Initial startup has not completed.
	SandboxState_SANDBOX_STATE_PENDING SandboxState = 1
	// Execution is active. This does not imply application readiness.
	SandboxState_SANDBOX_STATE_RUNNING SandboxState = 2
	// Execution is confirmed paused, with state retained for resumption.
	SandboxState_SANDBOX_STATE_PAUSED SandboxState = 3
	// This execution has ended, successfully or unsuccessfully.
	// The Sandbox resource may still exist.
	SandboxState_SANDBOX_STATE_STOPPED SandboxState = 4
)

// Enum value maps for SandboxState.
var (
	SandboxState_name = map[int32]string{
		0: "SANDBOX_STATE_UNSPECIFIED",
		1: "SANDBOX_STATE_PENDING",
		2: "SANDBOX_STATE_RUNNING",
		3: "SANDBOX_STATE_PAUSED",
		4: "SANDBOX_STATE_STOPPED",
	}
	SandboxState_value = map[string]int32{
		"SANDBOX_STATE_UNSPECIFIED": 0,
		"SANDBOX_STATE_PENDING":     1,
		"SANDBOX_STATE_RUNNING":     2,
		"SANDBOX_STATE_PAUSED":      3,
		"SANDBOX_STATE_STOPPED":     4,
	}
)

func (x SandboxState) Enum() *SandboxState {
	p := new(SandboxState)
	*p = x
	return p
}

func (x SandboxState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SandboxState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_sandbox_v1_sandbox_proto_enumTypes[0].Descriptor()
}

func (SandboxState) Type() protoreflect.EnumType {
	return &file_api_sandbox_v1_sandbox_proto_enumTypes[0]
}

func (x SandboxState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SandboxState.Descriptor instead.
func (SandboxState) EnumDescriptor() ([]byte, []int) {
	return file_api_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{0}
}

// Sandbox carries the current host binding and complete policy view for a
// stable Sandbox UID. Consumers must authenticate the attester and validate
// their RuntimeAttachment independently of the reported lifecycle state.
type Sandbox struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Uid   string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// The single Workload currently hosting this Sandbox. Absent when unassigned.
	// Replacing or clearing this field invalidates the previous host binding.
	Attester *Sandbox_Attester `protobuf:"bytes,2,opt,name=attester,proto3" json:"attester,omitempty"`
	// Latest observed runtime lifecycle state, independent of policy compilation.
	// Intermediate transitions may be coalesced during discovery delivery.
	State SandboxState `protobuf:"varint,3,opt,name=state,proto3,enum=io.kruise.agentio.sandbox.v1.SandboxState" json:"state,omitempty"`
	// Effective exit routing, delivered atomically with this Sandbox.
	EgressRouting *EgressRouting `protobuf:"bytes,4,opt,name=egress_routing,json=egressRouting,proto3" json:"egress_routing,omitempty"`
	// Effective policies in evaluation order; rules retain their source order.
	// All bodies are delivered together in this Sandbox resource.
	TrafficPolicies []*v1.TrafficPolicy `protobuf:"bytes,5,rep,name=traffic_policies,json=trafficPolicies,proto3" json:"traffic_policies,omitempty"`
	// Inline extension policy bodies, replaced atomically with this Sandbox.
	// Entries of the same type retain their evaluation order. Different types
	// define their own execution stages; list order does not order those stages.
	// Consumers must reject this Sandbox update if any extension is unsupported
	// or cannot be decoded. Runtime state does not imply extension support.
	Extensions    []*any1.Any `protobuf:"bytes,6,rep,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sandbox) Reset() {
	*x = Sandbox{}
	mi := &file_api_sandbox_v1_sandbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sandbox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sandbox) ProtoMessage() {}

func (x *Sandbox) ProtoReflect() protoreflect.Message {
	mi := &file_api_sandbox_v1_sandbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sandbox.ProtoReflect.Descriptor instead.
func (*Sandbox) Descriptor() ([]byte, []int) {
	return file_api_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{0}
}

func (x *Sandbox) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Sandbox) GetAttester() *Sandbox_Attester {
	if x != nil {
		return x.Attester
	}
	return nil
}

func (x *Sandbox) GetState() SandboxState {
	if x != nil {
		return x.State
	}
	return SandboxState_SANDBOX_STATE_UNSPECIFIED
}

func (x *Sandbox) GetEgressRouting() *EgressRouting {
	if x != nil {
		return x.EgressRouting
	}
	return nil
}

func (x *Sandbox) GetTrafficPolicies() []*v1.TrafficPolicy {
	if x != nil {
		return x.TrafficPolicies
	}
	return nil
}

func (x *Sandbox) GetExtensions() []*any1.Any {
	if x != nil {
		return x.Extensions
	}
	return nil
}

type Sandbox_Attester struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required, non-empty Workload.uid, used to locate its WDS Address resource.
	// Treat as an opaque identifier; do not infer endpoint type from its format.
	WorkloadUid   string `protobuf:"bytes,1,opt,name=workload_uid,json=workloadUid,proto3" json:"workload_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sandbox_Attester) Reset() {
	*x = Sandbox_Attester{}
	mi := &file_api_sandbox_v1_sandbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sandbox_Attester) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sandbox_Attester) ProtoMessage() {}

func (x *Sandbox_Attester) ProtoReflect() protoreflect.Message {
	mi := &file_api_sandbox_v1_sandbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sandbox_Attester.ProtoReflect.Descriptor instead.
func (*Sandbox_Attester) Descriptor() ([]byte, []int) {
	return file_api_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Sandbox_Attester) GetWorkloadUid() string {
	if x != nil {
		return x.WorkloadUid
	}
	return ""
}

var File_api_sandbox_v1_sandbox_proto protoreflect.FileDescriptor

const file_api_sandbox_v1_sandbox_proto_rawDesc = "" +
	"\n" +
	"\x1capi/sandbox/v1/sandbox.proto\x12\x1cio.kruise.agentio.sandbox.v1\x1a\"api/sandbox/v1/egressrouting.proto\x1a#api/security/v1/trafficpolicy.proto\x1a\x19google/protobuf/any.proto\"\xbb\x03\n" +
	"\aSandbox\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12J\n" +
	"\battester\x18\x02 \x01(\v2..io.kruise.agentio.sandbox.v1.Sandbox.AttesterR\battester\x12@\n" +
	"\x05state\x18\x03 \x01(\x0e2*.io.kruise.agentio.sandbox.v1.SandboxStateR\x05state\x12R\n" +
	"\x0eegress_routing\x18\x04 \x01(\v2+.io.kruise.agentio.sandbox.v1.EgressRoutingR\regressRouting\x12W\n" +
	"\x10traffic_policies\x18\x05 \x03(\v2,.io.kruise.agentio.security.v1.TrafficPolicyR\x0ftrafficPolicies\x124\n" +
	"\n" +
	"extensions\x18\x06 \x03(\v2\x14.google.protobuf.AnyR\n" +
	"extensions\x1a-\n" +
	"\bAttester\x12!\n" +
	"\fworkload_uid\x18\x01 \x01(\tR\vworkloadUid*\x98\x01\n" +
	"\fSandboxState\x12\x1d\n" +
	"\x19SANDBOX_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SANDBOX_STATE_PENDING\x10\x01\x12\x19\n" +
	"\x15SANDBOX_STATE_RUNNING\x10\x02\x12\x18\n" +
	"\x14SANDBOX_STATE_PAUSED\x10\x03\x12\x19\n" +
	"\x15SANDBOX_STATE_STOPPED\x10\x04B8Z6github.com/openkruise/agentio/api/sandbox/v1;sandboxv1b\x06proto3"

var (
	file_api_sandbox_v1_sandbox_proto_rawDescOnce sync.Once
	file_api_sandbox_v1_sandbox_proto_rawDescData []byte
)

func file_api_sandbox_v1_sandbox_proto_rawDescGZIP() []byte {
	file_api_sandbox_v1_sandbox_proto_rawDescOnce.Do(func() {
		file_api_sandbox_v1_sandbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_sandbox_v1_sandbox_proto_rawDesc), len(file_api_sandbox_v1_sandbox_proto_rawDesc)))
	})
	return file_api_sandbox_v1_sandbox_proto_rawDescData
}

var file_api_sandbox_v1_sandbox_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_sandbox_v1_sandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_sandbox_v1_sandbox_proto_goTypes = []any{
	(SandboxState)(0),        // 0: io.kruise.agentio.sandbox.v1.SandboxState
	(*Sandbox)(nil),          // 1: io.kruise.agentio.sandbox.v1.Sandbox
	(*Sandbox_Attester)(nil), // 2: io.kruise.agentio.sandbox.v1.Sandbox.Attester
	(*EgressRouting)(nil),    // 3: io.kruise.agentio.sandbox.v1.EgressRouting
	(*v1.TrafficPolicy)(nil), // 4: io.kruise.agentio.security.v1.TrafficPolicy
	(*any1.Any)(nil),         // 5: google.protobuf.Any
}
var file_api_sandbox_v1_sandbox_proto_depIdxs = []int32{
	2, // 0: io.kruise.agentio.sandbox.v1.Sandbox.attester:type_name -> io.kruise.agentio.sandbox.v1.Sandbox.Attester
	0, // 1: io.kruise.agentio.sandbox.v1.Sandbox.state:type_name -> io.kruise.agentio.sandbox.v1.SandboxState
	3, // 2: io.kruise.agentio.sandbox.v1.Sandbox.egress_routing:type_name -> io.kruise.agentio.sandbox.v1.EgressRouting
	4, // 3: io.kruise.agentio.sandbox.v1.Sandbox.traffic_policies:type_name -> io.kruise.agentio.security.v1.TrafficPolicy
	5, // 4: io.kruise.agentio.sandbox.v1.Sandbox.extensions:type_name -> google.protobuf.Any
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_sandbox_v1_sandbox_proto_init() }
func file_api_sandbox_v1_sandbox_proto_init() {
	if File_api_sandbox_v1_sandbox_proto != nil {
		return
	}
	file_api_sandbox_v1_egressrouting_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_sandbox_v1_sandbox_proto_rawDesc), len(file_api_sandbox_v1_sandbox_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_sandbox_v1_sandbox_proto_goTypes,
		DependencyIndexes: file_api_sandbox_v1_sandbox_proto_depIdxs,
		EnumInfos:         file_api_sandbox_v1_sandbox_proto_enumTypes,
		MessageInfos:      file_api_sandbox_v1_sandbox_proto_msgTypes,
	}.Build()
	File_api_sandbox_v1_sandbox_proto = out.File
	file_api_sandbox_v1_sandbox_proto_goTypes = nil
	file_api_sandbox_v1_sandbox_proto_depIdxs = nil
}
