{{- if and (eq .Values.epe.mode "managed") .Values.epe.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "epe.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "epe.labels" . | nindent 4 }}
data:
  config: |
    {{- toYaml .Values.epe.config | nindent 4 }}
{{- end }}
